### ISSUE TITLE
Multiple taxonomies in a single phyloseq object

### ISSUE THREAD

**Issue by dcat4** [joey711/phyloseq#1002]
Hi there,

I'm curious as to whether there's a way to merge 2 or more unique taxonomies (e.g., using different reference databases) into a single phyloseq object. For example, in a single phyloseq object you'd have an otu_table(), sample_data(), tax_table_A(), and tax_table_B(). Basically I'm looking for efficient ways to track different taxonomies through various normalization, filtering, etc, procedures. I recognize there's ways to come up with a "best" or "consensus" taxonomic assignment from multiple databases using statistics output by the RDP classifiers, but I'd like to monitor the effects of different reference databases on downstream results.

I've been exploring the merge_XX functions in phyloseq along with these and other forums for solutions and haven't come across anything that makes sense. Please let me know if you can offer any advice for functions or other packages that might allow this. 

Thanks for your time and consideration!

**Comment by joey711** [comment]
@dcat4 I have not had many requests for this, but you can do it without too much effort by:

- (1) Importing the taxonomy tables from different methods separately. The row-names of these tables need to be the same, and in the same order.
- (2) Appending something to their column names so that "Phylum" from method-1 is distinguishable from "Phylum" from method-2. E.g. `m1_Phylum`, and `m2_Phylum`.
- (3) Column bind using `cbind()`
- (4) `tax_table()`
- (5) Get rich :-) 

I probably won't support something like this directly, but hopefully that helps you in your endeavor!
