### ISSUE TITLE
plot_heatmap displaying as sequence

### ISSUE THREAD

**Issue by jjrahn** [joey711/phyloseq#1024]
I am a novice R-er and am probably making a simple mistake but I can't seem to find a description of this problem in other posts. I am working with a relatively large metagenomics data set that I successfully wrangled into R using the DADA2 platform. I'm following the Tutorial on the DADA2 page and everything up to this point has worked perfectly. Now I'm trying to get the heatmap to plot. Potentially relevant information:

R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

> packageVersion('ggplot2')
[1] ‘3.1.0’
> packageVersion('phyloseq')
[1] ‘1.24.2’

> ps
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 26482 taxa and 40 samples ]
sample_data() Sample Data:       [ 40 samples by 2 sample variables ]
tax_table()   Taxonomy Table:    [ 26482 taxa by 7 taxonomic ranks ]

Then limited to top 20 families as described in the DADA2 tutorial to get ps.top20
> ps.top20
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 20 taxa and 40 samples ]
sample_data() Sample Data:       [ 40 samples by 2 sample variables ]
tax_table()   Taxonomy Table:    [ 20 taxa by 7 taxonomic ranks ]

>plot_heatpmap(ps.top20)
yields a bunch of sequence but no heatmap
![rplot01](https://user-images.githubusercontent.com/42574870/47608408-fe854b80-d9fa-11e8-8f72-539e8c8d8bfc.png)

I apologize if this is a stupid, simple question. Thanks for your time!

**Comment by joey711** [comment]
Not stupid. I think your ASVs are still named according to their full amplicon DNA sequence, rather than some short-hand unique identifier that is more suitable to plotting. Try `taxa_names(ps.top20)` and if you get back a character vector of DNA sequences, then I guessed correctly, and you'll need to rename the ASVs by something more "plottable". 

A search around some DADA2 tutorials should give an example for how to do this.
