### ISSUE TITLE
can not manually reproduce tax_glom() - whats going on here?

### ISSUE THREAD

**Issue by s-christel** [joey711/phyloseq#1033]
Hello there! 

One of my collaborators has noticed a problem in my 16S analysis pipeline. It appears that when using tax_glom to calculate relative abundance of a class I am getting one number, and when I calculate the number manually I get another.

I am using the tax_glom() function to summarize all "classes" of my phyloseq object phy_bac, transform the reads to relative abundance, filter all classes that have <1% abundance, and melt the object to obtain a dataframe.
```
phy_bac %>%
                tax_glom(taxrank = "Class") %>%
                transform_sample_counts(function(x) {x/sum(x)} ) %>%
                filter_taxa(filterfun(kOverA(1, percentage)), TRUE) %>%
                psmelt %>% arrange(Class)
```
As an example: with this method the relative abundance of Deltaproteobacteria in sample A is 1.4% 

To check this, I went ahead and made a "wide" dataframe without taxglom to check in excel (i know i could do this more elegantly, but bear with me).
```
phy_bac %>%
              transform_sample_counts(function(x) {x/sum(x)} ) %>%
              psmelt %>% 
              select(Sample,Kingdom,Phylum,Class,Order,Family,Genus,OTU,Abundance) %>% 
              spread(Sample,Abundance)
```
And now comes the surprise. If I go into excel with this table, sort for "class", and sum up all relative abundances of Deltaproteobacteria in sample A, I am getting 0.6%!

Can somebody help me to find out what is happening here? I like using phyloseq since it has lots of functions that i use frequently, but I need to know what they are doing..

**Comment by cresil** [comment]
Default setting of tax_glom removes taxa with NA assignment. Try with
NArm=F.

**Comment by s-christel** [comment]
ok, this actually seems to work... but I dont understand why? How can i get a lower number when disabling a removal command?

**Comment by schuyler-smith** [comment]
You are interpreting relative abundance incorrectly. It is a measurement of what proportion of the total observations each OTU, or in your case Class, represents. It is (abundance of OTU of interest) / (abundance of all OTUS in your set). When NArm = true, it removes OTUs and their contributing abundances from the denominator, and since you are explicitly looking at the relative abundance of a particular classified OTU (with no NAs in it), your denominator stays the same. This will give you a higher (false) relative abundance.

So your number of reads is not lower, it is just a lower proportion of the total.

**Comment by s-christel** [comment]
I see. I didnt actually think those were completely removed, but masked. Thanks for making this clear. 
o7
