### ISSUE TITLE
Inconsistent vignette vs publication coefficient of variation setup.

### ISSUE THREAD

**Issue by grabear** [joey711/phyloseq#1043]
# Problem
I've been using the coefficient of variation used in the phyloseq preprocessing example:

```r
# Filter the taxa using a cutoff of 3.0 for the Coefficient of Variation
> gpsf = filter_taxa(gps, function(x) sd(x)/mean(x) > 3.0, TRUE)
```
By this example (if I'm understanding the filter_taxa function correctly) the function is filtering out all OTUs with a CoV less than 3 and keeping the OUTs that are greater than 3.  

Your publication (and statistics) suggest that you might be more interested in keeping OUTS less than 3 and removing those with a CoV greater than 3:
![image](https://user-images.githubusercontent.com/20953530/49312317-6a9b1980-f4a9-11e8-954d-2a6c798005b6.png)

Also seen here: https://journals.plos.org/plosone/article/figure?id=10.1371/journal.pone.0061217.g004

Unfortunately, I used this in ignorance for a little while until I realized what was going on.  I just wanted to make you guys aware of this, because other scientists might be doing analysis, using this vignette, and not realizing _exactly_ what they are filtering out at this step.

**Comment by grabear** [comment]
@sdhutchins

**Comment by joey711** [comment]
I'm afraid I don't see what the issue is. First, you're referring to a description of filtering that was done for the purpose of creating an example "look at these plots" figure. Second, these choices are always specific to a dataset and the goals of the analysis at hand. Third, for the purposes of plotting I did want to remove OTUs with low CV -- which the example does as stated.
