### ISSUE TITLE
Bar plot loss of classification

### ISSUE THREAD

**Issue by ArneClaeys** [joey711/phyloseq#1140]
I'm new to phyloseq and I am trying to make a bar plot from my count table.

This is my code for the part with the bar plot on phylum level:
###Phylum###
##Data preparation
#Loading metadata
metadata <- read.table("mapping_bacteria_bioptimal.txt", sep = "\t", header = TRUE)
rownames(metadata) <- ColTreat2
#Make the count table numeric
Bac <- data.frame(sapply(Bac, function(x) as.numeric(as.character(x))))
#Make tax into a matrix
taxA <- tax_table(as.matrix(Bac_tax))
#Build phyloseq class object
p_phylum_bioptimal <- phyloseq(otu_table(Bac, taxa_are_rows = TRUE), tax_table(taxA), 
                               sample_data(metadata))
#Filtering
p_phylum_bioptimal_r  <- transform_sample_counts(p_phylum_bioptimal, function(x) x / sum(x) )
p_phylum_bioptimal_rf <- filter_taxa(p_phylum_bioptimal_r, function(x) mean(x) > 1e-4, TRUE)
#Agglomerate taxa of the same type
p_phylum_bioptimal_h <- tax_glom(p_phylum_bioptimal_rf, "Phylum")
#Plot barplot
p_phylum <- plot_bar(p_phylum_bioptimal_h, fill = "Phylum")
p_phylum

As you can see I use the relative abundance in my bar plot, but I seem to be getting peaks at around 75%, but also ones at 25% and in between. The sum of my counts for each sample is approximately the same. I also checked for NAs, but the amount of counts classified as NA in Phylum compared to total counts is only around 0.01 - 0.05%, so that can't be it. I'm wondering how I'm losing so many.

**Comment by mikemc** [comment]
I think your question is, why your samples are adding up to much less than 100%. I suspect it is because you are filtering out all OTUs or ASVs that have a mean frequency of less than 1e-4. This will often be most of your OTUs or ASVs, since most only appear in a small subset of samples. You should instead consider filtering based on prevalence or minimum frequency or some combination, rather than mean frequency. For example, to keep all taxa that appear at 1e-4 in at least 5 samples:
```r
p_phylum_bioptimal_rf <- filter_taxa(p_phylum_bioptimal_r, function(x) sum(x > 1e-4) >= 5, TRUE)
```
Alternately, aggregate to the phylum level, and then filter out rare phyla.
