### ISSUE TITLE
plot_richness not working with custom vector x

### ISSUE THREAD

**Issue by AlexanderBartholomaeus** [joey711/phyloseq#1318]
I try to use `plot_richness` using a custom vector `x`. The manual say it should work with a vector of the same length than `nsamples(ps)` but it does not. Also a named vector with sample names does not help.

**Comment by ianartmor** [comment]
Reprex: 
`my_x <- sample_data(GlobalPatterns)$SampleType
plot_richness(GlobalPatterns, my_x)
`
Looks like the problem is that it generates the richness estimate df in "long" form so it has nsamples*measures numbers of rows, vs your variable which only has length of nsamples.

 It works fine if you choose only one measure:
`my_x <- sample_data(GlobalPatterns)$SampleType
plot_richness(GlobalPatterns, my_x, measure="Chao1")
`

In the meantime, I don't know if this helps you, but my workaround is to take the output of `estimate_richness` and `left_join` it to a data frame with my sample data that I keep outside of phyloseq for metadata summary plots. Then I just plot that with ggplot2. This has the added benefit of choosing what type of plot you want-- boxplot, scatterplot, etc.

**Comment by ianartmor** [comment]
Revisiting this: a very silly solution is to use `rep` to repeat your vector ones for each measure you want to use.

Example:
`my_x <- sample_data(GlobalPatterns)$SampleType`
`my_x_for_plotrich <- rep(my_x, 2)`
`plot_richness(GlobalPatterns, my_x_for_plotrich, measures=c("Chao1", "Shannon"))`
