### ISSUE TITLE
Merge the same taxonomies with different IDs

### ISSUE THREAD

**Issue by fpeti11** [joey711/phyloseq#1484]
Hello,

I have 20 samples, but all of them are in separated file with different IDs. I would like to merge all of these in one phyloseq object to make a taxonomic analysis. I was creating a phyloseq object for all the samples, and then I use merge_phyloseq, and then use tax_glom to merge the same taxons into one. Can you suggest me another method to solve this problem or is it a good method?

Thank you for your help
Have a nice day 
Peter

**Comment by ycl6** [comment]
Hi @fpeti11 

Are they 16S rRNA amplicon sequencing? 

Another way I can think of is to combine the sequences from different samples, make a unique set of sequences, then use dada2's [Assign taxonomy](https://benjjneb.github.io/dada2/tutorial_1_8.html#assign-taxonomy) strategy to get the taxnomy results from those. Manually curate the OUT/ASV counts of each unique sequence in your samples so that you have an OTU table, and you will have the required information to build a `phyloseq` object. 

However, I will suggest using the `dada2` workflow to process the whole dataset from the beginning.
