### ISSUE TITLE
Importing Silva taxonomy data

### ISSUE THREAD

**Issue by mdehollander** [joey711/phyloseq#162]
We are trying to import a BIOM file generated by Qiime with taxonomy data assigned against the Silva database with LCA Blast. The taxonomy format looks like this: {"id": "37", "metadata": {"taxonomy": ["Cellular organisms", "Bacteria", "Proteobacteria", "Betaproteobacteria", "Neisseriales", "Neisseriaceae", "Silvimonas"]}

The problem is that with the import_biom function the taxonomy is not recognized, because its optimized for Greengenes. We use the import_biom function with these arguments: parseFunction=parse_taxonomy_default . The taxonomy is now named like rank1, rank2 etc. but now we cannot access it with a string named Phylum or Kingdom. Is it possible to import a biom file with the taxonomy formatted as above? Or do we need to format the taxonomy with prefixes like "k__", and "f__" like RDP does?

**Comment by bedemickan** [comment]
This is helpful. I appreciate this - I am now happy.
Im going to have a beer.

**Comment by joey711** [comment]
Nice! I will uptick the value on my beer-tracker...

**Comment by coyk** [comment]
Thank you so much for answering questions about your code.  I really appreciate it.  I've been arguing with R for a little while now (and I am a very new user) to get it to rename the generic "Rank1" Rank2" etc to Kingdom, Phylum, Class, Order, Family, Genus and I haven't had luck yet.  My tax table is a mothur generated table ending in cons.taxonomy.  The taxonomic info is from the Silva v128 database.  The file is tab-delimited with OTus in 1st column, total in second column, and 3rd column a string of taxonomies and confidence values separated by semi-colons. 
 For example, Row 1:
'Otu000001\t2968324\tBacteria(100);Proteobacteria(100);Gammaproteobacteria(100);Methylococcales(100);Marine_Methylotrophic_Group_1(100);\n',
Row 22:
Otu000022\t200\tBacteria(100);Proteobacteria(100);Alphaproteobacteria(100);Rhizobiales(100);Methylobacteriaceae(100);Methylobacterium(100);\n',
 etc etc
The shallowest it goes is to genus, so 6 ranks.

This is the file I use, along with the mothur shared file, as input for import_mothur.  Is this the step at which I could change the rank names?  I know there is a parse_taxonomy_default argument.  I've tried 

>taxvec = c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus")
>parse_taxonomy_default (taxvec)
>Bathy_table <- import_mothur (mothur_shared_file = "Bathylist.shared", mothur_constaxonomy_file ="Bathytax.taxonomy", parse_taxonomy_default(taxvec), cutoff=NULL)

but then when I  ask for rank names
>rank_names(Bathy_table)
I get 
"Rank1" "Rank2" "Rank3" "Rank4" "Rank5" "Rank6"

I also tried 
parse_taxonomy_default(c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus"))
as the full argument for import_mothur, instead of creating taxvec before import_mothur.  No dice.

Any suggestions/corrections appreciated!

**Comment by haroldnunez** [comment]
Did you created a phyloseq object already? Or you are still trying to import into phyloseq?

**Comment by coyk** [comment]
At this point I have not.  Since import_mothur had the parse taxonomy argument, I assumed this is the step where I could get it to rename the ranks.  I'm assuming the merging of the OTU_table (created from import_mothur) with the sample_mapping creates the phyloseq object?

**Comment by haroldnunez** [comment]
You should try first with the make.biom command from mothur https://www.mothur.org/wiki/Make.biom

**Comment by joey711** [comment]
Woah slow down. If @coyk is at the stage of seeing the phyloseq-generated dummy columns "Rank1", "Rank2", ... then was already successful importing. All you have to do is update the column names of the taxonomy table to reflect what you want them to be. This is an answer that has been shared many times in the issues tracker.

Your fix would be this one-liner after the import:

```r
colnames(tax_table(physeq)) <- c("Kingdom", "Phylum", ...)
```

where `physeq` is your phyloseq object (e.g. `Bathy_table`), and `...` is the rest of the rank names you want to rename.

The `parse_taxonomy_` family of functions are there as modular support for specific formats, and as example functions, because one could write a different custom function with the same input/output and provide that to the `import_` function instead. An advanced move, but there for flexibility if you need it.

**Comment by grabear** [comment]
#854
