### ISSUE TITLE
Using non phyloseq functions on phyloseq-stored data

### ISSUE THREAD

**Issue by elipowel** [joey711/phyloseq#190]
Feature request: Adonnis or ANOSIM as well as indicator species analysis from VEGAN, tests for box plots

It would be great to have some more statistical packages easily accessible from within the suite

This is related to [an earlier Issue](https://github.com/joey711/phyloseq/issues/105) on a similar topic.

**Comment by RJ333** [comment]
I would like to add a short comment: 

If you are not using Joey's way of generating a data.frame `as(sample_data(physeq), "data.frame")`  but instead `as.data.frame(sample_data(physeq))`, this might not be sufficient.  I ran into issues using `adonis` in `vegan`:

> Error in terms.formula(formula, data = data) :
  'data' argument is of the wrong type

and it turned out that `data.frame` and `as.data.frame` do different things. You see by `str(as.data.frame(sample_data(physeq)))` that it still contains the extra phyloseq-class features, whereas  `str(data.frame(sample_data(physeq)))` does the job and you can use the output e.g. for `vegan`

(more info here: https://stackoverflow.com/questions/21574250/difference-between-as-data-framex-and-data-framex)

Bye

RJ
