### ISSUE TITLE
manual order x axis labels in plot_bar

### ISSUE THREAD

**Issue by elinekl** [joey711/phyloseq#240]
Is there a way I can select the order of the labels on the x axis in plot_bar?
Cheers!

**Comment by pavlo888** [comment]
Hi there, 

I have a problem re-arranging my data. 

I have re-arranged the factor levels with this command: 

`sample_data(phy1)$GH = factor(sample_data(phy1)$GH, levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"))`
Then when I use: 
`levels(sample_data(phy1)$GH)`
I obtain: 
```
> levels(sample_data(phy1)$GH)
 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"
```
So when I plot the data, I still have a problem with the way it is ordered (see attached image). 

Could you please help me solve this issue?

Alternatively, how could I annotate my data so that sample 10 does not come before sample 2?

Thanks in advance! 

Cheers, 
Pablo 
![alpha_shannon_GH](https://user-images.githubusercontent.com/45701394/82128193-8c7d7e80-97b9-11ea-80ce-93a95deb6a4a.png)
