### ISSUE TITLE
plot_heatmap abundance scale incomplete

### ISSUE THREAD

**Issue by kfontanez** [joey711/phyloseq#265]
Joey-

I've used plot_heatmap to plot the Top 20 most abundant pathways in my metagenomic data. However, the abundance scale is incomplete and only labeled at one location on the gradient. I'm not sure why. Please note that these are relative abundances calculated using your transform_sample_counts function.

> KEGG=phyloseq(COUNTS,ANNOT,L3_META)
> KEGG
> phyloseq-class experiment-level object
> otu_table()   OTU Table:         [ 4602 taxa and 7 samples ]
> sample_data() Sample Data:       [ 7 samples by 5 sample variables ]
> tax_table()   Taxonomy Table:    [ 4602 taxa by 1 taxonomic ranks ]
> 
> KEGG_rel=transform_sample_counts(KEGG,function(x)x/sum(x))
> otu_table(KEGG_rel)[1:5][1:5]
> OTU Table:          [5 taxa and 7 samples]
>                      taxa are rows
>      L3_150D    L3_150L    L3_500D    L3_300L    L3_300D    L3_500L    L3_200D
> 1 0.03427107 0.03847790 0.04692735 0.04104191 0.03920685 0.04397018 0.03473736
> 2 0.03211590 0.03420084 0.03776746 0.03548366 0.03318448 0.03812921 0.03280565
> 3 0.02603514 0.02890271 0.01684269 0.02953755 0.02441722 0.02268204 0.01812467
> 4 0.02417171 0.02360399 0.02758351 0.02415448 0.02488836 0.02689567 0.02378147
> 5 0.03185335 0.02096737 0.01971666 0.02219087 0.02714163 0.01969774 0.02770690
> 
> TOP20KEGGnames=names(sort(taxa_sums(KEGG_rel),TRUE)[1:20])
> TOP20KEGG=prune_taxa(TOP20KEGGnames,KEGG_rel)
> TOP20KEGG
> phyloseq-class experiment-level object
> otu_table()   OTU Table:         [ 20 taxa and 7 samples ]
> sample_data() Sample Data:       [ 7 samples by 5 sample variables ]
> tax_table()   Taxonomy Table:    [ 20 taxa by 1 taxonomic ranks ]

Here is my code to make the heatmap:

> plot_heatmap(TOP20KEGG,method="PCoA",distance="bray",taxa.label="Pathway",title="Top20 KEGG L3 pathways using bray dist,clustered with PCoA")
> ![screen shot 2013-11-14 at 10 16 48 am](https://f.cloud.github.com/assets/5814641/1541951/de2a0e18-4d3f-11e3-80f3-e92ff7044725.png)

As you can see, the Abundance only contains a single value. It would be helpful to have values at the top middle and bottom of the scale. Am I doing something wrong here?

One workaround I tried was to use scale_color_gradient to define my own top and bottom of the scale.

> f=plot_heatmap(TOP20KEGG,method="PCoA",distance="bray",taxa.label="Pathway",title="Top20 KEGG L3 pathways using bray dist,clustered with PCoA")
> f+scale_color_gradient(limits=c(0.005,0.05),expression(Abundance))

![screen shot 2013-11-14 at 10 41 20 am](https://f.cloud.github.com/assets/5814641/1542181/39466000-4d43-11e3-9294-3683c691a768.png)

I chose the limits based on looking at the top and bottom values in the TOP20KEGG object:

> otu_table(TOP20KEGG)[1:3]
> OTU Table:          [3 taxa and 7 samples]
>                      taxa are rows
>      L3_150D    L3_150L    L3_500D    L3_300L    L3_300D    L3_500L    L3_200D
> 1 0.03427107 0.03847790 0.04692735 0.04104191 0.03920685 0.04397018 0.03473736
> 2 0.03211590 0.03420084 0.03776746 0.03548366 0.03318448 0.03812921 0.03280565
> 3 0.02603514 0.02890271 0.01684269 0.02953755 0.02441722 0.02268204 0.01812467
> otu_table(TOP20KEGG)[18:20]
> OTU Table:          [3 taxa and 7 samples]
>                      taxa are rows
>        L3_150D     L3_150L     L3_500D     L3_300L     L3_300D     L3_500L
> 18 0.008861320 0.010227548 0.013232532 0.010383907 0.009914376 0.012227747
> 19 0.009550534 0.009912659 0.010698342 0.009779646 0.010016797 0.010974911
> 20 0.010777626 0.009460005 0.008390671 0.008518663 0.011901348 0.008773211
>        L3_200D
> 18 0.009319896
> 19 0.009467755
> 20 0.009396210

However, my main concern about this workaround is: 

Is the scale represented by scale_color_gradient the same default log_trans(4) scale used for the plot_heatmap function? Or do I need to define it manually somehow? 

Thank you,
Kristina

**Comment by jenlang** [comment]
I have a slightly similar problem. The legend scale has an obnoxious amount of digits (I'm also using relative abundance) and won't let me alter it. I've tried using trans = identity_trans() but that just gives me a black plot. I tried + scale_color_gradient(limits=c(0.003,16), expression(Abundance)) and that doesn't even give me a plot.

`plot_heatmap(pso_hm,"PCoA", "unifrac", weighted=FALSE, "Treatment", "Genus", sample.order = "Treatment", trans = log_trans(4), title = title) + theme(axis.text.x = element_text(size=7))`
![image](https://user-images.githubusercontent.com/10035756/28731157-a73998f2-7387-11e7-8220-ca2597bf5768.png)
If I try to change the legend with the following code I get this plot
`plot_heatmap(pso_hm,"PCoA", "unifrac", weighted=FALSE, "Treatment", "Genus", sample.order = "Treatment", trans = log_trans(4), title = title) + theme(axis.text.x = element_text(size=7)) + scale_fill_gradient(name = "Rel Abundance (%)", breaks = c(16, 1, 0.06, 0.00), labels = c("16", "1", "0.06", "0.00"))`
and error: Scale for 'fill' is already present. Adding another scale for 'fill', which will replace the
existing scale.

![image](https://user-images.githubusercontent.com/10035756/28731457-d968b154-7388-11e7-889b-5dbf5d2ffebe.png)

Why can't I modify this plot like a regular ggplot2 plot? Being able to organize the sample by ordination is fantastic but the plotting is too strict and not flexible enough. Even our database manager had tried to go in and alter the source code and he couldn't figure it out.   

Any help would be greatly appreciated because I've given up!

**Comment by tjarbour** [comment]
@joey711 I am also experiencing this too-many-digits issue, and would like to change to scientific notation. I _think_ this can be done easily with the `scales` package, but still haven't figured out how (what plot layer to modify). Thanks in advance for any help!

**Comment by SumTot** [comment]
Hello,
I have the same problem than before was showed. The scale only shows three values and not more. 
Does someone understand and could explain me how is the calculation made?
I have read that the function uses the log transformation with base 4. In my case, with this base (4) three numbers are represented in the scale: 4; 0.25 and 0.015
If for example I change the base 4 by 10, the represented numbers are : 10; 1; 0.1 and 0.01
Or if I change it by 2, the scale will be: 8; 0.5 and 0.03125

Someone could explain me how is it working? 
Maybe if I understand the basis, I could change my scale...
Thanks a lot in advance!!
