### ISSUE TITLE
phyloseq wrapper for edgeR DGEList

### ISSUE THREAD

**Issue by laurenms** [joey711/phyloseq#280]
Hi Joey, 
I'm curious if you are going to add a wrapper to convert phyloseq objects into the DGEList for edgeR (similar to what you did for DESeq in phyloseq_to_DESeq)?
Thanks, 
Lauren

**Comment by moyegunle** [comment]
Hi Joey ( or anyone who can help) , this might be a silly question and not appropriate here (sorry)  but wondering if you had a subgroup in addition to DIAGNOSIS in the example above. 
For example if you wanted to examine if the log2 fold changes differed across another variable say LOCATION (if there was a variable like that). Like effect modification or interaction...would it be DIAGNOSIS*LOCATION?
Another example that might be clearer would be paired samples- if the variable denoting the paired samples was TIME and the variable of interest in still DIAGNOSIS- and we would like to see if the log2fold changes between paired samples differed based on DIAGNOSIS, would we write 
"dge = phyloseq_to_edgeR(kosticB, group = "TIME*DIAGNOSIS")? thanks in advance

**Comment by moyegunle** [comment]
Sorry I had a star(*, a product sign) before the fonts changed to italics

**Comment by TseWue** [comment]
Hi
I also used a subgroup because not all my samples were paired. But I simply created a new phyloseq object. Anyhow, when I wanted to do the paired tests (as described in https://joey711.github.io/phyloseq-extensions/edgeR.html) I get stuck at the line which was also posted above by @laurenms 

`x = as(otu_table(pairs), "matrix") + 1L
taxonomy = data.frame(as(tax_table(pairs), "matrix"))

# Now turn into a DGEList
x = DGEList(counts=x, group=groups,genes=taxonomy, remove.zeros=TRUE)`

The line exited with the error message
_Error in DGEList(counts = x, group = groups, genes = taxonomy, remove.zeros = TRUE) : 
  Length of 'group' must equal number of columns in 'counts'_

Did I forget to do something to the phyloseq object beforehand? As it seems to me, the information about the groups is being searched for in x but it actually is only found in taxonomy (as a variable of it). Is that right?
Thanks for your help!
