### ISSUE TITLE
Using transformed count data from DEseq2

### ISSUE THREAD

**Issue by kfontanez** [joey711/phyloseq#283]
Joey-

In your "Waste not, want not" paper you suggest that researchers interested in PCA and clustering ought to consider using variance stabilized data rather than proportions or rarified data.

DEseq2 allows output of the transformed count matrix derived from the variancestabilizingTransformation function using `getVarianceStabilizedData(object)`. Do you have a convenient way to change that back into a phyloseq data object so that all of the available graphical and analytical functions of phyloseq can be used (barplots, heatmaps, etc)?

Thanks,
Kristina

**Comment by barbara1** [comment]
Hi Joey,

I wanted to do some further analyses on a phyloseq object I created in
December, but now I get an error message.

Error in phyloseq(DT) :
  Problem with OTU/taxa indices among those you provided.
Check using intersect() and taxa_names()

I updated my phyloseq package in January and I thought this might be the
problem, so I recreated the phyloseq object from the original files
(sample, otu_table and taxa_table) and I continue to get the error message.
I had no issues in December with the set up.

I checked that the row_names matched between the otu_table and taxa_table
and assigned the row_names from the taxa_table to the otu_table, but this
did not change anything.

rownames(taxa_table)=taxa_names(otu_table)

I did not see any information on how to use the intersect() to check the
issue further. If you have any suggestions on where I should be looking for
the issue in my files or any known issues with updating the package, it
would be really helpful!

Thanks in advance,

Barbara


Barbara D Bahnmann MSc | Marie Curie PhD Fellow
*Trainbiodiverse* ITN | Soil Microbial Ecology
http://www.trainbiodiverse.com/people/barbara-bahnmann
barbara.bahnmann@ualberta.ca | +420 607 398 692

**Comment by joey711** [comment]
Hi Barbara,

Sorry you are having this issue. This sounds like a completely unrelated issue to the now-closed issue to which this comment has been added. 

Please re-post as a new issue. Copy and paste should be fine.

Also, please note that your issue post is incomplete, as you have not indicated which version of phyloseq you were using before and after, and you did not post the code that you used to create the "new" phyloseq object from the original files. This latter case is more important, because it should have fixed your issue right away. Please indicate what the file formats are as well when you provide that code.

Thanks in advance for your updated comment, and your continued interest in phyloseq!

joey

**Comment by JamieMcDevittIrwin** [comment]
Hello, 

After going through this post and trying to save my variance stabilized counts in my original otu table, I am having problems with the conversion from a dseq object (after variance stabilizing) back to a phyloseq object. I am using phyloseq version 1.16.2. 

Below is my code:

# load the data with low read samples pruned out
load("data/secondmito/lowreads_pruned/otutable_top10removed_coral_866_may.Rdata") #otu_tablef_no10_coralf_sm_866f_mayf
ls()

print(otu_tablef_no10_coralf_sm_866f_mayf) # 39 samples, 6037 taxa
class(otu_tablef_no10_coralf_sm_866f_mayf) # "phyloseq"

# Try with updated gm_means, because my data has such a high prevalence of sparsely sampled OTUS
test = phyloseq_to_deseq2(otu_tablef_no10_coralf_sm_866f_mayf, ~ 1)
# calculate geometric means prior to estimate size factors (zero tolerant version of geomeans)
gm_mean = function(x, na.rm=TRUE){
  exp(sum(log(x[x > 0]), na.rm=na.rm) / length(x))
}
geoMeans = apply(counts(test), 1, gm_mean)
diagdds = estimateSizeFactors(test, geoMeans = geoMeans)
diagdds = estimateDispersions(diagdds)
diagdds.vst <- varianceStabilizingTransformation(diagdds)
dim(diagdds.vst) # 6037, 39 (same as original OTU table)
class(diagdds.vst)

# save the untransformed data as a separate variable so you can go back to it
otu_tablef_no10_coralf_sm_866f_mayf0 <-  otu_tablef_no10_coralf_sm_866f_mayf

# replace the counts with variance stabilized counts 
otu_table(otu_tablef_no10_coralf_sm_866f_mayf0) <- otu_table(diagdds.vst, taxa_are_rows=TRUE)


Error Outputed: 
> otu_table(otu_tablef_no10_coralf_sm_866f_mayf0) <- otu_table(diagdds.vst, t
<_coralf_sm_866f_mayf0) <- otu_table(diagdds.vst, ta                        xa_are_rows=TRUE)
**Error in access(object, "otu_table", errorIfNULL) :
  otu_table slot is empty.**

Thank you very much for your help! All of these issues and vignettes on phyloseq are incredibly helpful.

Jamie

**Comment by LCzaplickiD** [comment]
I'm having the same problem:
#DESeq2 conversion
fungi.DESeq=phyloseq_to_deseq2(fprunedpsF1spooled, ~ Rep) 
#DESeq2 Variance Stabilization
fungi.DESeq = estimateSizeFactors(fungi.DESeq, geoMeans = geoMeansFs)
fungi.DESeq = estimateDispersions(fungi.DESeq, fitType="local")
fungi.vst<-varianceStabilizingTransformation(fungi.DESeq,blind=FALSE,fitType = "local")
dim(fungi.vst)
#Save the untransformed data as separate variable
vst.fungi.phyloseq = fprunedpsF1spooled
#Add the variance stabilized otu numbers into the dataset
otu_table(vst.fungi.phyloseq)<-otu_table(fungi.vst, taxa_are_rows = TRUE)

error:
otu_table(vst.fungi.phyloseq)<-otu_table(fungi.vst, taxa_are_rows = TRUE)
Error in access(object, "otu_table", errorIfNULL) : 
  otu_table slot is empty.

Thank you again for all these helpful threads and the vignettes!

**Comment by SumTot** [comment]
Hello!
I have some problems with the colors of my heatmap (https://github.com/joey711/phyloseq/issues/1305)
Can I use my own palette in the plot_heatmap? If I use for example, "high=myownpalette", I get colors that I don´t like. For example black colors for values really small. I would like to have dark red but not black in these values.
![heatmap wit High argument](https://user-images.githubusercontent.com/57224842/77629294-94533c00-6f49-11ea-83ae-0b15839cd16a.png)

**Comment by tierrasoledad** [comment]
I had the same problem when I tried this code:
"error:
otu_table(vst.fungi.phyloseq)<-otu_table(fungi.vst, taxa_are_rows = TRUE)
Error in access(object, "otu_table", errorIfNULL) :
otu_table slot is empty."

So I tried it this way... 
So I still ran the variance Stabilizing Tranformation on fungi.DESeq object.
fungi.vst<-varianceStabilizingTransformation(fungi.DESeq,blind=FALSE,fitType = "local")

But when I try to get the matrix use the getVarianceStabilizedData func and use that as my otu table it seems to work.
fungi.vst.1<- getVarianceStabilizedData(fungi.DESeq)
otu_table(vst.fungi.phyloseq)<-otu_table(fungi.vst.1, taxa_are_rows = TRUE)
