### ISSUE TITLE
How does estimate_richness deal with uneven sequencing depth?

### ISSUE THREAD

**Issue by laurenms** [joey711/phyloseq#287]
Hi, I apologize in advance if this is answered somewhere in the documentation that I haven't been able to find yet. How does estimate_richness deal with uneven sequencing depth? I was under the impression the function wanted raw counts as the input but should the data be transformed already (not necessarily rarefied but something like that)?
Thanks!
lauren

**Comment by sfujio** [comment]
Hi Joey, 
I have used plot_richness and estimate_richness with boxplot function to generate plots, and they have very large variance. I have seen that in many tutorials and in this issue, it is said not to trim or standardize the library size but also have come across with papers such as DOI: 10.1111/j.1462-2920.2011.02550.x and DOI: 10.1002/ece3.508  were it´s discussed that different library size would affect to the estimation of richness and diversity and that the sample´s library size should be standardize.  Could you specify how the library size information is incorporated into the estimation? so I can justify why I used the raw data when I present my results. 

Thank you

PS: I have seen the word normalize used, after using the DESeq transformation of the data, but strictly speaking it should be standardize, because normalizing is transforming the data so it has a normal distribution, which I would think is not what happens when that command is used.. or is that what happens?

**Comment by sargdavid** [comment]
Hi Paul,

I know this is a closed issue so I can open a new one if you prefer but I still have same question that @laurenms had - how do you take the sequencing depth into account. I am looking at your function and here is what it looks like for, e.g. Shannon's index:

    _if ("Shannon" %in% measures) {
        outlist <- c(outlist, list(shannon = diversity(OTU, index = "shannon")))
    }_

i.e you are using **_vegan::diversity_**, correct? If so, that function does not seem to have any adjustment for the sequencing depth as it simply calculates **_-p*log(p)_**. 

As @laurenms noted in the very beginning, samples with larger number of reads will have a better chance of detecting more OTUs hence will end up with higher Shannon index.  Am I missing something?

Thank you.

**Comment by samd1993** [comment]
I would be worried about this too since my data is hinging on the fact that I get a significant result for richness but the seq. depth isnt even...does the log help mitigate seq. depth issues since that in itself is a transformation?

**Comment by RomGallet** [comment]
Dear Joey, 
I have the same question regarding the relationship between sequencing depth and Diversity index. I'm working on a  Gut microbiome dataset, in which I have thousands of samples. Of course, their sequencing depth differ, but the rarefaction curves seem to indicate that I reach the plateau is all cases, and thus, that I should not have any issues in detecting diversity. However, when I plot "number of reads" vs "Shannon index" I find a significant correlation between these factors. 
I'm not sure how I can solve this problem. 
Do you have any idea? 
Thank you in advance.
