### ISSUE TITLE
ordering the stacks in plot_bar

### ISSUE THREAD

**Issue by laurenms** [joey711/phyloseq#291]
Is there a way to change the stacking order in a plot_bar graph (not the legend order but the stack order)? As it is now, each stack is ordered with the factor composing the largest abundance on the bottom of the stack. I am plotting relative abundance against time and by Genus. 
p=plot_bar(most_abundant10, "Time", fill = "Genus", facet_grid = Treatment ~ .)
p + ylab("Relative Abundance (%)")
p + xlab("time since start of experiment")

I would like to change it so that the stacks are ordered the same way for each in each stack so it is easy to look across the plot and see increases or decreases in abundance without having to search for the color for a particular genera which may have moved from the bottom of the stack at one time point to the top of the stack at another time point.

I looked through the ggplot2 documentation and thought I might be able to add something like p + geom_bar(aes(order = -as.numeric("Genus"))) but this didn't work.

Any ideas?
Thanks!
lauren

**Comment by dlebron10** [comment]
Is there a way to re-size the legend stack in the plot_bar?
I guess I have too many species and the legend is too long to fit the frame of the window. 
I would like to make it smaller.

**Comment by CarlyRae** [comment]
I'm going to add a note here that I needed to do this to get my stacks in order

#### I had a merged phyloseq object, merging by elevation
ele_m <- merge_samples(ele, "Elevation_100m")

#### transformed to % relative abundance
ele_m = transform_sample_counts(ele_m, function(x) 100 * x/sum(x))

#### used psmelt
physeqdf <- psmelt(ele_m)

#### Forced the levels, following code above
temp <- c("Brucellaceae", "Comamonadaceae",  'Sphingobacteriaceae', 'Sanguibacteraceae', 'Xanthomonadaceae', 'Streptococcaceae', 'Nocardiaceae', 'Hyphomicrobiaceae', 'Planococcaceae', 'Microbacteriaceae', 'Micrococcaceae')

physeqdf$Family <- factor(physeqdf$Family, levels = c(temp))

#### This did not work
ggplot(physeqdf, aes(x=Sample, y=Abundance, fill=Family, order =as.factor(Family))) + geom_bar(stat = "identity", color = "black")

![image](https://cloud.githubusercontent.com/assets/3433598/13818578/c4ab2b48-eb6c-11e5-84f3-f706c297dcc4.png)


### This worked for me
ggplot(physeqdf[order(physeqdf$Family),], aes(x=Sample, y=Abundance, fill=Family, )) + geom_bar(stat = "identity", color = "black")

![image](https://cloud.githubusercontent.com/assets/3433598/13818585/cea7e140-eb6c-11e5-9a65-dcdc18b796a6.png)

Still, trying to figure out if there is any way to fix the gray stack. I suppose it you can't see the stack, you can't see the stack and it will be gray....

Thought I would share in case anyone else was having issues not getting the code above to work for them.

**Comment by ElinVidevall** [comment]
I've been trying to figure out how to plot the bar figures with black outline around the boxes, i.e. separating one family from another family. Exactly like the figure above. However, I have so many OTUs so the entire bars get very black with all the horizontal lines. I don't want the OTU lines, but I do want the black color separating the families. Any suggestion on what to do? Can I do it directly in ggplot or do I need to summarize the data somehow?

**Comment by CarlyRae** [comment]
Take a look at this post https://github.com/joey711/phyloseq/issues/468

It sounds like you should merge_taxa by family so you remove those OTU lines. 

In the figure above I also dramatically reduced my dataset to only include OTUs that showed a significant trend with elevation (x-axis). So, in this image I still have the bars separating distinct OTUs, but I only have a few OTUs that are in the same family so the lines aren't too much. I followed the restroom biogeography tutorial to select only OTUs I was interested in by editting this code to my needs:

top19otus = names(sort(taxa_sums(restroomR), TRUE)[1:19])
taxtab19 = cbind(tax_table(restroomR), family19 = NA)
taxtab19[top19otus, "family19"] <- as(tax_table(restroomR)[top19otus, "Family"], 
    "character")

Instead of top19otus, I specified OTUs that were significant using metagenomeSeq

OTUs_differ <- c("OTU_2", "OTU_3", "OTU_4", "OTU_5","OTU_61","OTU_6","OTU_10","OTU_165", 'OTU_16', 'OTU_19','OTU_26','OTU_367','OTU_382','OTU_40','OTU_41','OTU_50','OTU_93')

taxtab_select <- cbind(tax_table(ele), family_differ = NA)

taxtab_select[OTUs_differ, "family_differ"] <- as(tax_table(ele)[OTUs_differ, "Family"], "character")

#### made my numeric elevation variable a factor
sample_data(ele)$Elevation_100m <- factor(sample_data(ele)$Elevation_100m, levels = c("700", "800", "900", "1000"))
levels(sample_data(ele)$Elevation_100m)

#### then merge_sample as my beginning lines above to merge by the elevation

ele_m <- merge_samples(ele, "Elevation_100m")

**Comment by ElinVidevall** [comment]
Thank you, CarlyRae! It works perfectly! Thank you so much, it's very appreciated.

**Comment by Gian77** [comment]
Hi guys,
I am trying to plot a barplot with plot_bar function but I am unable to remove the black border to my bars, is there something I need to do with geom_bar()? Can you please give the code for that?

I mean like this one of the post above (figure attached)

![cd95790e-0cf5-11e4-9b67-d2573269f361](https://cloud.githubusercontent.com/assets/13815699/15194241/f6ad2bd8-178f-11e6-8ffe-f4d75e13f671.png)

What kind of palette did you use here?
Thank you very much,
G.

**Comment by Gian77** [comment]
Hey Michelle, will you be at the the meeting in AA Monday and Tuesday?
http://microbe.med.umich.edu/about/michigan-meeting-2016
Guys, if you are around I think it worth to go, it's free by the way. I will be there ;)
G.

**Comment by Mikeyj** [comment]
Hi @Gian77 for the colour palette it's a custom one. I had a project where we needed a large discriminating palette.  I started with this:

`custom_col42 = c("#781156","#A51876","#D21E96","#E43FAD","#EA6CC0","#F098D3","#114578","#185EA5","#1E78D2","#3F91E4","#6CABEA","#98C4F0","#117878","#18A5A5","#3FE4E4","#6CEAEA","#98F0F0", "#117845","#18A55E","#1ED278","#3FE491","#6CEAAB","#98F0C4","#787811","#A5A518","#D2D21E","#E4E43F","#EAEA6C","#F0F098","#F7F7C5","#784511","#A55E18","#D2781E","#E4913F","#EAAB6C","#F0C498","#781122","#A5182F","#D21E2C","#E43F5B","#EA6C81","#F098A7")`

I'm deuteranomalous and we're lucky to have another protanomolous researcher so we whittled it down to a palette that wasn't too bad for our wonky vision and still had a large number of different colours:

`custom_final28 = c("#771155", "#AA4488", "#EA6CC0", "#CC99BB", "#114477", "#4477AA","#1E78D2", "#77AADD", "#117777", "#44AAAA", "#3FE4E4", "#77CCCC", "#117744","#44AA77", "#1ED278", "#88CCAA", "#771122", "#AA4455", "#D21E2C","#DD7788","#777711", "#AAAA44", "#D2D21E", "#DDDD77","#774411", "#AA7744", "#D2781E", "#DDAA77")`

Also 

`custom_col21 = c("#771155","#AA4488", "#CC99BB", "#114477", "#4477AA", "#77AADD", "#117777", "#44AAAA", "#77CCCC", "#117744", "#44AA77", "#88CCAA", "#777711", "#AAAA44", "#DDDD77", "#774411", "#AA7744", "#DDAA77", "#771122", "#AA4455", "#DD7788")`

For removing the black borders round the edge, ggplot2 has updated several times since I put that code together (and I remember deprecation warnings at the time when I was doing it too) and my code is no longer functional - sorry. I'm pretty sure it's now controllable, but not sure how.

**Comment by michberr** [comment]
@Gian77 I will be! I'm giving a poster/lightning talk. I look forward to seeing you there and i hope others can make it too!

**Comment by Gian77** [comment]
Thanks Mykeyj,

they looks pretty cool palette! Thanks for sharing ;)

Here below was what I have (with a much brighter palette than yours)... I think is not possible to remove the black bars using this function though, maybe I need to use ggplot() instead...

### code starts here ###
source("plot_ordered_bar.R")

fungi_genus = tax_glom(biom_ITS, "Genus")
fungi_genus
tax_table(fungi_genus)
otu_table(fungi_genus)
ITS_genus = merge_samples(fungi_genus, "Description")
sample_data(ITS_genus)$Description <- levels(sample_data(fungi_genus)$Description)
ITS_genus
tax_table(ITS_genus)
ITS_genus = transform_sample_counts(ITS_genus, function(x) 100 * x/sum(x))
top100ITS <- names(sort(taxa_sums(ITS_genus), TRUE)[1:20]) 
top100ITS
fungi_top100 <- prune_taxa(top100ITS, ITS_genus)
fungi_top100
otu_table(fungi_top100)
tax_table(fungi_top100)

write.csv(tax_table(fungi_top100) , file = "tax_tab_fungitop20.csv") #correct the tax_table
tax_tab_fungitop20 <- read.csv("tax_tab_fungitop20.csv", header=T, row.names =1)
tax_tab_fungitop20 
tax_table(fungi_top100) <- tax_table(as.matrix(tax_tab_fungitop20))
fungi_top100
tax_table(fungi_top100)

sample_data(fungi_top100)
sum(sample_sums(fungi_top100)/24)

p1 <- plot_ordered_bar(fungi_top100, x = "Description", fill="Genus", leg_size = 0.4, title="Fungi Barplots")
p1 + scale_fill_manual(values=palette20) + ylim(0, 100) #+ coord_flip() #+ theme_bw()
### code end here ###

[plot.pdf](https://github.com/joey711/phyloseq/files/263767/plot.pdf)

**Comment by Gian77** [comment]
@michberr That is very good, my boss will have the talk, I will take it easier and just bring a poster. I am sure will be a great meeting. I love to interact with people do similar stuff.. I am more a "fungi guy" than a bacterial one, but I do bacteria a lot too. I will be looking for your poster then ;)

**Comment by joey711** [comment]
I love all the helpful discussions about color palettes. Really useful data viz principles in general.

I do want to make sure that these (now several) issue threads on stacked bars with phyloseq note that my recommendation for most of these situations is to take advantage of the easy faceting in ggplot2.

See the following more recent post

# [Issue 442](https://github.com/joey711/phyloseq/issues/442)

especially my post with the large font header **"Faceting beats stacking pretty much all the time"** and some reproducible examples to demonstrate/compare.

To summarize, there are several reasons to avoid stacked bar plots in all but very, very simple circumstances (which precludes most microbiome data). They include

- (1) **Moving Origin** - Every entry in one stack has a different origin in the other stacks, making it difficult to for the human eye to do anything except fuzzy (that is, less quantitative) comparisons.
- (2) **Limited Available Classes** - There is a low limit with which the human eye distinguishes similar color shades. I like the custom palettes, but you'll notice in practice these are dangerous, because after ~10 palettes it becomes very difficult for anyone to confidently distinguish the classes. 
- (3) **Comprehension Time** - Studies show that comprehension time is very important for how broadly and completely a population of readers will understand your quantitative graphic. These also show that for the same reason, a complicated color-legend is much less effective than a faceted organization in which the numeric values being compared are confined to the same panels - and also has the advantage that the panels can be clearly labelled with the corresponding identities of what they represent.

To summarize, with faceted separation of classes in a bar graphic,

- the eye only needs to go to one place on the graphic (instead of back and forth from legend to entries)
- each panel has a single vertical-scale origin (instead of a whole bunch of shifted origins in vertical space)
- there is no limit to the number of classes that can be represented, you'll just make a taller or wider graphical object.
- scales in each panel can have different limits, useful for when the data has a large dynamic range

For the point about large number of classes, I love using the `ggsave` function and specifying the width and height to values that might be much to large for a printed page, but easily explorable on the computer and contributed as a supplemental figure.

**Comment by Gian77** [comment]
Thank you @joey711 that is a good post... 
I've forgot to add the palette if someone would play with the same colours I've used, here you go...

palette20 <-c("#000066","#0000ff","#0066ff","#00ffff","#669966","#003300","#006600","#009900","#00ff00","#C0FF3E","#cccccc","#330033","#6600ff","#9900ff","#9999ff","#ffccff","#ff0000","#FF8000","#ff6600","#996600","#ffff00")

**Comment by slvrshot** [comment]
This seems more trouble than its worth. I can just as easily create ordered stack bar charts in excel, phinch, or even qiime itself. I agree with @joey711 that faceting is better but I am not a fan of what it seems to do to the scales. I have 90,000 taxa which I'ved filtered and pruned to 4000, and whenever I facet the scales for abundance give values from 3 to 9. I can clearly see the trends in the data but the scales are essentially meaningless and uninformative.

**Comment by joey711** [comment]
1. Stacked bars are always "more trouble than they're worth" because they're not worth very much, from the perspective of communicating quantitative information faithfully and efficiently.
2. Scales, controlling scales, defining scales, are all things ggplot2 does very well, and easily, if you know how. The `scale_` and `coord_` family of functions are where you should look. The documentation is pretty extensive, and there are lots of examples online. As for faceting, you have the option in ggplot2 to enforce that the scales are all the same, or adjust to data within the panel. This is the `"scales"` argument, one of the standard optional arguments to both `facet_wrap` and `facet_grid`.

**Comment by slvrshot** [comment]
@joey711 

Would you be able to provide an example? My code currently is this: 

p = plot_bar(ent10,"Phylum", fill="Phylum", facet_grid=Gut_Location~Description) #best plots
p + geom_bar(aes(color=Phylum, fill=Phylum), stat="identity", position="stack") 

Also is there anyway to get rid of the "p_" in p_Actinobacteria in my legends?

I used greengenes if that helps any.

**Comment by Gian77** [comment]
@slvrshot 

I usually do like this when needed

tax_table(physeqobject)[, "Phylum"] <- gsub("p__", "", tax_table(physeqobject)[, "Phylum"])
tax_table(physeqobject)[, "Family"] <- gsub("f__", "", tax_table(physeqobject)[, "Family"])
...

90k OTUs sounds quite a lot, are they from the same experiment/run?

G.

**Comment by slvrshot** [comment]
Thanks tremendously @gian77.

Also in my earlier post I realized my counts were already relative abundances. There was no need to transform them. My y scale now looks much more consistent and realistic.

**Comment by slvrshot** [comment]
@Gian77 

I ran your script on my phyloseq object testdata to an error...
> tax_table(testdata)[, "Phylum"] <- gsub("p__", "", tax_table(testdata)[, "Phylum"])
Error in as(x, "matrix")[i, j, drop = FALSE] : subscript out of bounds

Any ideas here?

**Comment by joey711** [comment]
Replace `"Phylum"` in the example script with the relevant taxonomic rank name in your data. Whatever you put in its place needs to be among the rank names returned by `rank_names()` function

```r
rank_names(testdata)
```

That error suggests that `testdata` does not have a `"Phylum"` rank, or it is spelled differently. Case sensitive, as is most things in R.

**Comment by slvrshot** [comment]
@joey711 You were right. I forgot to change the rank_names. Thanks!

**Comment by Gian77** [comment]
@slvrshot as @joey711 stated you need to change column names before, easy fix though, run:

colnames(tax_table(physeqobject)) = c(k = "Kingdom", p = "Phylum", c = "Class", o = "Order", f = "Family", g = "Genus", s = "Species")
G.
