### ISSUE TITLE
vegan::capscale ordination in phyloseq 

### ISSUE THREAD

**Issue by iLivius** [joey711/phyloseq#312]
Dear Dr. McMurdie,

I’m currently into microbial community analysis and an eager user of your package. Big fan! 
We just got a paper accepted in PLOS ONE (about endophyte bugs in grapevines after several treatments, classic microbial ecology study, 16S rRNA pyroseqs) but still one reviewer made mincemeat out of me since I used a CCA for constraining variables. I would like to use then a Constrained Analysis of Principal Coordinates (CAP), since I’ve already used its PCoA counterpart as an unconstrained approach early in the analysis. 

I’m almost sure that the vegan::capscale (http://cc.oulu.fi/~jarioksa/softhelp/vegan/html/capscale.html) is not wrapped into phyloseq. Can you please suggest me how should I use that function as an ordination in phyloseq?   

Thank you very much in advance

Cheers
Livio

**Comment by hmamine** [comment]
Hello, 
Thank you for these implimentation, really useful. 
However, I have found some diffirence between 
ordcap = ordinate(physeq_object, "CAP", "bray", ~design1+design2) with 
D.cap<-capscale(formula = otumat ~ design1 + design2 , data = sample_tab, dist="bray")
An other issue, ordcap has something wrong in the structure because anova(ordcap, by="axis") do not work where the anova(D.cap, by="axis") works perfectly. 
Thank you again for all you help.
Amine
