### ISSUE TITLE
Using subset_samples with variable in expression

### ISSUE THREAD

**Issue by audy** [joey711/phyloseq#335]
I'm trying to use `subset_samples` using a variable in the expression.

I usually follow [this solution](http://stackoverflow.com/questions/1743698/r-eval-expression) but for some reason it doesn't work with `subset_samples`.

``` S
f1 <- parse(text=paste('age', '>=', min_age))
ss <- subset_samples(phy, eval(f1))

# error in eval(expr, envir, enclos) : object 'f1' not found
```

This works for `subset_taxa`:

``` S
# create a formula to select taxa that are in `top_phy`
form <- parse(text=paste(options$rank, '%in%', 'names(top_phy)'))

# find out who the `top_phy` are
top_phy <- sort(tapply(taxa_sums(glom), tax_table(glom)[,options$rank], sum), decreasing=T)[1:options$top]

glom.top <- subset_taxa(glom, eval(form))
```

**Comment by ondrejcinek** [comment]
Dear Joey,

I am afraid the problem is more complex, and that scoping really does not work in certain instances:
In the function below, the 'country' variable is located in a for cycle within a function, and the subset_samples really returns "object 'country' not found. In contrast, a text constant passes without problems and the set gets subsetted.

Might you please consider trying the function call from within a cycle / function, and verifying whether the subset_samples code might be amended?

Thank you very much,
Ondrej

some_funtion <- function(reduced_dataset) {
	...
	...
	countries <- c("Nigeria", "Sudan", "Azerbaijan", "Jordan")
	for (country in countries){
			cat("Testing in ", country)
			
			dataset_country <- subset_samples(reduced_dataset, str_country == country)
			...
			...
}

**Comment by teyden** [comment]
I have the same issue that @ondrejcinek has outlined, whereby the actual value of the variable name is not interpreted and treated as a string literal. I'm using it a bit differently, but the scoping issue is the same: `subset_samples(phyloseq_obj, !is.na(var_name))`

Does anyone have a solution for this?

**Comment by Gerlex89** [comment]
Hi everyone.

I'm doing bar_plot to my phyloseq object and after applying several ggplot options like to show the abundances on the tip of each bar, I cannot find the way to **remove the 0 abundances from the plot**.

My issue is just like here: https://stackoverflow.com/questions/63159218/ggplot-and-the-geom-text-label

I have 120 samples in total. From these in my test plot only 5 have counts that come from `otu_table()`, but also I don't know which variables is using `bar_plot()` if "Abundance" is the y-axis and it isn't included in my original data.

Like indicated in the link above, the solution would be something like:

`geom_text(data = subset(physeq, MYSTERIOUS_VARIABLE != 0), aes(label = Abundance))`

possibly with subset_samples() instead of subset() but I cannot figure out that until now as the phyloseq object cannot be just used directly as a data frame.

The plot works by using only `geom_text(aes(label = Abundance)`, however is still visually incomplete by that detail.

![23 05 2021_15 24 55_REC](https://user-images.githubusercontent.com/57483526/119262314-146f4300-bbdb-11eb-97bd-887e1fca7053.png)

**Comment by mikemc** [comment]
@Gerlex89 We need to see the full code that you used to make your plot to effectively help you. But perhaps this tip will help - you are right that the `data` argument of `geom_text()` needs a data frame. What the `plot_bar()` function does under the hood is call `psmelt()` to create a data frame, and then supplies that data frame as the data frame to `ggplot()`. Generally, there is very little reason to use `plot_bar()` if you want any customization; you are better off getting this data frame e.g. `df = psmelt(physeq)` and using ggplot directly, so that everything is more transparent. But if you want to use `plot_bar()`, you can try this ggplot trick using purrr-style anonymous functions which lets you set the data arg for a layer to be a subset of the ggplot object (which in this case is the output of `psmelt(physeq)`). See the [documentation for `geom_text()`](https://ggplot2.tidyverse.org/reference/geom_text.html) for more info.
```r
plot_bar(physeq) +
  geom_text(data = ~subset(.x, MYSTERIOUS_VARIABLE != 0))
```

**Comment by Gerlex89** [comment]
Thank you for the quick reply!

`psmelt()` was the answer to this and other questions I could have, and now the plot is tidy. So many functions I constantly forget and so many things I'm learning on the go about both R and Phyloseq.

My code is just the customization of `plot_bar()` and by what I have seen it would be a longer way to get the same result only with ggplot2 rather than using `plot_bar()`, but I'm probably wrong.

```
p = plot_bar(plot.subset.firmi, fill = "Species")
p$data$Sample = factor(p$data$Sample, levels = desired.order)

p + theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 20)) +
    theme(text = element_text(size = 35)) +
    scale_y_continuous(breaks = pretty_breaks(n = 10)) +
    geom_text(data = ~subset(psmelt(plot.subset.firmi), Abundance !=0), aes(label = Abundance), position = position_nudge(y = 4.5), size = 8)
```
`desired.order` comes as a solution you gave in [#1075 ](url) to give the correct order to the samples.

The reason for only 5 samples with counts is because I created a cleaned object dropping the uncultured and other taxa without assignation at the genus level only for Firmicutes, then it reduced a lot the species identified, in my previous plot to only 2.

Thanks again.

**Comment by flashton2003** [comment]
This issue just caught me out as well. Had to do some serious gymnastics to get the prune option to work as well.

```groups_for_comparison <- c("group1", "group2")
var_values <- sample_data(phyloseq_obj)
var_bool <- var_values$Group %in% groups_for_comparison
pseq_control_vs_acute <- prune_samples(var_bool, phyloseq_obj)```

Would be much better if subset could just recognise variables that are in scope.
