### ISSUE TITLE
merge_samples into groups with varying number of samples

### ISSUE THREAD

**Issue by StefPN** [joey711/phyloseq#356]
Hi,
For several plotting functions I would like to merge my samples into my three clinical groups. Each sample is adjusted to even sequencing depth, so this is not a problem for merge_samples. However, my three groups contain: 175, 224 and 256 samples, respectively, so just forming the sum of all samples per group would bias my data. How can I adjust for this? Another issue is that my data is not normally distributed so I would actually prefer to calculate the median over the mean for each group and plot that. How can I do that instead? I am sure there is some kind of R function for that as well but I am not very experienced in R.
Thank you for your help!
Kind regards,
Stef

**Comment by nasden** [comment]
> Did you look at the `merge_samples` function? It is designed for this purpose, for example.
> 
> Is this issue still outstanding for you? If you did solve your problem, do you mind posting here how you did it, and/or what you might have preferred?
> 
> Also, the new app [Shiny-phyloseq](http://joey711.github.io/shiny-phyloseq/) might be useful for you, but you'll probably want to use an ordination or network plot, rather than a heatmap or tree, to summarize your data (or merge the samples before uploading for analysis).
> 
> Thanks again for the feedback, and your interest in phyloseq.

Hi, 

SO I have two sets of features_hdf5.biom files (the second one is from the re-run sequences). How do I merge my two features_hdf5.biom files and replace a few samples from the second file onto the first file?

Nas

**Comment by DevsLilSis** [comment]
Hello! I think I'm having a similar issue, although I have different purposes, I just wanna make a composition plot...

I have 4 groups, 2 of those have 5 replicates and 2 have only 4 replicates. 

-I have already standardized to median sequencing depth:
total = median(sample_sums(physeqtpf))
standf = function(x, t=total) round(t * (x / sum(x)))
AyB = transform_sample_counts(physeqtpf, standf)

-And transformed to relative abundances:
AyBrelative  = transform_sample_counts(AyB, function(x) x / sum(x) )

Then I use merge_samples to group the replicates in their respective groups and plot:
AyBCode <- merge_samples(AyBrelative, "Code", fun = median)
plot_bar(AyBCode, fill = "Phylum") + 
  geom_bar(aes(color=Phylum, fill=Phylum), stat="identity", position="stack")

The problem is that I get a plot that has 1-5 in the Y axis and the groups with 5 replicates have bars up to 5, and the ones with 4 have bars up to 4...I know this comes from the fact that merge_samples sums the reads in the samples...but I havent been able to figure out how to fix it so that i get a plot up to 100% for all the bars, and not with dissimilar heights...

Thanks for all your help in advance

**Comment by brenzink** [comment]
I have exactly the same problem. Did you find an answer?
