### ISSUE TITLE
issue with subset_taxa

### ISSUE THREAD

**Issue by jenkel** [joey711/phyloseq#374]
Hi, 

I imported my biom file, tree file and mapping file separately and then used merge_phyloseq to join them together. When I tried to subset my data to just Ruminococcaceae I got the following error,

> GRum <- subset_taxa(satin_005, Family == "f__Ruminococcaceae")
> Error in `rownames<-`(`*tmp*`, value = c("sp1", "sp0")) : 
>   length of 'dimnames' [1] not equal to array extent

I have previously checked that the rank names and genus names are present in the dataset:

> rank_names(satin_005)
> [1] "Kingdom" "Phylum"  "Class"   "Order"   "Family"  "Genus"   "Species"
> 
> get_taxa_unique(satin_005,"Family")
>  [1] "f__Lachnospiraceae"       "f__Ruminococcaceae"  
>  [3] "f__"                      "f__Erysipelotrichaceae"  
>  [5] "f__[Coprobacillaceae]"    "f__[Odoribacteraceae]"  
>  [7] "f__[Barnesiellaceae]"     "f__Porphyromonadaceae"  
>  [9] "f__Rikenellaceae"         "f__[Paraprevotellaceae]" 
> [11] "f__Prevotellaceae"        "f__Bacteroidaceae"  
> [13] "f__Bifidobacteriaceae"    "f__Coriobacteriaceae"  
> [15] "f__Enterobacteriaceae"    "f__Alcaligenaceae"  
> [17] "f__Desulfovibrionaceae"   "f__Verrucomicrobiaceae"  
> [19] "f__Veillonellaceae"       "f__Christensenellaceae"  
> [21] NA                         "f__Turicibacteraceae"  
> [23] "f__Streptococcaceae"      "f__Lactobacillaceae"  
> [25] "f__Leuconostocaceae"      "f__Peptostreptococcaceae"
> [27] "f__Clostridiaceae"        "f__Catabacteriaceae"  

What could be the issue? 

Thanks for your help,

Jen

**Comment by storme994** [comment]
Hi @joey711,

I came across the same issue as @jenkel - however I imported the taxonomy file separately and used this to create a phyloseq file (code): 

`otu_m <-read.table("otu_phyloseq_trial_otuid.txt",header=T, row.names=1, sep="\t")
as.matrix(otu_m) -> otumat

tax_m <-read.table("tax_file.txt",header=T, row.names=1, sep="\t", na.strings = "")
as.matrix(tax_m) -> taxmat
OTU = otu_table(otumat, taxa_are_rows = TRUE)
TAX = tax_table(taxmat)

physeq = phyloseq(OTU, TAX)

sample_data <-read.table("metadata_noref_num.txt",header=T, row.names=1, sep="\t")
sampledata = sample_data(sample_data)

library("ape")
random_tree = rtree(ntaxa(physeq), rooted=TRUE, tip.label=taxa_names(physeq))

physeq1 = merge_phyloseq(physeq, sampledata, random_tree)`

Then when using subset_taxa, I got the error:
`Error in `rownames<-`(`*tmp*`, value = c("sp1", "sp0")) : length of 'dimnames' [1] not equal to array extent`

I could not find any help for this error relating specifically to the subset_taxa function. Upon evaluating my taxonomy table, I found that some empty spaces had " " (a space) within them instead of being completely empty. 

I removed the spaces using:

`replace(tax_m, tax_m == " ", NA) -> tax123`

And then remade the phyloseq file. The subset_taxa function then worked. 

Hope this simple solution helps some other users!

storme
```
