### ISSUE TITLE
Independent Filtering of OTU dataset

### ISSUE THREAD

**Issue by wblewis7** [joey711/phyloseq#417]
I am using phyloseq-DESeq2 to normalize my sequencing data with the negative binomial method as in "Waste not, Want not." I have a large number of very low abundance OTUs which I would like to remove. Would it be best to perform the independent filtering before or after performing the normalization in phyloseq? For my data, I am more interested in overall community differences between groups than in differential abundance with specific OTUs.

Will

**Comment by joey711** [comment]
This is a tricky question that cannot really be answered in the abstract. Your experimental design, and real data might need more careful consideration, and it is generally left to the user to decide threshold parameters for filtering, etc. I make no claims about general-purpose, one-size one-workflow fits all data.

I generally do recommend some level of independent filtering prior to making microbiome-microbiome pairwise comparisons. A good prevalence filter usually goes a long way. There are many ways to accomplish this in phyloseq's `filter_taxa`, `prune_taxa` and related tools. For removing blatant noise, you're better off doing it before you try to do any complicated model fitting, rather than after. For differential abundance detection with DESeq2, independent filtering is part of the standard workflow, so you'll get that part "for free" anyway.

[the phyloseq FAQ](https://www.bioconductor.org/packages/release/bioc/vignettes/phyloseq/inst/doc/phyloseq-FAQ.html) might also be helpful...
