### ISSUE TITLE
plot_ordination label size

### ISSUE THREAD

**Issue by CarlyRae** [joey711/phyloseq#422]
When I use plot_ordination, with label = "X" the size of the font is so small it is hard to read

plot_ordination(run_invert, SMP.jac.invert, color = "Site", shape = "Species", label  = "Run_no")

![image](https://cloud.githubusercontent.com/assets/3433598/5631678/4d260796-9596-11e4-8195-e54bb028bf99.png)

I can do 

p <- plot_ordination(run_invert, SMP.jac.invert, color = "Site", shape = "Species", label  = "Run_no")

p + theme_bw() +  theme(text = element_text(size = 16)) + geom_point(size = 4) 

![image](https://cloud.githubusercontent.com/assets/3433598/5631675/44dfeea8-9596-11e4-961c-2841cee3f547.png)

to get the other items larger, but I am at a loss for how to make the label sizes larger. I've done a good bit of searching and need help with this. 

Thank you

**Comment by joey711** [comment]
I suspect this results from the text size being set explicitly in the point label layer definition. Individual layer definitions supersede theme-defined sizes, which are really just defaults. 

For example, 

```S
ggplot(mydf, aes(xvar, yvar)) + geom_text(size = 15) + 
theme_bw() + theme(text = element_text(size = 5)) + geom_point(size = 4)
```

Will produce a plot with size-15 text, even though the theme-spec sets the default value to `5`.

Hope that helps. I will close for now, but feel free to post back if this does not completely solve your issue.

Thanks again for your feedback and contribution to phyloseq devel :-)

joey

**Comment by CarlyRae** [comment]
I have tried a few ways around trying to add the geom_text into the code. The problem is first if I try to use ggplot to plot the ordination I generated with plot_ordination = p 

ggplot(p, aes(Axis.1, Axis.2))  +theme_bw() +  theme(text = element_text(size = 16)) + geom_point(size = 4)

I get this error Error: ggplot2 doesn't know how to deal with data of class ggggplot

So I don't know how to add the geom_text to a non-ggplot object

I've tried a few different ways 

p <- plot_ordination(run_invert, SMP.jac.invert, color = "Site", shape = "Species", label = "Run_no") + geom_text(size = 15)

p 

Error: geom_text requires the following missing aesthetics: label

p = plot_ordination(run_invert, SMP.ord.invert, color = "Site", shape = "Species", label = "Run_no") + geom_text(data = run_invert, label = "Run_no", size = 15)

Error: ggplot2 doesn't know how to deal with data of class phyloseq

It will work if I I do

p = plot_ordination(run_invert, SMP.ord.invert, color = "Site", shape = "Species", label = "Run_no") + geom_text(label = "Run_no", size = 4)

p  + theme_bw() +  theme(text = element_text(size = 16)) + geom_point(size = 4)

![image](https://cloud.githubusercontent.com/assets/3433598/5635347/5ef1c486-95b6-11e4-88f3-56576d24f508.png)

But that's not what I need....

I've tried to bring in a separate mapping file with the right labels 

p + geom_text(data = map, label = "Run_no")

Error in eval(expr, envir, enclos) : object 'Axis.1' not found

If I look at the normal layers from p 

p$layers
[[1]]
geom_point: na.rm = TRUE 
stat_identity:  
position_identity: (width = NULL, height = NULL)

[[2]]
mapping: x = Axis.1, y = Axis.2, label = Run_no, na.rm = TRUE 
geom_text: parse = FALSE, na.rm = TRUE, size = 2, vjust = 1.5 
stat_identity:  
position_identity: (width = NULL, height = NULL)

I really am at a lose of how you change that default size in [[2]]. I am assuming that is what needs to be fixed somehow. 

Any other insight would be appreciated. 

Cheers,

Carly

**Comment by joey711** [comment]
Carly,

You're very close. Don't keep "a separate mapping file". Include the additional sample covariates in your phyloseq data object from the beginning so that everything is consistent, shareable, and in one place.

You can add/replace sample data in a phyloseq object with the accessor/assignment framework with `sample_data` as the phyloseq-specific nomenclature (assume you have a `data.frame` with your additional "mapping" data called `newmapdf`:

```S
sdf = sample_data(run_invert)
sample_data(run_invert) <- sample_data(cbind(data.frame(sdf), newmapdf)))
physeq1
```

printing `run_invert` should mention more sample variables than before, and you should have the variable you want to label now available with the code you showed above, with the following correction.

```S
plot_ordination(run_invert, SMP.ord.invert, color = "Site", shape = "Species") + 
geom_text(mapping = aes(label = Run_no), size = 10) +
theme_bw()
```

Hope that helps!

**Comment by CarlyRae** [comment]
I don't actually keep separate mapping files. I do merge them all together. This is usually how I get them in 

biom_all <-paste("SMP_uparse_norm_taxa.biom", sep = "")
tree_final <- read.nexus("Rooted_pruned.tre")
map_site_sp <- import_qiime_sample_data("map_site_sp.txt")

run.I <- import_biom(biom_all, tree_final)

**Comment by joey711** [comment]
Well, you can always find documentation at the ggplot2 website, for instance:

http://docs.ggplot2.org/current/geom_text.html

and some basic info / examples are available within ggplot2 package doc:

```S
?geom_text
```

`mapping` is simply the first argument to the `geom_text` function, and actually not even necessary. I included it for emphasis. The important thing was to instruct ggplot2 to map the `label` attribute of the `geom_text` layer to the `Run_no` variable, and this is always done through the aesthetic mapping function, `aes`.

The following would also work just as well as your example, and is a little easier to read IMO because some of the unnecessary bits are omitted ...

```S
plot_ordination(run_invert, SMP.ord.invert, 
   color = "Site", 
   shape = "Species") +
geom_text(aes(label = Run_no), size = 10, vjust = 1.5) + 
geom_point(size = 4) +
theme_bw()
```
 
Cheers

joey

**Comment by ajcardenasb** [comment]
Hello,
I have a similar issue with geom_text function and tried to use the same advice but it did not help for me.  I am plotting a radial tree with any problem except that the tip labels are not rotated according to the tree. 

![test](https://cloud.githubusercontent.com/assets/11017843/11457459/14516e70-96bb-11e5-976c-35289da2d291.png)


I am trying to use the following command in order to have the tip labels in the same angle than the the branches.

d = plot_tree(AS.100, color = "treatment", label.tips = "order", size = "abundance", ladderize = "left" ) + coord_polar(theta = "y") + geom_text(aes(label = order, angle=angle), size=3, color="purple", hjust=-0.3)

but always get errors like this one:

Don't know how to automatically pick scale for object of type function. Defaulting to continuous
Error in data.frame(label = function (..., na.last = TRUE, decreasing = FALSE)  :
  arguments imply differing number of rows: 0, 396

Any hint would be appreciated.

Cheers,
Anny
