### ISSUE TITLE
plot_heatmap ylab not editable

### ISSUE THREAD

**Issue by shokoiwai** [joey711/phyloseq#433]
I'd like to use custom label for y-axis on plot_heatmap output but I cannot edit.

**Comment by ghanesh** [comment]
I have a similar problem:
using plot_heatmap(myData, sample.order="Leche", sample.label="Leche"", taxa.label="Rank2", title=""OTU abundance with Leche") results in exactly the same output as when using taxa.label="Jabba". The Environment in R though has Rank2 as header for tax level as my tree is not rooted and by default, the parse_greengeenes during import expects a Root as first Rank....btw is there a way to change this?
Any help highly appreciated.
Thank you very much, and sorry for hijacking this issue :-)

**Comment by joey711** [comment]
@ghanesh Probably better if you post this to a new issue (if you haven't already). About to complete and close this issue...

**Comment by joey711** [comment]
It turns out that ggplot2 has multiple ways to re-name the axis labels,
and the different ways appear to have a hierarchy of precedence. 
The common and convenient and easy-to-remember `ylab()` function
appears to have lower precedence than naming the axis in a `scale_discrete` layer,
which is what `plot_heatmap` does in order to provide the element-renaming feature.
There are other ways `plot_heatmap` could do this to better support the `ylab` option, 
but it would require rewriting some of the `plot_heatmap` function
and I don't see much/any functional difference for the end-user,
so long as this workaround is documented (as I'm attempting to do here, and elsewhere).

### Heat Map Example

For further details, see the [plot_heatmap tutorial](http://joey711.github.io/phyloseq/plot_heatmap-examples.html)

As the number of taxa in a dataset gets very large, the ability to effectively display all of the elements of the data becomes compromised, and a heatmap representation is no exception. It can also be time-consuming to render. To address both these issues, we show an example in which we have subsetted the Global Patterns dataset to a manageable portion, in this case, the Crenarchaeota phylum.


```S
library("phyloseq"); packageVersion("phyloseq")
```

```
## [1] '1.10.0'
```

```S
data("GlobalPatterns")
gpac <- subset_taxa(GlobalPatterns, Phylum=="Crenarchaeota")
(p <- plot_heatmap(gpac, "NMDS", "bray", "SampleType", "Family"))
```

![gpheatmap-1](https://cloud.githubusercontent.com/assets/841437/6453355/56c956d8-c0fa-11e4-8df0-2fdf5b822318.png)

### What if you wanted to change the axis labels?


```S
library("ggplot2"); packageVersion("ggplot2")
```

```
## [1] '1.0.0'
```

```S
p$scales$scales[[1]]$name <- "My X-Axis"
p$scales$scales[[2]]$name <- "My Y-Axis"
print(p)
```

![gpheatmap-rename-axes-1](https://cloud.githubusercontent.com/assets/841437/6453374/75105646-c0fa-11e4-9bb0-b8ce453d31d0.png)

### Update

I have updated the "analysis" vignette to point out this trick,
and I have also updated the `plot_heatmap` vignette to also mention this.
This should effectively close this issue.
