### ISSUE TITLE
Error: could not find function "import_biom"

### ISSUE THREAD

**Issue by elinekl** [joey711/phyloseq#461]
HI,
I loaded phyloseq into R. If you run packageVersion("phyloseq") it says 1.10.o. SO I suppose this means phyloseq is loaded.
But I can't import a biom file with import_biom as I get an error could not find function "import_biom"
Any ideas what I'm doing wrong?
Cheers,
Eline

**Comment by spholmes** [comment]
What happens if you type
?import_biom

I would say restart R and reload phyloseq with
library(phyloseq)

I haven't had this particular error..

On Wed, Apr 15, 2015 at 12:04 AM, eline klaassens <notifications@github.com>
wrote:

> HI,
> I loaded phyloseq into R. If you run packageVersion("phyloseq") it says
> 1.10.o. SO I suppose this means phyloseq is loaded.
> But I can't import a biom file with import_biom as I get an error could
> not find function "import_biom"
> Any ideas what I'm doing wrong?
> Cheers,
> Eline
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/461>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
Director, MCS
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by elinekl** [comment]
restarting everything helped me out, thanks
