### ISSUE TITLE
merge physloseq - request for more detailed information

### ISSUE THREAD

**Issue by macrobiotus** [joey711/phyloseq#474]
Hi Joey, thanks for developing Phyloseq it is one of the most useful packages of my work lately. I have two Phyloseq objects with partly overlapping sample_names() and sample_data(), generated with different markers. Now I would like to merge both sets into one Phyloseq object. I would rename the taxa_names() with a prefix, e.g. "18S_" and "COI_", which would modify these identifiers in the otu_table(). Where is the object that links OTUs to samples? I'm assuming that would need to be altered as well before merging. Point being I don't want the taxa_names() to be added together, but append the otu_table() of the finished object - so that in the end I have one Phyloseq object, with one OTU table comprising of OTUs from each marker. I checked the help, but was hoping that you could give some information of how to achieve this particular task - I will edit taxa_names() and sample_data() but am unsure where to find OTU assignemnt to sample_data(). Thank you and kind regards, I hope this all makes sense and Kind regards, Cheers, Paul

**Comment by macrobiotus** [comment]
Solved via editing dimnames() and other references to OTU labels, sample labels and sequence labels in phyloseq object prior to merging. Fingers crossed. Thank you.

**Comment by joey711** [comment]
Nice! Thanks for solving and closing! All relevant indices have to match for phyloseq to know what to do with the objects you're merging. Furthermore, two or more counts with the same sample and OTU indices are summed together by default. If that is a problem for your analysis, you'll want to give these different sample names. In general, all replicates of any kind should have different sample IDs. The `sample_data` can distinguish different types of covariates and replicate IDs, so that is the recommended way to keep track of those in further analysis.

Best of luck!
