### ISSUE TITLE
heatmap error: using tutorial script

### ISSUE THREAD

**Issue by nidhi13** [joey711/phyloseq#484]
> data("GlobalPatterns")
> gpt <- subset_taxa(GlobalPatterns, Kingdom=="Bacteria")
> gpt <- prune_taxa(names(sort(taxa_sums(gpt),TRUE)[1:300]), gpt)
> h<-plot_heatmap(gpt, sample.label="SampleType")
Error in order(mdf$Abundance, decreasing = TRUE) : 
  argument 1 is not a vector

Could someone explain what the error means? 

I also got an error when I tried my own data:

gpt<-subset_taxa(merge2,Kingdom=="Bacteria")
> gpt<-prune_taxa(names(sort(taxa_sums(gpt),TRUE[1:300]),gpt))
Error in prune_taxa(names(sort(taxa_sums(gpt), TRUE[1:300]), gpt)) : 
  error in evaluating the argument 'taxa' in selecting a method for function 'prune_taxa': Error in sort(taxa_sums(gpt), TRUE[1:300]) : 
  'decreasing' must be a length-1 logical vector.
Did you intend to set 'partial'?

**Comment by audy** [comment]
Your example worked for me (phyloseq 1.7.24). Which version of Phyloseq/R are you running (type `sessionInfo()`)? Does the error still happen if you run the example code in a fresh R session?

**Comment by nidhi13** [comment]
R version 3.1.1 and phyloseq 1.10.0. Am comfortable with this R version, as when I updated R, things did not work, so I reverted to the older version.
Tried it in a fresh session and got same error.

**Comment by michberr** [comment]
What other packages do you have loaded? If you have reshape loaded instead of reshape2, the psmelt function which is contained in the plot_heatmap function fails. It  would lead to that error because the vector "Abundance" is never created during the melting process. This is just a guess, but it would be helpful if you could post your entire session info

**Comment by nidhi13** [comment]
Yes! I loaded reshape instead of reshape2, detached and loaded reshape2 and it works. Brilliant. thanks!

**Comment by joey711** [comment]
This is now fixed in `1.13.3+`.
If you don't want to install the devel version (simply wait for the next BioC release), then @michberr 's `detach` workaround should also be fine. This is due to a name collision with the old, slow "reshape" package. phyloseq uses the faster "reshape2" package of the same author. They both contain a function called `melt`. This issue is now fixed, as phyloseq explicitly calls `reshape2::melt` in all instances.

Will close for now.

joey
