### ISSUE TITLE
Discrepancy between OTU number in phyloseq and biom summarize-table output

### ISSUE THREAD

**Issue by amrutahv** [joey711/phyloseq#512]
Hello,
I don't know if anyone else has experienced this before. I have used QIIME v 1.9.1 to build a biom table. Using the "biom summarize table" command, I obtained the following

Num samples: 25
Num observations: 56962
Total count: 3760136
Table density (fraction of non-zero values): 0.127

Counts/sample summary:
 Min: 21866.0
 Max: 282898.0
 Median: 142323.000
 Mean: 150405.440
 Std. dev.: 75224.327
 Sample Metadata Categories: Description; Habitat; PopID; BarcodeSequence; InputFileName; Host; LinkerPrimerSequence; ReverseBarcode; Individuals; ReversePrimer
 Observation Metadata Categories: taxonomy

Counts/sample detail:
( per sample information)

The number of observations here is 56962.

I imported the same table in phyloseq in R. And when I check the imported phyloseq object, this is what appears.

biomdata
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 42154 taxa and 25 samples ]
sample_data() Sample Data:       [ 25 samples by 10 sample variables ]
tax_table()   Taxonomy Table:    [ 42154 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 42154 tips and 42152 internal nodes ]

Doesn't the number 42154 here indicate number of OTUs?

If yes, then I wonder why it is different from "biom summarize-table" command.

Further information about the versions etc:
phyloseq 1.12.2
R 3.2.1
biom format 2.1.0

Hoping someone can answer this.

Amruta

**Comment by CarlyRae** [comment]
Yes, I have noticed this before. 

What is likely happening is your phylogenetic tree does not contain all the OTUs that were generated when you just look at your biom file. If you are running the pick_de_novo_otus.py in QIIME then you are using pynast to align your sequences. If you go into that folder called pynast_aligned_seqs on default (or something similar) you will find the sequences that fail alignment. When you generate a tree using fasttree all of those sequences (OTUs) that failed alignment don't go into the tree. 

If you read your biom_file into Phyloseq as the otu_table and look at the stats of the otu_table such as ntaxa() you should see the same number of OTUs (56962). But, when you have the biom and tree files merged then all the OTUs that did not align get thrown out. In many instances this is a good thing. They are sequences that are not aligning well with other sequences and can just be 'junk'. For instance, I have seen chicken 18s rRNA sequences be assigned as a bacterial OTU (when doing 16s rRNA microbiome on chicken samples) that stayed in my biom_table but when you go to align these sequences they fail alignment because they aren't even the gene you are looking for. BUT, I have also seen where know sequences have been thrown out for alignment. You might want to lower the threshold of alignment to get those sequences in. Here is a post from QIIME google forum on a bug that was in 1.9 that should be fixed now. https://groups.google.com/forum/#!topic/qiime-forum/VQ7OxzFENcw

Not really a phyloseq issue. It just happens when you are merging these files in phyloseq. 

Cheers,

Carly
