### ISSUE TITLE
Questions on Deseq with Phyloseq tutorial

### ISSUE THREAD

**Issue by rkenne12** [joey711/phyloseq#522]
Hello, 

I am a novice and any help you could give would be greatly appreciated.  I am using the following tutorial:  
http://joey711.github.io/phyloseq-extensions/DESeq.html 
 to analyze significant differences in my 16s data set.  I ran the analysis and it looked very close to my relative abundance, but I have a few questions.  

The first questions is why was 30 chosen as your variance threshold?  Was this based on the frequency of your low variance OTUs?  

Second, what does the number 1 refer to in the script: keepOTUs = apply(otu_table(kostic), 1, var) > varianceThreshold? 

Third, what would be an appropriate script to use if my n= 3 per group in stead of the script:  cds = phyloseq_to_DESeq(kostic1, "DIAGNOSIS", sharingMode = "gene-est-only").  

Finally, why was alpha set to 0.1 instead of 0.05 or 0.01?

**Comment by joey711** [comment]
- (1) It was arbitrary, to make the example work fast and make the point. You should choose this more carefully in your own data.
- (2) If you read the `apply` documentation, the second argument specifies the index. 1 means "apply on rows"
- (3) I don't think this call necessarily changes because you have 3 samples per group
- (4) For fun so there was more to plot :-)
