### ISSUE TITLE
problem jittering points for plot_richness

### ISSUE THREAD

**Issue by jennomics** [joey711/phyloseq#523]
Here's my code:

p = plot_richness(ISS, measures = c("Shannon"), color = "Surface", x = "Description")
p + geom_point(size = 3, position = "jitter") + theme_bw(base_size = 18)

I get the jittering that I want, but the original (non-jittered) points also remain on the plot.

How can I remove those? Thanks!

**Comment by jennomics** [comment]
I found the answer on this tutorial, thanks!

http://joey711.github.io/phyloseq/plot_richness-examples

**Comment by joey711** [comment]
Great!

**Comment by TseWue** [comment]
Hi,

I have the same question but I don't see how this tutorial helps in removing the original dots from the plot_richness() command. I have tried shape = NA but then I can't add points back on with the geom_point() command since it doesn't do the same math with the data. Also, I have tried to find a way to just color the original dots white but that didn't work.
Any ideas?

Thank you!

**Comment by wRajter** [comment]
Hi there,

I've encountered the same problem. I wanted to make a plot with jittered data points, but non-jittered original points remained on the plot.

As mentioned, this tutorial explains how to fix -> http://joey711.github.io/phyloseq/plot_richness-examples. It is in the last paragraph (More details about ggplot2).

I used the code for the plotting image and right after it, I added this one line: <plotname>$layers <- <plotname>$layers[-1] and then it worked.

Example of my code:
> plot <- plot_richness(abu_small, x="habitat", color="habitat",
>                                measures="Observed") +
> geom_point(size=2, position = "jitter")
> 
> plot$layers <- plot$layers[-1]

Hope this help :) 
And happy plotting to everyone!
