### ISSUE TITLE
JSON error with importing .biom

### ISSUE THREAD

**Issue by ecologysarah** [joey711/phyloseq#530]
Hi,

I've just started using phyloseq, and have hit a brick wall in importing my data. I have my otu table as a biom, created in QIIME. After reading some of the other threads about biom issues, I've added taxonomy metadata to it (biom add-metadata -i otu_table.biom -o otu_table_tax.biom --observation-metadata-fp rep_set_taxonomy.tsv --observation-header OTUID,taxonomy --sample-metadata-fp map.tsv --sample-header SampleID,Precoloniser,Site --sc-separated taxonomy), and converted it from HDF to JSON (biom convert -i otu_table_tax.biom -o otu_table_tax_json.biom --table-type="OTU table" --to-json). 

I've then tried to load it into phyloseq:
biom1 = system.file("extdata", "otu_table_tax_json.biom", package = "phyloseq")
wood_data = import_biom(biom1)

But keep getting this error:
Error in fromJSON(content, handler, default.size, depth, allowComments,  : 
  invalid JSON input

If I try:
read_biom("otu_table_tax_json.biom")
Then the biom seems alright:
biom object. 
type: OTU table 
matrix_type: sparse 
8648 rows and 95 columns 

I'd be very grateful for any suggestions!

Thanks,

Sarah

**Comment by joey711** [comment]
that's not a valid file path. the `system.file()` command is shown in tutorials because it makes them OS-independent and they are referring to data that is located within the package itself. Obviously your data is not in the package, nor should it be.

Your file path for your data should just be a standard relative or absolute Unix path string.

```S
jsonbiomfile = "path/to/my/data/file.biom"
import_biom(jsonbiomfile)
```

Please see also:
https://github.com/joey711/phyloseq/issues/443

**Comment by ecologysarah** [comment]
Thanks, that makes sense now! I'm still quite new to working with code, so when working off a script I sometimes miss which bits I need to modify!
