### ISSUE TITLE
Error in file(con, “r”) : cannot open the connection

### ISSUE THREAD

**Issue by moon-thestral** [joey711/phyloseq#540]
Using R 3.2.2 in Windows 8.1, I'm trying to import a qiime otu table file, using this code:

biom_otu_tax <- import_biom("D:/from_qiime/micro/results/otus_open_ref_R1otu_table_mc2_w_tax_no_pynast_failures.biom")

However, I get the error message:

    Error in file(con, "r") : cannot open the connection

I have tried every combination of:

-    First running setInternet2(TRUE) (this fixes it for most people)
-    Setting my working directory to the file location
-    Running it in R, rather than RStudio
-    Opening R/RStudio as an administrator
-    Restarting my computer

Nothing seems to fix it.

**Comment by moon-thestral** [comment]
I made a mistake and got the file path wrong - missed a "/". However, when I corrected it I still got an error:

> biom_otu_tax <- import_biom("D:/from_qiime/micro/results/otus_open_ref_R1/otu_table_mc2_w_tax_no_pynast_failures.biom")

Error in fromJSON(content, handler, default.size, depth, allowComments,  : 
  invalid JSON input

**Comment by spholmes** [comment]
This is just because Windows does not recognize your path.
It is better to move to your working directory where your data is with the
setwd()
command or define the path
called "Start in:' enter the full path to the folder
for instance.
Susan

On Thu, Oct 15, 2015 at 3:12 PM, moon-thestral <notifications@github.com>
wrote:

> Using R 3.2.2 in Windows 8.1, I'm trying to import a qiime otu table file,
> using this code:
>
> biom_otu_tax <-
> import_biom("D:/from_qiime/micro/results/otus_open_ref_R1otu_table_mc2_w_tax_no_pynast_failures.biom")
>
> However, I get the error message:
>
> Error in file(con, "r") : cannot open the connection
>
> I have tried every combination of:
>
>    - First running setInternet2(TRUE) (this fixes it for most people)
>    - Setting my working directory to the file location
>    - Running it in R, rather than RStudio
>    - Opening R/RStudio as an administrator
>    - Restarting my computer
>
> Nothing seems to fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/540>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by moon-thestral** [comment]
That didn't fix it

**Comment by spholmes** [comment]
Then maybe you have the new HD5 format for your biom file see this issue
and solution:
here are some issues that are similar and have solutions:
https://github.com/joey711/phyloseq/issues/530
https://github.com/joey711/phyloseq/issues/520
https://github.com/joey711/phyloseq/issues/443
There is a new version now that enables the HD5 format as well,
but you need to update your version to the one on github,

Susan



On Thu, Oct 15, 2015 at 7:18 PM, moon-thestral <notifications@github.com>
wrote:

> That didn't fix it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/540#issuecomment-148577436>.
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by joey711** [comment]
@moon-thestral your original issue (e.g. the title) was about not knowing how to specify the system path. You have since posted an identical issue on BioC support site. Please try and stick to one place, preferably here if you posted here first. The BioC site will get forwarded to me anyway.

This issue is closed, because you resolved the file connection problem. Please review Susan's helpful links to related issues with the sneaky two separate formats defined as `.biom`. If you still need help, post a new issue fully specifying the new problem, which is likely related to this format change. There are workarounds, and you might be able to find your solution on one of those previously answered issue links.

The original biom format was JSON-based, and that was the original supported in phyloseq. @jnpaulson and I have a submitted a new package to BioC, called "biomformat", that can import and automatically recognize both the HDF5 and JSON formats so that this doesn't come up again. It will be included in the devel version of phyloseq very soon, and the release version of phyloseq about 6 months from now when BioC does their next release (they just had a release).

Thanks and good luck

joey
