### ISSUE TITLE
How to access or set factor levels in tax_table?

### ISSUE THREAD

**Issue by andrewd001** [joey711/phyloseq#548]
Hi,
I've been using Phyloseq to plot trees of OTUs annotated with sample data (e.g. Elevation) or taxonomic identities (e.g. Phylum). I want to treat a taxonomic rank (Phylum, for example) as a factor with levels that are plotted in a specified order, but I can't figure out how to achieve this. 

In a non-Phyloseq context, I might set factor levels in a dataframe like this:
> df$Phylum <- factor(df$Phylum, levels = tax_ref$Phylum, ordered = TRUE)
(where tax_ref$Phylum contains phyla names in the desired order). I assumed that a similar method would apply in a Phyloseq environment. 

I understand that sample data can be accessed like this: 
> sample_data(physeq)$Elevation

But this doesn't work for the tax_table:
> tax_table(physeq)$Phylum
    Error in tax_table(physeq)$Phylum : $ operator is invalid for atomic vectors

So this method of setting factor levels doesn't work either (same error):
> tax_table(physeq)$Phylum <- factor(tax_table(physeq)$Phylum, levels = tax_ref$Phylum, ordered = TRUE)
    Error in tax_table(physeq)$Phylum : $ operator is invalid for atomic vectors

I discovered that this seems to work for accessing Phylum levels:
> tax_table(physeq)[, "Phylum"]

But doing the following replaces all the Phylum names with numbers instead:
> tax_table(physeq)[, "Phylum"] <- factor(tax_table(physeq)[, "Phylum"], levels = tax_ref$Phylum, ordered = TRUE

So, how can I set the factor level order for tax_table(physeq)$Phylum?

Thanks,

Andrew.

**Comment by michberr** [comment]
Hi Andrew,

You cannot access the Phylum column of tax_table with a $ because the underlying data structure is a matrix not a dataframe. Similarly, you can't turn the Phylum column into a factor because the data type  for that whole matrix is "character" and matrices cannot hold mixed data types in R.

Some of the plotting functions in phyloseq such as plot_bar utilize the function psmelt which melts all of your sample_data and tax_table data into one dataframe and then it is easy to manipulate any column reorder factors. Unfortunately, this is not the case for plot_tree(). 

Sorry, I'm not sure how to do what you're requesting, and it may not be possible with the way the functions are written, but hopefully it's slightly more satisfying to know more about the structure of phyloseq objects and why what you had tried did not work.

Best,
Michelle

**Comment by andrewd001** [comment]
Hi Michelle,

Aha. Thank you, that's an excellent and concise explanation. It is better knowing why it won't work, even if there's no current solution. Much appreciated.

Cheers,

Andrew.
