### ISSUE TITLE
plot_heatmap PDF rendering error

### ISSUE THREAD

**Issue by jeffkimbrel** [joey711/phyloseq#555]
There is an error in the PDF rendering of a heatmap in RStudio, both saving as a .PDF from the "plots" section, and from an R markdown document with `dev="pdf"`. When saving as a .png, of with `dev="png"`, the heatmap looks correct. 

[PDF](https://github.com/joey711/phyloseq/files/34435/unnamed-chunk-8-1.pdf)
[PNG](https://cloud.githubusercontent.com/assets/10132972/11160068/5e631c6e-8a1a-11e5-8451-34c37f1284db.png)

What appears to be happening is it is setting the number of columns equal to the number of rows (or vice versa), and creating a weird interpolation of colors. 

This may be an Rstudio or other problem, but I only see this with `plot_heatmap`objects.

```
packageVersion("phyloseq")
[1] ‘1.13.6’
```

**Comment by joey711** [comment]
For saving graphics to PDF, I prefer and suggest ggplot2's `ggsave()` function

```S
myHeatMap = plot_heatmap(physeq, ...)
# Width and height are in inches
ggsave(filename = "heatmapFile.pdf", plot = myHeatMap, width = 9, height = 6.5)
```

Hope that helps! Will close for now. Can open if something else comes up.

**Comment by benjjneb** [comment]
Jeff, the issue here is not with phyloseq or ggplot2, it is with certain pdf viewers, most commonly Preview on the Mac. 

Preview incorrectly displays this pdf when the "Smooth text and line art" option is checked in Preferences..., which it is by default. You can reopen in Preview and uncheck that box, or open in an Adobe viewer, and the pdf will display correctly.
