### ISSUE TITLE
geom_text error

### ISSUE THREAD

**Issue by ajcardenasb** [joey711/phyloseq#558]
Hello,
 I am plotting a radial tree but the tip labels are not rotated according to the tree. I am using  geom_text function but I can´t map the the label attribute of the geom_text layer to my variables. 

this is what I ran to build the tree 
 d = plot_tree(AS.100, color = "treatment", label.tips = "order", size = "abundance", ladderize = "left" ) + coord_polar(theta = "y")

![](https://cloud.githubusercontent.com/assets/11017843/11457459/14516e70-96bb-11e5-976c-35289da2d291.png)

and this in order to have the tip labels in the same angle than the the branches:

d = plot_tree(AS.100, color = "treatment", label.tips = "order", size = "abundance", ladderize = "left" ) + coord_polar(theta = "y") + geom_text(aes(label = order, angle=angle), size=3, color="purple", hjust=-0.3)

but always get errors like this one:

Don't know how to automatically pick scale for object of type function. Defaulting to continuous
Error in data.frame(label = function (..., na.last = TRUE, decreasing = FALSE) :
arguments imply differing number of rows: 0, 396

Any hint would be appreciated.

Cheers,
Anny

**Comment by lfaller** [comment]
Hi Anny,

Were you able to come up with a solution for this problem? I would also be interested in rotating the labels so that they go well with the angled branches.

Thanks!
~Lina

**Comment by joey711** [comment]
hi, sorry its taken so long to respond. I coded a solution to this a while back. It will take me a bit to find it. The trick was to map text angle to the radial position in the aesthetic-mapping definition (`aes`) so that they match up nicely. I suspect there is a nicer way to do this.

On the other hand, it is not a terrible outcome that all your text labels are legible from one point of view. That's often how we end up doing things in cartesian plots, with the exception of a few right angles to save margin on the vertical axis. Having text every which way adds a surprising amount of "mental overhead" for a lot readers.

I'll close as this is not a feature I'm planning to add in the short-term (but I'd be happy to entertain a pull request that adds this if someone finds a nice tweak).

In the mean time, there is an example of exactly what you want provided in the **ggtree** BioC package:

https://www.bioconductor.org/packages/3.3/bioc/vignettes/ggtree/inst/doc/treeVisualization.html

(scroll down to find it)

The words are upside down in one of the hemispheres, but it is closer to what you're requesting.

Hope that helps! If you find or code a solution that works, please post it here so others may benefit. Best of luck. Cheers

joey

**Comment by lfaller** [comment]
Thanks for the pointers, Joey! I'll take a look at ggtree :-)
