### ISSUE TITLE
Error of import_usearch_uc() in phyloseq

### ISSUE THREAD

**Issue by Kaydonuts** [joey711/phyloseq#570]
I have a question about phyloseq.

When I did phyloseq using R, I had a following error.

#Importing Data - UPARSE
OTU = import_usearch_uc("map.uc")

Error in base::table(...) : attempt to make a table with >= 2^31 elements

The file size of "map.uc" is 216 MB. 
How can I fix this error?

Thank you in advance,

**Comment by joey711** [comment]
Hi @Kaydonuts 

What you see is an error that reveals on old version of R, a 32-bit implementation of R, and/or a version of R installed on a system with limited RAM.

The `2^31 - 1` limitation on vector index length was removed as of R version 3.0.0. 

See the following for more details:
https://cran.r-project.org/bin/windows/base/old/3.0.0/NEWS.R-3.0.0.html

"There is a subtle change in behaviour for numeric index values `2^31` and larger. These never used to be legitimate and so were treated as NA, sometimes with a warning. They are now legal for long vectors so there is no longer a warning, and `x[2^31] <- y` will now extend the vector on a 64-bit platform and give an error on a 32-bit one."

Upgrading your version of R, and ensuring that you've installed it as 64-bit will alleviate this limitation. If you have a 32-bit processor, you are unlikely to be able to handle data of this size, or with this architecture. Most cloud computing rental services like AWS support 64-bit systems, almost predominately at this point, as I understand. So that is an option if you do not want to purchase an upgraded computer.

Cheers and best!

joey
