### ISSUE TITLE
Determining if alpha diversities are statistically significantly different

### ISSUE THREAD

**Issue by lfaller** [joey711/phyloseq#578]
Hi all,

I am trying to compare alpha diversities for my dataset and was able to plot the data as follows:

```rsplus
plot_richness(mydata, x="condition", measures=c("Shannon"))
```
I have four conditions and get one box plot for each -- looks good!

Now I would like to see if the means the box plots of two conditions are statistically significantly different.

Is there a way to do this in phyloseq? 

My current approach looks as follows (using the GlobalPatterns dataset):

```rsplus
data("GlobalPatterns")

plot_richness(GlobalPatterns, x = 'SampleType', measures = 'Shannon')

results = estimate_richness(GlobalPatterns, measures = 'Shannon')
d = sample_data(GlobalPatterns)

# calculate t-test
soil = results[d[,'SampleType'] == 'Soil',]
feces = results[d[,'SampleType'] == 'Feces',]
t.test(soil, feces)
```

Am I on the right track? Is there a better way to do this?

Thanks a bunch!
~Lina

**Comment by joey711** [comment]
Of course you have to determine if `t.test` or some other test (e.g. `wilcox.test`, etc) is most appropriate. Otherwise this is fine. phyloseq is not trying to wrap or re-code everything in R (nor would this be recommended or possible), but since the data is already "in" and available to an R session, you can now do this additional inference straight away. 

I leave it to you to double check that those collection of values are independent according to your data and the assumptions of the test. But the general concept/procedure of what you showed,  is correct; e.g. using phyloseq to grab a particular summary of your microbiome data, and then doing further specialized analysis on those values.

Hope that helps. Good luck!

joey

**Comment by lfaller** [comment]
Great, thanks for the feedback!
