### ISSUE TITLE
How to change the default sort order in plot_richness function?

### ISSUE THREAD

**Issue by lfaller** [joey711/phyloseq#579]
Hi all,

I generated a plot using **plot_richness** for four conditions.

Is there a way to reorder the four boxplots? Right now, it's **sorted alphabetically**, which is the default, according to the documentation:

_sortby -- (Optional). A character string subset of measures argument. Sort x-indices by the mean of one or more measures, if x-axis is mapped to a discrete variable. Default is NULL, implying that a discrete-value horizontal axis will use default sorting, usually alphabetic._

Is there a way to specify the order manually?

Thanks a bunch!
~Lina

**Comment by joey711** [comment]
Hi @lfaller this is not built-in to the `plot_richness` function, and no plans to add this to the function directly. Part of the reason is that this is already possible to do using `ggplot2`

See the following links for details (or ggplot2 doc):

- (1) [change order discrete scale](http://stackoverflow.com/questions/3253641/how-to-change-the-order-of-a-discrete-x-scale-in-ggplot)
- (2) [specific order discrete scale](http://stackoverflow.com/questions/12774210/how-do-you-specifically-order-ggplot2-x-axis-instead-of-alphabetical-order)

## MRE


```S
library("phyloseq"); packageVersion("phyloseq")
```

```
## [1] '1.15.2'
```

```S
data("GlobalPatterns")
p = plot_richness(GlobalPatterns, 
                  x="SampleType", 
                  measures=c("Chao1", "ACE", "InvSimpson"), 
                  nrow=3, 
                  sortby = "Chao1")
p
```

![unnamed-chunk-1-1](https://cloud.githubusercontent.com/assets/841437/13182934/29f560c4-d6e9-11e5-8a1a-dd31739491ec.png)

Define new order of variables manually.


```S
newSTorder = c("Sediment (estuary)", "Soil", "Freshwater (creek)", 
               "Feces", "Tongue", "Skin", "Mock",
               "Ocean", "Freshwater")
```

Turn your x-axis variable into a character vector,
then turn it back into an ordered factor with the new order
(define in the variable, `newSTorder`).


```S
p$data$SampleType <- as.character(p$data$SampleType)
p$data$SampleType <- factor(p$data$SampleType, levels=newSTorder)
print(p)
```

![](Issue-579_files/figure-html/unnamed-chunk-3-1.png) 

![unnamed-chunk-3-1](https://cloud.githubusercontent.com/assets/841437/13182944/38e9fb8a-d6e9-11e5-8db3-9625a08e580b.png)

**Comment by lfaller** [comment]
Thanks for the detailed advice, I was able to adapt your example to my data!
