### ISSUE TITLE
How to group all "unknowns" in one unknown category

### ISSUE THREAD

**Issue by SWJohnson** [joey711/phyloseq#581]
Hello, I am fairly new to phyloseq and I am trying to make a bar graph with my data at the Class level.  I made a bar graph at the Kingdom level by removing all "Unclassified" and "Unknown" data at the Kingdom level, and only included known data.  Now I am want to plot a bar graph at the Class level but instead removing the unknowns at the Class level, I want to group all the Unknowns (different OTUs) into one bar.  So in the end I would like to have all the individual bars from all the known OTUs and one big bar for all the unknowns (possibly at the top of the graph).  Is there a way for me to do this?

**Comment by joey711** [comment]
It sounds like you have two separate issues.

## (1) How to make a specialized plot like the one you're imagining.

Google ggplot2 examples, the ggplot2 website, and gain a little bit of understanding about how this works. Its easier in many ways than basic graphics in R, and harder in others. Don't be scared. There are tons of examples online, including phyloseq-specific examples. So the answer to your main question is, *yes, there is a way*. Actually many ways. Some of the simpler alternatives are shown in the following tutorial:

### [Restroom Biogeography Tutorial](http://joey711.github.io/phyloseq-demo/Restroom-Biogeography)

But again, how you are hoping to show the data might differ, and you might be able to add small modifications to the plot object produced by phyloseq to get what you want without remaking the graphic from scratch.

## (2) Unclassified Domains, how to deal. 

The second major question implied by your post involves *how to deal with unclassified taxa at high taxonomic ranks like Domain or Phylum*.

**Answer:** You should probably remove these from your data. If you blast the (consensus) sequence of these against nr it will probably match to known DNA that was not an intended target of your primers. Or they are novel chimeras. There is a vanishing possibility these represent completely new and undescribed domains that are not identifiable based on current taxonomic reference data, but after positive matches to off-target sequences in public databases you will reject this hypothesis (and you might reject it anyway based on knowledge of your experimental design, procedures, biological context, etc.). In general, for other users wondering about this, you should probably remove these high-rank-unclassifiable sequences from your data.

**Comment by SWJohnson** [comment]
Thank you for replying but I don't think Ive explain my problem very well.  I've already made my bar graphs at the phylum level and I've already removed all unclassified data at the kingdom level, all unknown data at the phylum level and all mitochondrial and chloroplast data.  So the bar graph I made at the kingdom level was with only filtered data.

Now I want to go further and make bar graphs at the class, order, family, genus and species level.  The difference here is that I dont want to remove the unknowns at these lower more specific level.  Instead I want to group all these unknowns at these specific levels into one big bar at the top of my bar graph.  So for example, at the genus level, I'd have all the bar of the known organisms and one bar at the top grouping all the unknowns.

I know how to make the graph, I just dont know how to group the unknowns together because they all have different OTUs.  This is the code I used at the kingdom level:
phy <- transform_sample_counts(bac_merged, function(x) 100 * x/sum(x))
###agglomerate taxa
glom_taxa <- tax_glom(phy, taxrank = "Phylum")
###create dataframe from phyloseq object
dat_taxa <- data.table(psmelt(glom_taxa))
###convert Phylum to character vector from a factor 
dat_taxa$Phylum <- as.character(dat_taxa$Phylum)
###group dataframe by Phylum, calculate median rel. abundance
medians <- dat_taxa[, median := median(Abundance, na.rm = TRUE), by = "Phylum"]
###change name of phyla whose rel. abundance is less than 5%
remainder <- dat_taxa[(median <= 0.05), Phylum := "Remainder < 5%"]
#set color palette to accommodate the number of genera
library(RColorBrewer) 
library(colorRamps) 
colourCount = length(unique(dat_taxa$Phylum))
getPalette = colorRampPalette(brewer.pal(9, "Set1"))
#barplot
w <- ggplot(dat_taxa, aes(x=X.SampleID, y=Abundance, fill=Phylum, order=as.factor(Phylum)))
w <- w + geom_bar(aes(), stat="identity", position="stack") + scale_fill_manual(values=getPalette(colourCount)) + theme(legend.position="bottom") + guides(fill=guide_legend(nrow=5))
w
Now this code made all data (filtered data) less than 5% be placed into a bar.  How do I do the same thing (without the less than 5% part) for the unknowns at say genus or species levels

**Comment by SWJohnson** [comment]
Could you please reopen issue 581? Thank you


*Shanay Williams-JohnsonMSc. Biology Candidate*

Vale Living with Lakes Centre,
Laurentian University,
935 Ramsey Lake Road,
Sudbury, ON. P3E 2C6 CANADA
(705) 675-1151 ext 3107





On Thu, Feb 18, 2016 at 12:20 PM, Paul J. McMurdie <notifications@github.com

**Comment by joey711** [comment]
Considering the scale is relative abundance, each position in each of these plots would sum to 1 (or 100%), and so the missing space already represents the information you're trying to describe, and in a more intuitive manner.

I don't think it is better or easier to try and modify a phyloseq object to include a "fake" OTU that represents all uncharacterized taxa at a specific level. However, you can accomplish this by making a separate phyloseq object for each of the ranks that you want to plot. Within each of these, you can change the `NA` taxonomic assignment to a dummy identifier of your choice, and then use `tax_glom` to agglomerate at that level. You would want to do this separately at each rank, not in succession, as agglomerated data is not easily reverted and there can be inconsistencies between ranks, etc.

You didn't show the plot in your post with the code, but you apparently know how to do this with Phylum. There is no technical barrier to doing this with other taxonomic ranks.

Alternatively, since you appear to know how to use ggplot2, you can use the `psmelt` function to transform the phyloseq data into a data.frame that ggplot2 can interpret straight away, or you can modify the dataset that is embedded in the plot object returned by `plot_bar`. In your example, you would find this in `w$data`.

There is no ready-made plot function that does exactly what you want, but you are close and have many options at your disposal.

Side note:

You mentioned at the end "group them first in the phyloseq file". There is no such thing. All of this is happening in-memory, in a formal definition of a microbiome experiment called a *phyloseq object*, or *instance of the phyloseq-class*. You can make copies and modifications of these interactively in your R session, and `tax_glom` appears to be the way you'll probably end up doing this. Also note that you might have to modify one of the components of your original phyloseq object or its derivatives for each taxonomic rank by using the `tax_table() <-` compound expression, or accessing the taxonomy table with `tax_table()`, saving it to a variable, modifying the rank in question, and re-assigning back to the phyloseq object prior to what you want to do.

I'm not going to re-open unless there's a deficiency, bug, feature request, or clear problem to solve. What you're asking for so far is special variant of something phyloseq already does, that you can accomplish in multiple different ways with just a little more effort, or borrowing code from the tutorial I've already linked.

Best of luck!

**Comment by SWJohnson** [comment]
Thank you

**Comment by weekend89** [comment]
For anyone who run into the same problem, I converted my phyloseq object to a data.frame and made my plots in ggplot2 instead of phyloseq and it worked.  

#find percent abundance of phyloseq object
obj2 <- transform_sample_counts(obj1, function(x) 100 * x/sum(x))
#melt the phyloseq object with psmelt
obj3 <- psmelt(obj2)
#rename NA's in Class level to "Unknown"
obj3$Class[is.na(obj3$Class)]="Unknown"
#make data a data.frame
obj4 <- data.frame(obj3)

class <- ggplot(obj4, aes(x=Sample, y=Abundance, fill=Class, order=as.factor(Class)))
class <- class + geom_bar()
class <- class + theme()
class

**Comment by Gian77** [comment]
Hello,
I tried to change all the `NA, "", " ", "\t"` that were present in my `tax_table` to `"Unclassified"`, but `tax_gplom` still doesn't display them on my output. From the function documentation that should not be the right behaviour, I  do not know why is happening. Please look at the code below. Thank you for helping, 
Gian

`> library(ggplot2)`
`> head(tax_table(biom_ITS_uparse_pop_df))`

>Taxonomy Table:     [6 taxa by 7 taxonomic ranks]:
         Kingdom Phylum          Class                              Order              Family              Genus            Species          
FOTU_2   "Fungi" "Basidiomycota" "Wallemiomycetes"                  "Geminibasidiales" "Geminibasidiaceae" "Geminibasidium" NA               
FOTU_1   "Fungi" "Ascomycota"    "Pezizomycetes"                    "Pezizales"        "Tuberaceae"        "Tuber"          NA               
FOTU_95  "Fungi" NA              NA                                 NA                 NA                  NA               NA               
FOTU_105 "Fungi" "Rozellomycota" "Rozellomycota_cls_Incertae_sedis" "GS07"             NA                  NA               NA               
FOTU_6   "Fungi" "Ascomycota"    "Sordariomycetes"                  "Hypocreales"      "Nectriaceae"       "Fusarium"       "Fusarium_solani"
"FOTU_144 "Fungi" "Rozellomycota" "Rozellomycota_cls_Incertae_sedis" "GS11"             NA                  NA               NA 

`> tax_table(biom_ITS_uparse_pop_df)[is.na(tax_table(biom_ITS_uparse_pop_df))] <- "Unlcassified"`
`> head(tax_table(biom_ITS_uparse_pop_df))`

>Taxonomy Table:     [6 taxa by 7 taxonomic ranks]:
         Kingdom Phylum          Class                              Order              Family              Genus            Species          
FOTU_2   "Fungi" "Basidiomycota" "Wallemiomycetes"                  "Geminibasidiales" "Geminibasidiaceae" "Geminibasidium" "Unlcassified"   
FOTU_1   "Fungi" "Ascomycota"    "Pezizomycetes"                    "Pezizales"        "Tuberaceae"        "Tuber"          "Unlcassified"   
FOTU_95  "Fungi" "Unlcassified"  "Unlcassified"                     "Unlcassified"     "Unlcassified"      "Unlcassified"   "Unlcassified"   
FOTU_105 "Fungi" "Rozellomycota" "Rozellomycota_cls_Incertae_sedis" "GS07"             "Unlcassified"      "Unlcassified"   "Unlcassified"   
FOTU_6   "Fungi" "Ascomycota"    "Sordariomycetes"                  "Hypocreales"      "Nectriaceae"       "Fusarium"       "Fusarium_solani"
FOTU_144 "Fungi" "Rozellomycota" "Rozellomycota_cls_Incertae_sedis" "GS11"             "Unlcassified"      "Unlcassified"   "Unlcassified"`

`> biom_phyla = tax_glom(biom_ITS_uparse_pop_df_gn, "Phylum")`
`> tax_table(biom_phyla)`

>Taxonomy Table:     [11 taxa by 7 taxonomic ranks]:
          Kingdom Phylum                   Class Order Family Genus Species
FOTU_2    "Fungi" "Basidiomycota"          NA    NA    NA     NA    NA     
FOTU_3    "Fungi" "Mucoromycota"           NA    NA    NA     NA    NA     
FOTU_71   "Fungi" "Ascomycota"             NA    NA    NA     NA    NA     
FOTU_7    "Fungi" "Mortierellomycota"      NA    NA    NA     NA    NA     
FOTU_547  "Fungi" "Calcarisporiellomycota" NA    NA    NA     NA    NA     
FOTU_344  "Fungi" "Glomeromycota"          NA    NA    NA     NA    NA     
FOTU_392  "Fungi" "Olpidiomycota"          NA    NA    NA     NA    NA     
FOTU_1295 "Fungi" "Kickxellomycota"        NA    NA    NA     NA    NA     
FOTU_146  "Fungi" "Chytridiomycota"        NA    NA    NA     NA    NA     
FOTU_977  "Fungi" "Zoopagomycota"          NA    NA    NA     NA    NA     
FOTU_438  "Fungi" "Blastocladiomycota"     NA    NA    NA     NA    NA

**Comment by grabear** [comment]
Try messing with [metacoder](https://github.com/grunwaldlab/metacoder/blob/master/scratch/issue_141--phyloseq_converter.Rmd).  @Gian77
