### ISSUE TITLE
Outlier dots in wrong spot when using the color option in plot_richness

### ISSUE THREAD

**Issue by lfaller** [joey711/phyloseq#584]
Hi all,

I am using the `plot_richness` function to group my data by one variable and then color it by another. Unfortunately, the outlier dots seem to be duplicated: they are plotted once on their own vertical line and once more on the middle one. Both of these variables are factors. Is there a way to keep all the red dots with the red boxplot and the blue dots with the blue boxplot?

This is my code:

``` rsplus
plot_richness(physeq, x = "direction", color = 'v_region', measures = "Shannon", title = "Alpha diversity of samples by direction colored by direction") + geom_boxplot()
```

Any thoughts on how to fix this would be appreciated!

![screen shot 2016-03-02 at 1 55 51 pm](https://cloud.githubusercontent.com/assets/7854149/13471554/08675aa8-e07f-11e5-9dca-64e01de9fc89.png)

**Comment by lfaller** [comment]
If anyone has any suggestions, I'd be very interested in hearing more!

Best,
~Lina

**Comment by joey711** [comment]
Its more complicated than that. For example, some blue points are shown only in the middle, but not with the blue box, even though some blue points are with the blue box. 

Can you post an MRE? It will help tremendously with diagnosing this.

**Comment by lfaller** [comment]
That's a fair request :-)

This is a bit contrived but hopefully a start:

```
library("phyloseq")
library("ggplot2")

data("GlobalPatterns")

sample_data(GlobalPatterns)$category <- c(rep('earth',3), rep('human',7), rep('water',8), rep('earth',3), rep('human',2), rep('artificial',3))
plot_richness(GlobalPatterns, x = "category", color='SampleType', measures = "Shannon") + geom_boxplot()
```

![screen shot 2016-03-30 at 4 21 09 pm](https://cloud.githubusercontent.com/assets/7854149/14156287/a0b8f616-f693-11e5-8bfe-1f91adf80198.png)

Thanks for taking a look at this!

**Comment by joey711** [comment]
Actually, this is an issue with *ggplot2*, and not *phyloseq*.

The reason for the problem is that the boxplot geom *dodges* differently than the points. 
To fix this you can set the position argument for points to dodge, 
and hope that they dodge in the same place.
I found a dodge-width value that works for my example, 
but I don't know if it is universal.

Thanks for your MRE. Here is a simpler one using only ggplot2,
to demonstrate that the phenomenon also occurs in plain vanilla ggplot2
(and thereby defend the honor of phyloseq  O:-).


```S
library("ggplot2"); packageVersion("ggplot2")
```

```
## [1] '2.1.0'
```

## Reproduce the problem


```S
p = ggplot(data = mtcars, 
           mapping = aes(x = factor(cyl),
                         y = mpg, 
                         color = factor(carb))) + 
  geom_boxplot()
p + geom_point()
```

![unnamed-chunk-2-1](https://cloud.githubusercontent.com/assets/841437/14193673/bae66aa0-f75b-11e5-8842-2d8cb1816e90.png)


## Fix the problem

For some reason `position = position_dodge(width = 0.75)` 
seems to be the magic `width` value.


```S
p + geom_point(position = position_dodge(width = 0.75))
```

![unnamed-chunk-3-1](https://cloud.githubusercontent.com/assets/841437/14193678/c3a2597e-f75b-11e5-9fc1-5603c12fdf76.png)

## Resolved.

I will close for now. Thanks for posting. I hope this helps!

**Comment by lfaller** [comment]
Great, thanks so much for helping diagnose this!

Best,
~Lina
