### ISSUE TITLE
Issue with Ordinate or Bray/Jaccard Curtis Distance

### ISSUE THREAD

**Issue by jsilve24** [joey711/phyloseq#594]
Hi all, 
I am getting an issue when trying to calculate PCoA results from bray (or jaccard) distance matrices. I am not sure if the issue rests with the ordination or the calculation of the distance matrices themselves. 

Everything works fine for small datasets, but I have been trying to run this analysis on a somewhat paired down version of the HMP dataset. (I am sorry, I have trouble reproducing the problem on smaller datasets). 

I saw this issue and thought it might be related: https://github.com/joey711/phyloseq/issues/344
I have also seen this issue and do not believe it is related: https://github.com/joey711/phyloseq/issues/572

The necessary files to reproduce the error are in my dropbox [here](https://dl.dropboxusercontent.com/u/4314134/distance_issue_hmp_small.zip). 

In short, I precompute the bray-curtis distance (warning: this takes a number of hours). 
> library(phyloseq); packageVersion("phyloseq")
[1] ‘1.14.0’
> set.seed(4)
>
> DATA <- get(load(HMP.RData))
> DATA <- transform_sample_counts(DATA, function(x) x/sum(x))
> dist <- distance(DATA, method = 'bray')
> save(dist, file='dist/bray_dist.RData')

Where 'DATA' is the HMP_small dataset in the file HMP.RData
If I then take that precomputed distance matrix(included as bray_dist.RData) and run 

> load('HMP.RData')
> load('bray_dist.RData)
> pcoa  <- ordinate(HMP_small, 'PCoA', distance = dist)

then I get the following error:

> Error in data.frame(eig[1:k], rel.eig, rel.eig.cor, bs, cum.eig.cor, cum.bs) : 
  arguments imply differing number of rows: 4358, 4360
> In addition: Warning message:
In sqrt(eig[1:k2]) : NaNs produced

I have looked over the OTU table but I have not found anything obvious (like NaN or negative values). 
Note: While I include files and code for this issue with the bray curtis distance, I have the exact same problem with the Jaccard distance/index. Which leads me to believe that there might be an issue with the vegdist method, but that it only occurs with this dataset makes me wonder if its an issue with ordination... I really am not sure, thank you again for the help. 

Thanks!

**Comment by jsilve24** [comment]
Reading a little I wonder if the issue has to do with negative eigenvalues produced by non-metric distances (it sounds like the bray-curtis is such a non-metric distance). A very cursory search produced http://www.inside-r.org/packages/cran/ape/docs/pcoa - the ape package seems to handle this with a few interesting methods.

**Comment by michberr** [comment]
Whoa, ghosts of github issues past! Sorry about never following up on #344 @joey711  . . . i think i was trying to graduate or something :). Maybe i will investigate that issue again this afternoon. 

@jsilve24 I loaded in your data from the dropbox. Upon first inspection, HMP_small contains 4358 samples and dist has 4358 "dimensions". dim(as.matrix(dist)) yields [4358,4358]. However, i get the same error as you when i call ordinate()

Phyloseq's ordinate function is actually a wrapper for the pcoa function in ape (among other ordination methods from other packages). Therefore, when you call ordinate(method = "PCoA") you are really calling the ape `pcoa` function. I looked through the `pcoa` source code, and you're right, this error is being produced because of negative eigenvalues. The "NANs" are produced when trying to take the square root of a matrix that still contains negative values. This is surprising to me, because i've worked with plenty of datasets in phyloseq that produce negative eigenvalues when calculating pcoa scores from a bray-curtis distance matrix. This has never led to an error like the one you got. 

Upon closer inspection, this is where the bug is in the `pcoa` function:
```{}
k2 <- length(which(eig > epsilon))
vectors <- sweep(D.eig$vectors[, 1:k2], 2, sqrt(eig[1:k2]), FUN = "*")
```

The way that the `pcoa` function is written, it assumes that any negative eigenvectors will come after all the positive eigenvectors. So rather than passing in the indexes of `which(eig > epsilon)` it just passes in 1:k2. Now, mathematically i don't know what's going on here i.e. why you are getting negative eigenvectors before positive eigenvectors. Maybe @spholmes knows. This seems like a bug worth reporting to ape though.

**Comment by joey711** [comment]
Bray-Curtis is a semi-metric distance, which means it can violate the triangle inequality. This is a possible explanation. If you're not trying to make an inference on all 4000+ samples simultaneously, you might consider splitting this into pieces according to the design and your hypotheses. This might alleviate the worst of the deviations from metric. You can also try an alternate ordination method. If you have the computing power, NMDS might be the next most reasonably alternative. You'll need to make a choice regarding the number of dimensions, so anything you know already or learned from the MDS attempt regarding dimensionality would help.

Hope these are helpful suggestions.

I'll leave this open for a little while longer to encourage other comments and troubleshooting.

**Comment by michberr** [comment]
It's not surprising that negative eigenvalues are produced. This is almost always the case with Bray-Curtis, for the reason @joey711 mentioned above, and this usually doesn't produce an error with the `ordinate` or ape `pcoa` command. 

What's strange here is that some of the principal coordinates associated with negative eigenvalues appear before some of the coordinates with positive eigenvalues when you make the `pcoa` call to the hmp dataset. I thought by definition, principal coordinates were ordered from highest to lowest eigenvalue (highest to lowest variance when points are projected onto the coordinate)?

**Comment by michaelgreenacre** [comment]
Those on this thread might find my recent **Ecology in R** conference paper interesting: "Why I don't use Bray-Curtis in multivariate analysis of ecological data". It's on YouTube at youtube.com/CARMEnetwork, or the direct link to the video is:
https://www.youtube.com/watch?v=c7VUrViGmQU
