### ISSUE TITLE
Same colors - species in two bar_plots

### ISSUE THREAD

**Issue by maculatus** [joey711/phyloseq#595]
How I can keep the same colors for the same species in two plot_bars?

**Comment by jeffkimbrel** [comment]
Here's how I do it. Assuming you have a phyloseq object called `phyloObject`, you can build a custom color palette based on `species` or any other level of taxa (even `OTU`).

```
library("RColorBrewer")
getPalette = colorRampPalette(brewer.pal(9, "Set1"))

speciesList = unique(tax_table(phyloObject)[,"species"])
speciesPalette = getPalette(length(speciesList))
names(speciesPalette) = speciesList
```

Then, add either of these lines depending on if you need to edit the `fill` or the `color`:

```
scale_color_manual(values=speciesPalette)
scale_fill_manual(values= speciesPalette)
```

**Comment by maculatus** [comment]
Thank!  I will need to play a bit with the number of colors (35) but this is an improvement. I will close the question.

**Comment by joey711** [comment]
Nice Q & A!

**Comment by jeffkimbrel** [comment]
Great! Just to really drive it home, you can pick any color palette you like (check out the bottom of [this link](http://www.cookbook-r.com/Graphs/Colors_(ggplot2)/).

Also, you can manually edit the color palette that you make. For example, if you want to really highlight a single species in a bar plot, you can make a color palette based on "greys". Then, manually edit the color palette to change the one species to "red" or something to make it stand out more.

Lastly, the color palette can be used elsewhere, so you can have unified colors across `phyloseq`, `igraph`, `ggplot`, or anything else you might need a shared color palette.

**Comment by maculatus** [comment]
Thanks again. The link is perfect and I have the graph with colors that are different among the taxa and the same for each taxon across different graphics. It is consistent even when some of the taxon are not present.

**Comment by kelvinfrog** [comment]
Regarding to my question at #605, I follow this example and have these codes at the end. But still cannot have the same family group together. 

```
library("RColorBrewer")
getPalette = colorRampPalette(brewer.pal(9, "Set1"))
familyList = unique(tax_table(physeq)[,"Family"])
familyPalette = getPalette(length(familyList))
names(familyPalette) = familyList
plot_bar(physeq, fill = "Family") + scale_fill_manual(values= familyPalette)
```

**Comment by michberr** [comment]
@kelvinfrog If you want to visualize your data at the Family level instead of OTU, you need to use the `tax_glom` command with `taxrank = "Family"`. If you still want separate bars for OTUs, but you want them ordered by Family (all OTUs from the same family next to each other in the plot) I would follow the advice from #291 or #442 using the `psmelt` function to melt your phyloseq object into a long-format data.frame and then `dplyr::arrange` to sort your data.frame by Family.

**Comment by coyk** [comment]
I have tried to use the code from above to get the same color scheme across four bar plots and it does not work for me

library("RColorBrewer")
getPalette = colorRampPalette(brewer.pal(12, "Set3"))
ClassList = unique(tax_table(Bathy_ps1_exp_trim_rarefy)[,"Rank3"])
ClassPalette = getPalette(length(ClassList))
names(ClassPalette) = ClassList
Bps1trimrare.pro = subset_taxa(Bathy_ps1_exp_trim_rarefy, Rank2 == "Proteobacteria")
plot_bar(Bps1trimrare.pro, fill="Rank3")+ scale_fill_manual(values= ClassPalette)

Here, I am making bar plots of the classes (Rank 3) present within Proteobacteria across 4 different datasets.  The above is from one dataset.  I've tried 
getPalette = colorRampPalette(brewer.pal(9, "Set1"))
getPalette = colorRampPalette(brewer.pal(8, "Set2"))
getPalette = colorRampPalette(brewer.pal(12, "Set3"))

I've also tried 
plot_bar(Bps1trimrare.pro, fill="Rank3")+ scale_color_manual(values= ClassPalette)

I actually don't know the difference between scale_color_manual and scale_fill_manual.  Across all datasets, there are a total of 8 unique classes.  Three of the datasets are consistent with regard to color scheme, but one is different (that's the one I pasted above).  Also, some classes in two of the bar plots are coded as white.  In one bar plot, 3 classes are coded white, including a class that occurs in another dataset that has a color in that one.  I have NO IDEA what's going on.

**Comment by jeffkimbrel** [comment]
If you are making the color scheme from only one of four objects, is it possible that last object has unique "rank3" taxa that aren't in the object you built the palette from? Taxa not in the palette will show up as white in the plot. 

In 'ggplot2', "fill" and "color" can mean different things depending on the type of plot. For 'plot_bar', which calls 'geom_bar', "fill" is the interior of the bar, and "color" is the border line. Your last example didn't work because you set the "fill" according to "rank3",  but assigned the palette to the "color".

**Comment by coyk** [comment]
Thank you.  Thank you thank you thank you.  I redefined my Palette with the dataset that had the most categories in it.  I had been redefining it every time with every dataset.  My last plot has a single white category now, which is fine, because it is one and not visible anyway.  The last plot is a weirdo in that it doesn't have alot of the categories that the other plots have, but it does have this one unique category.  I'm sure at some point in the future I'll be up against this conundrum again and will want to know how to have all unique categories non-white, but not today!
Thank you!

**Comment by TesselLagerwerf** [comment]
This has been a very helpful post and I really appreciate it! I have got it working, but another problem has come up with my situation.

I want to make an abundance stack plot consisting out of 59 different classes. Via this question I have been able to create a colorpallete containing enough colors, but due to the fact that my OTU's are ordered alphabetically based on the species names, and not the class names, the colors seem to be all over the place. Here is what it looks like now:

![image](https://user-images.githubusercontent.com/35833676/45088449-50030f80-b109-11e8-8113-b69b3c22637d.png)

So I was wondering how do I get my phyloseq ordered alphabetically on class names ór how do I get the colors to be attached in alphabetical order? Cause now it just looks so chaotic that it is not really representable.
