### ISSUE TITLE
Creating phyloseq object from usearch v8 output files

### ISSUE THREAD

**Issue by nelsquash** [joey711/phyloseq#603]
Hi,
I would like to request your help in creating a phyloseq object for further analysis. This is the first time am getting to use phyloseq and am eager to see some plots and perform some analysis.
My project will have 700 16S samples but at the moment am currently trying to analyze  half of them.

I generated an otu table (otutab.txt) and biom files (otutab.json) using usearch version 8.
I also made a mapping file by hand for it to resemble the Qiime mapping file. I constructed a phylogenetic tree (rep_phylo.tre) using Qiime pynast tool.

I have gone through the usearch documentation but I dont seem to be able to create a phyloseq object - I bump into errors which I haven't managed to solve. As a last resort I tried one of the suggestions you had provided a while ago on a closed forum about using .uc file, however my file exceeds R 32-bit limits as I get a "Error in table(x$sample, x$OTU) :
  attempt to make a table with >= 2^31 elements" error.

I shall send you my files separately

What is the problem and how can I solve it in future when I have more data?
Many thanks for your help!

**Comment by CarlyRae** [comment]
I'll lend a suggestion as I also use Usearch to cluster my OTUs, and then QIIME to assign, align and make a tree and generate a .biom file from that. Then I bring those items into phyloseq. First, I think you need your .json file to be a .biom file but in json format. 

Using biom convert, example code is this

biom convert -i Ch3_final_1013.biom -o Ch3_final_1013_json.biom --to-json --table-type="OTU table" 

Then in phyloseq I bring each file in separately and then merge. 

### Rarified
biom_rare <-  import_biom("otu_tables/Ch3_final_1013_json.biom", parseFunction = parse_taxonomy_greengenes)

### get error message, but looks fine, adds a rank1 at the end for whatever reason
rank_names(biom_rare)

#### MAPPING FILE ####
map <- import_qiime_sample_data("Mapping_Ch3_final.txt")

#####  TREE FILE  #####
library(ape)
tree = read.tree("Ch3_all_final_rooted.tre")
is.rooted(tree)
## tree rooted using archaeal outgroup and pruning outgroup in another file

ch3 <- merge_phyloseq(biom_rare, tree, map)
ch3

**Comment by nelsquash** [comment]
Hi Carley,
Thanks for the suggestions. The biom convert gave the desired output. However, on attempting to import the biom file, I got an error:
 "Error in i$metadata$taxonomy : $ operator is invalid for atomic vectors"

When I tried the rank_names function on the biom_rare, I got the error:
 "Error in tax_table(physeq, errorIfNULL) : 
  error in evaluating the argument 'object' in selecting a method for function 'tax_table': Error: object 'biom_rare' not found

Importing the tree and the mapping file worked OK.

Consequently, when trying to merge the different components, an anticipated error was thrown:
"Error in merge_phyloseq(biom_rare, tree, map) : 
  object 'biom_rare' not found"

Perhaps am missing something if your usearch v8 generated biom file works. I could share my files if you would like to try.

Thanks!

**Comment by CarlyRae** [comment]
This may not be a phyloseq issue at all. The phyloseq folks might be better to point out what that error is indicating, but it seems like you don't have taxonomy metadata in your .biom file. 

It is likely something that you are doing incorrectly while working in Usearch or with the biom file in QIIME.  Here is my code for all that I do, which I edited from a post by Mike in the QIIME forum (https://groups.google.com/forum/#!topic/qiime-forum/zqmvpnZe26g). See if somewhere along these lines you are missing some code (again likely adding the taxonomy metadata to the .biom file. Probably the add taxonomy to biom file at the end of this code.

Good luck!

#####Uparse in Usearch
—enter terminal, and get into the folder where your files are by using cd

./usearch7.0.1001_i86osx32 -fastq_stats Ch3_all.fastq -log ch_3seqs_all.stats.log

02:00  36Mb  100.0% Reading Ch3_all.fastq
   1636799  Recs (1.6M), 0 too long      
     378.9  Avg length
    620.2M  Bases

16636799 reads with avg. length 378.9 after trimming

### First find out how many cores you have on your computer, you can then specify how many threads you can use at a time.

sysctl -n hw.ncpu

##I have 8 cores on my computer, so can run a job in each one of those cores by specifying -threads -8 in the command below

###### remove low quality reads (trimming not required for paired-end data)

./usearch7.0.1001_i86osx32 -fastq_filter Ch3_all.fastq -fastaout ch3.seqs.filtered.fasta -threads 8 -fastq_truncqual 15 -fastq_minlen 200



01:40 1.2Mb  100.0% Converting, 1.6M recs, 1499456 converted (91.6%) 
   1636799  FASTQ recs (1.6M)                                       
   1499456  Converted (1.5M, 91.6%)
   
    
############## dereplicate seqs ################# In other words cluster sequences and pick a representative sequence for each cluster

./usearch7.0.1001_i86osx32 -derep_fulllength ch3.seqs.filtered.fasta -fastaout ch3.seqs.filtered.derep.fasta -sizeout -threads 8


00:00 995.3kb Reading ch3.seqs.filtered.fasta, 575Mb
00:01 576Mb 1499456 (1.5M) seqs, min 200, avg 367, max 451nt
00:07 663Mb 565360 (565.4k) uniques, avg cluster 2.7, median 1, max 88253
00:22 663Mb  100.0% Writing ch3.seqs.filtered.derep.fasta



######### filter singletons — I think so they go to the bottom!! and then they are removed ##############
./usearch7.0.1001_i86osx32 -sortbysize ch3.seqs.filtered.derep.fasta -minsize 2 -output ch3.seqs.filtered.derep.ms2.fasta

00:00 1.0Mb Reading ch3.seqs.filtered.derep.fasta, 221Mb
00:03 222Mb 565360 (565.4k) seqs, min 200, avg 362, max 451nt
00:03 228Mb Getting sizes
00:05 229Mb Sorting 90147 sequences
00:07 230Mb  100.0% Writing ch3.seqs.filtered.derep.ms2.fasta


########### cluster OTUs (de novo chimera checking can not be disabled in usearch7) ###############

./usearch7.0.1001_i86osx32 -cluster_otus ch3.seqs.filtered.derep.ms2.fasta -otus ch3.seqs.filtered.derep.ms2.repset.fasta

01:10  63Mb  100.0% 3369 OTUs
                             
Input seqs  90147 (90.1k)
      OTUs  3369
   Members  81359 (81.4k)
  Chimeras  5419
   Max mem  63Mb
      Time  01:10
Throughput  1287.8 seqs/sec.




############# reference chimera check ################
./usearch7.0.1001_i86osx32 -uchime_ref ch3.seqs.filtered.derep.ms2.repset.fasta -db gold.fa -strand plus -nonchimeras ch3.seqs.filtered.derep.ms2.repset.nochimeras.fasta -threads 8

00:00 1.0Mb Reading ch3.seqs.filtered.derep.ms2.repset.fasta, 1.3Mb
00:00 2.3Mb 3369 seqs, min 201, avg 356, max 420nt
00:00 2.4Mb Reading gold.fa, 16Mb
00:00  18Mb 10362 (10.4k) seqs, min 1205, avg 1470, max 1655nt
00:01  19Mb  100.0% Masking
00:01  19Mb  100.0% Word stats
00:01  20Mb  100.0% Building slots
00:02  83Mb  100.0% Build index   
00:05 117Mb  100.0% Search 49/3369 chimeras found (1.5%)
00:05 117Mb  100.0% Writing 3320 non-chimeras  



########### label OTUs using UPARSE python script ########

For python scripts download from http://drive5.com/python/


python fasta_number.py ch3.seqs.filtered.derep.ms2.repset.nochimeras.fasta OTU_ > ch3.seqs.filtered.derep.ms2.repset.nochimeras.OTUs.fasta

######## map the _original_ quality filtered reads back to OTUs #############

./usearch7.0.1001_i86osx32 -usearch_global ch3.seqs.filtered.fasta -db ch3.seqs.filtered.derep.ms2.repset.nochimeras.OTUs.fasta -strand plus -id 0.97 -uc ch3.otu.map.uc -threads 8

00:00  18Mb Reading ch3.seqs.filtered.derep.ms2.repset.nochimeras.OTUs.fasta, 1.2Mb
00:00  19Mb 3316 seqs, min 201, avg 356, max 420nt
00:00  19Mb  100.0% Masking
00:00  19Mb  100.0% Word stats
00:00  20Mb  100.0% Building slots
00:00  26Mb  100.0% Build index   
00:47  33Mb  100.0% Searching, 92.8% matched


###MAKE OTU TABLE#######
##I think this is the one you have to modify the uc2otutab command, google search on qiime forum — Mike told me how to do this

python uc2otutab_mod.py ch3.otu.map.uc > ch3.seqs.filtered.derep.ms2.repset.nochimeras.OTU-table.txt


#####   GO INTO QIIME  #####
# convert to biom

biom convert -i ch3.seqs.filtered.derep.ms2.repset.nochimeras.OTU-table.txt -o ch3.seqs.filtered.derep.ms2.repset.nochimeras.OTU-table.biom --table-type="otu table" 

##### assign taxonomy 

####Move green gene files to the folder you are working in. Most people use the 97% assign 

parallel_assign_taxonomy_rdp.py  -t 97_otu_taxonomy.txt -r 97_otus.fasta -i ch3.seqs.filtered.derep.ms2.repset.nochimeras.OTUs.fasta -o assigned_taxonomy


Now I needed to download stuff to install BIOM format commands

to get python to run 

/usr/bin/env python

doesn't work command + d to quit

go to http://biom-format.org/

and download the latest version of biom, then cd into the folder and run sudo python setup.py install
put in your password and should work

# add taxonomy to BIOM table

biom add-metadata --sc-separated taxonomy --observation-header OTUID,taxonomy --observation-metadata-fp assigned_taxonomy/ch3.seqs.filtered.derep.ms2.repset.nochimeras.OTUs_tax_assignments.txt -i ch3.seqs.filtered.derep.ms2.repset.nochimeras.OTU-table.biom -o Ch3_all_w-neg_final.biom


###I want to look at it so converting to .txt
biom convert -i Ch3_all_w-neg_final.biom -o Ch3_all_w-neg_final.txt --to-tsv --header-key taxonomy



##########ALIGN AND MAKE PHYLOGENETIC TREE#######
ch3.seqs.filtered.derep.ms2.repset.nochimeras.OTUs.fasta  — moved this file over to work with — this is what I need to align 

added an archaeal sequence to the fasta file (Pyrodictium occultum; GenBank accession #M21087) I obtained the accession number by going through green genes and chose a Crenarchaeota sp.  I trimmed 400 bp from the beginning and end of the full sequence, probably doesn’t matter for aligning, but did it anyway. I had to save as a .txt file and then just rename the file .fasta

seqs.filtered.derep.ms2.repset.nochimeras.OTUs.archaea.fasta is now the file I need
  
4) Aligning the representative sequence set (align_seqs.py)

align_seqs.py -i ch3.seqs.filtered.derep.ms2.repset.nochimeras.OTUs.archaea.fasta -o pynast_aligned/


##pynast_aligned  and filtered_alignment folder from before does not have the archaeal sequence
   
   7) Filtering the alignment prior to tree building - removing positions which are all gaps, or not useful for phylogenetic inference (for more information,     refer to filter_alignment.py)

filter_alignment.py -i pynast_aligned/ch3.seqs.filtered.derep.ms2.repset.nochimeras.OTUs.archaea_aligned.fasta -o filtered_alignment/

  
8) Building a phylogenetic tree (for more information, refer to make_phylogeny.py)

make_phylogeny.py -i filtered_alignment/ch3.seqs.filtered.derep.ms2.repset.nochimeras.OTUs.archaea_aligned_pfiltered.fasta -o Ch3_all_archaea.tre


## Convert biom to get into phyloseq
biom convert -i Ch3_all_w-neg_final.biom -o Ch3_all_w-neg_final_json.biom --to-json --table-type="OTU table" 

#### Single rarefaction

single_rarefaction.py -i Ch3_all_w-neg_final_json.biom -o ch3_final_1013.biom -d 1013

### Convert all to json to use in phyloseq

biom convert -i ch3_final_1013.biom -o ch3_final_1013_json.biom --to-json --table-type="OTU table"

**Comment by nelsquash** [comment]
You were right Carly, It wasn't a phyloseq issue per se. I had missed to add taxonomy to the Biom table and single rarefaction steps. They seemed to fix the problem and I now I have a phyloseq object - yet to add mapping file, but in summary it worked. Thanks very much!

**Comment by CarlyRae** [comment]
Great, glad to hear it helped. Also, note that the work of the phyloseq group showing that rarefaction should not really be done when looking at abundance of bacteria. Please anyone correct me if I'm incorrect with this, but the publication (http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003531) points to only abundance as far as I can tell. So, I do rarefaction for my analyses for alpha -and beta- diversity and then use the unrarefied biom file to examine changes in abundance of bacteria (I use css-normalized counts I get from package MetagenomeSeq to use as my response for each bacterial OTU of interest). Good luck!

**Comment by spholmes** [comment]
Carly
I believe you have a typo, our normalizations are relevant to differential
bacterial adundances,
but the diversity issues are still unresolved, the current pipeline for
diversity suffers from
a lot of errors in the output from the standard OTU methods and we now
recommend the DADA2
methods which fix a lot of these.

Susan

On Thu, Apr 28, 2016 at 6:59 AM, Carly Muletz Wolz <notifications@github.com
> wrote:

> Great, glad to hear it helped. Also, note that the work of the phyloseq
> group showing that rarefaction should not really be done when looking at
> abundance of bacteria. Please anyone correct me if I'm incorrect with this,
> but the publication (
> http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003531)
> points to only abundance as far as I can tell. So, I do rarefaction for my
> analyses for alpha -and beta- diversity and then use the unrarefied biom
> file to examine changes in abundance of bacteria (I use css-normalized
> counts I get from package MetagenomeSeq to use as my response for each
> bacterial OTU of interest). Good luck!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joey711/phyloseq/issues/603#issuecomment-215432123>
>



-- 
Susan Holmes
Professor, Statistics and BioX
John Henry Samter Fellow in Undergraduate Education
Sequoia Hall,
390 Serra Mall
Stanford, CA 94305
http://www-stat.stanford.edu/~susan/

**Comment by joey711** [comment]
# 2^31 length error

This has not been a limitation for a long time. As of R version 3.0.0 and greater, vector length limits are well beyond 2^31-1.

See [this post on R memory limits](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Memory-limits.html) for more details.

Point being, **you should update your version of R**.

# You should not rarefy your data. Ever.

Also @CarlyRae @nelsquash we strongly recommend **against** the `single_rarefaction.py` method that you suggested, and that is typical in QIIME workflows. The name itself is a misnomer, as rarefaction cannot be accomplished with one resampling, and was never recommended this way, not originally, and not since. This is why we coined the also-pervasive synonym, *rarefying*, to name what `single_rarefaction.py` is doing. There is no mathematical underpinning to rarefying, and a host of statistical drawbacks to doing so, and so we recommend against it on these grounds.

Please see the [Waste Not Want Not...](http://dx.doi.org/10.1371/journal.pcbi.1003531) article for the more formal explanation.

There is **absolutely no requirement in phyloseq to rarefy you data prior to import**, so even adding that step here is off-topic.

# HDF5 biom files now supported by phyloseq

Also, the latest release version of phyloseq, published yesterday on the new site-wide release of BioConductor, has migrated to [the biomformat package](https://www.bioconductor.org/packages/release/bioc/html/biomformat.html), which can handle the new HDF5 version of the biom file output from QIIME.

With respect to this tangential issue and the OP issue, see [the phyloseq FAQ](https://bioconductor.org/packages/release/bioc/vignettes/phyloseq/inst/doc/phyloseq-FAQ.html) for more related details. 

# Import from usearch is well supported in phyloseq

## Importing usearch output

WRT the OP, phyloseq has included a function for importing from usearch output for a long time, `import_usearch_uc`. 

See its doc, and maybe also [Issue 573](https://github.com/joey711/phyloseq/issues/573)

## Importing UPARSE output

If you used usearch's `cluster_otus` option, then you were using UPARSE.
The phyloseq package supports a UPARSE-specific output file format
that is generated when you use 
[the -uparseout option](http://www.drive5.com/usearch/manual/opt_uparseout.html).

The command in phyloseq is, predictably, `import_uparse`.

**Comment by CarlyRae** [comment]
Thank you for the feedback @spholmes and @joey711 

From my understanding and many times reading the 'waste not, want not...." you have demonstrated that 'rarefying' when looking at differential abundance (yes, @spholmes my word choice was incorrect above) among groups is statistically problematic. I have not seen any publications on examining alpha-diversity or beta-diversity (specifically when just examining presence/absence metrics). Please correct me if I am wrong. 

The problem I have is there is a long standing 'traditional' of standardizing sampling depth in community ecology literature. Making sure you sample the same amount of time, the same size of area, etc. to examine patterns in alpha and beta diversity. Therefore, it does have some backing to standardize your sampling efforts when examining communities in general because if you sample one community more it can look different than another community due to sampling depth alone. Again, I have not seen any examining how differences in sampling depth effect alpha and beta diversity. My conclusion is without that demonstration, stating to never rarefy ever is not backed up with data. I appreciate the work you all are doing and I would be more than happy to proceed with all my analyses without rarefying to equal sampling depth (or normalizing or single rarefaction or whatever term we want to use), but it is commonly regarded that uneven sampling effort can lead to bias.

I use Usearch to decrease the number of spurious OTUs and that seems to help, but again I still 'rarefy' to equal sampling depth for alpha- and beta- (P/A) diversity analyses. I do not see how reducing spurious OTUs removes the concern have having different sequence counts among variables of interest (in regards to what @spholmes suggested above). Only 'rarefying' can remove that bias as far as I can see for now. I did not 'rarefy' when I examined differential abundance among groups. This is based on your 'waste not, want not...' publication. However, I am now having changes trying to correlate 'non-rarefied' sequence counts to a continuous variable (multiple temperatures), but there are more sequences per individual for the highest temperature. Therefore, I run into problems. I tried to take 'non-rarefied' counts and transform to relative abundance, but the statistical models do not perform as well. So, even in looking at abundance there are challenges that arise from the uneven sampling depth that rarefying can help in removing the bias of more sequencing coverage in a specific treatment. I realize that spurious results can occur due to 'rarefying', but that in some instances one might have to accept those problems so that they can remove the issue of sequence count being higher in one treatment causing a problem of OTUs 'appearing' to increase in that treatment. 

I am just not entirely convinced that you can make a blanket statement that you should never rarefy for any microbiome analyses; I am convinced about differential abundance testing among categorical variables. 

Again, thank you for all of your work.

**Comment by joey711** [comment]
@CarlyRae 

Thanks for your feedback. This is helpful to hear precise details about the confusion. I consider it a personal failure of mine that you could read "Waste Not, Want Not..." several times and come to the conclusion that rarefying is *okay* for alpha or beta diversity analyses. I suspect that this is wishful thinking derived from a preference to employ familiar methods, despite the fact that they are in this case inefficient at best, and inappropriate at worse. Where on this horrible spectrum from inefficient to inappropriate *rarefying* falls depends entirely on the specific dataset and what analysis methods are being applied afterward. For alpha diversity it is amazing to me that anyone familiar with ecology would ever even suggest *rarefying*, because alpha diversity is a measure that *(1)* is evaluated one sample at a time (so why would the read counts of other samples matter), and *(2)* produces estimates of richness (or evenness, etc.) that are much better as the library size gets larger. For some alpha measures the library size directly influences the confidence intervals. For beta diversity, how much library size differences matter depends on the distance measure chosen, and the distance measure should be chosen with the data source and behavior in mind. To this end, I did include an entire simulation and two figures to communicate precisely how rarefying can hurt a beta-diversity analysis, using various common normalization, distance methods, choices for *rarefying* library size min, and clustering techniques. In this simulation I used clustering accuracy as a quantitative measure of effectiveness of the procedures, and I thought it was pretty clear that *rarefying* was hurting the effectiveness of the analysis in which appeared. 

I should point out that I do not make general statements lightly. I think that would be a dangerous habit to become accustom. The reason I can state so generally that *rarefying* is a bad practice, is that *rarefying* contains a number of red flag steps that any statistician recognizes immediately as an inefficient use of the available valid data, while also introducing noise. There is an extensive background of mathematical and statistical theory behind such an assessment, theory which is generalizable. The simulations I showed in the article are simply a useful way of communicating this theory, in a way that equations usually fail when explaining to biologists.

To answer your reference to practices in ecology literature. There is a critical difference that I apparently failed to communicate in the article. There is a substantial difference between:

- (1) *marshaling resources toward even sampling*, and
- (2) *throwing away observations (data) after the fact*, as if it had been evenly sampled.

The reason this matters so strongly in the case of barcoded NGS data is that the sequencer provides differences in sequencing effort that is often 10X, or worse. Hamstringing the large libraries to a random downsampling at a depth equal to among the smallest libraries in the dataset is equivalent to throwing away a large amount of useful (e.g. non-artifact) data. *Rarefying* is categorically different than marshaling your observational resources through a carefully planned and executed experimental design, and if we had that capability with 2nd-gen sequencing I would join you in supporting even depth as a good design approach in most cases. Of course, there would also be exceptions where you might prefer a depth profile that is non-uniform based on prior knowledge of sample complexity, etc., but this point is moot until we actually have something resembling control of library sizes in multiplexed DNA sequencing.

I hope that helps clarify. I strongly suggest that you give my article, and this issue, another careful consideration.

**Comment by CarlyRae** [comment]
Thank you for the response. I attended a workshop with you all at SISMID in 2012 and was 'convinced' before the paper was published to not rarefy. I at that point had little experience with working with this data and was a new graduate student. When the paper was first published I was still convinced that rarefying should not be employed, because you present that it is admissible. Also, I have a committee member (part of MetagenomeSeq group) that agrees with the notion that rarefying is a problem. But, then as I started doing analyses and working with several different datasets to analyze I realized that it is not as straightforward as it seems to never rarefy, given in some cases extreme variation in sequencing depth among groups/treatments of interest. 

Now, I have four separate datasets that all present their own unique problems. First, if you have more sampling depth in a treatment or a group, on average the group can have higher alpha-diversity, simple as that. Yes, it is an individual based metric, but when you are saying do gorillas' microbiomes have higher alpha-diversity than chimpanzees' microbiomes, but the gorilla group by chance had on average 10x more sequencing coverage (almost all individuals) than chimpanzees you run into a problem. You can use rarefaction methods to examine this, but you still have the sequencing coverage problem. If for instance you were examining insect communities at 10 plots, 5 with say nitrogen treatment and 5 without) and you went 10 more times (50 surveys) to survey a plots in nitrogen treatment than a plot with no treatment (5 surveys) and said there is higher alpha-diversity in the nitrogen treatment, some folks would be sure to say your sampling was not even. I see this as the exact same problem with the microbiome sequencing coverage problem. I am sampling the gorillas 10x more than the chimpanzees.

For beta-diversity, I can see if you are using abundance weighted metrics that your should use normalized counts (I've been using metagenomeSeq CSS-normalization) to do your analyses. And from your paper you present that using deseq normalization is improved method for those for bray-curtis and weighted unifrac. However, correct me if I'm wrong, but you don't present information in using presence/absence beta-diversity metrics such as jaccard or unweighted unifrac when using deseq normalization or metagenomeseq normalization, etc. In the paper u-unifrac you present data on either rarefying or using relative abundance, and that using the relative abundance is poor compared to rarefying. Again, if you have a group or treatment that by chance has more sequencing coverage you are more likely to recover more species and then that group can look different because of the sequencing coverage. 

I am not opposed to not using rarefaction. I would love to, but can you tell me what am I supposed to do when I have a treatment group that has 10x more sequencing coverage and then shows higher abundance of all significant bacterial OTUs examined. **Do you think ignoring that issue of sequencing coverage being correlated to a treatment effect is better than ignoring the rarefying issue that you present in the plos paper?** That is really my problem at this point as it has arisen a few times in my analyses with either alpha-diversity or abundance of OTUs, and that is why rarefying for me seems to be the 'least worst of both evils'.
