### ISSUE TITLE
Barplot: Bars have colors not represented in the labels

### ISSUE THREAD

**Issue by rvanyperen** [joey711/phyloseq#615]
[screenshot.pdf](https://github.com/joey711/phyloseq/files/266918/screenshot.pdf)
I have filtered down to the top 50 OTUs for my samples, converted the OTU counts to relative abundance, and plotted the data using the command plot_bar(MyData, fill = "Rank6") + facet_grid(. ~ Grouping, scales = "free", space = "free").  ##Rank6 fills by genus

In the resulting plot I see a number of the bars have segments that are colored grey, but there is no grey box in the legend. How are these segments being filled in?

**Comment by montoyah** [comment]
Hi rvanyperen,

I have your same issue and it's due, I think, to NA present in the tables due to unresolved taxonomic levels. In my specific case, I have a single gray bar in my top 10 genera, and corresponds to the only unresolved genus in the subset. So far, I've been trying to do something like this (I expect to replace "NA" by "Desulfuromonadales"): 

scale_fill_manual( name = 'Genus',
                    breaks = c('Delftia', 'Escherichia-Shigella', 'Methanobacterium', 'Methanoculleus',
                                     NA', 'Pseudomonas(100)', 'Smithella(100)', 'Streptococcus(100)',
                                   'Treponema(82)', 'unclassified', 'Youngiibacter(100)'),
                    labels = c('Delftia', 'Escherichia-Shigella', 'Methanobacterium', 'Methanoculleus',
                               'Desulfuromonadales', 'Pseudomonas', 'Smithella', 'Streptococcus',
                               'Treponema', 'Desulfuromonadales', 'Youngiibacter'))

but I can't get the NA to show up in labels "breaks".

Another option would be manually modify the dataset to change that NA for something else so it will show up in the plot, but that would be my last resort. It's a "dirty" work around.

Any ideas?

**Comment by joey711** [comment]
Yes, you probably need to remove NAs prior to plotting, and perhaps choose a rank/level that does not have so many features for mapping color. At most you can only effectively map about 8 - 10 distinct things to color, and even that is often a heavy cognitive load for your audience.
