### ISSUE TITLE
changes to ordinate function with weighted UniFrac?

### ISSUE THREAD

**Issue by kh8046** [joey711/phyloseq#627]
Hi,

I am performing PCoA on weighted UniFrac distances of a 16S dataset that contains sequences from root and soil samples from different growing conditions.  After a recent update in my phyloseq version from 1.14 to 1.16, I have noticed that the ordination of the points and the percentage of variation explained by each axis is different. I could not figure out how to go back to v1.14, so I had a colleague with v1.14 run my code and produce the previous plot. Additionally, I also receive an error message with v1.16 that does not occur in v1.14, but the plot is still produced.  Was there a change in the way UniFrac is calculated between these 2 versions?  If so, how/why did it change, and would the old plot (v1.14) necessarily be "wrong"?  If there was no change, any idea on what is causing my error and the differences in the plots?

Below the code I am using plus error message, plot_ordination outputs for both versions and some info about my R session.

Any ideas/advice is much appreciated!
### v1.14

`CC_SE_rare_Wunifrac <- ordinate(CC_SE_bac_rare_RA_log2,method="PCoA",distance="wunifrac")`
`plot_ordination(CC_SE_bac_rare_RA_log2,CC_SE_rare_Wunifrac,color="Type")`

![v114](https://cloud.githubusercontent.com/assets/19904713/16005386/526c5c28-3167-11e6-960c-232dc5a5c3f1.png)
### v1.16

`CC_SE_rare_Wunifrac <- ordinate(CC_SE_bac_rare_RA_log2,method="PCoA",distance="wunifrac")`

`Warning message:
In matrix(tree$edge[order(tree$edge[, 1]), ][, 2], byrow = TRUE,  :
  data length [3775] is not a sub-multiple or multiple of the number of rows [1888]`

`plot_ordination(CC_SE_bac_rare_RA_log2,CC_SE_rare_Wunifrac,color="Type")`

![v116](https://cloud.githubusercontent.com/assets/19904713/16005441/9876ad22-3167-11e6-8f22-4e7608b7445c.png)
### R session info

R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.5 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] multcompView_0.1-7 doParallel_1.0.10  iterators_1.0.8    foreach_1.4.3      car_2.1-2  
 [6] picante_1.6-2      nlme_3.1-128       gridExtra_2.2.1    ape_3.5            gridBase_0.4-7  
[11] coin_1.1-2         survival_2.39-4    ggplot2_2.1.0      gplots_3.0.1       vegan_2.3-5  
[16] lattice_0.20-33    permute_0.9-0      phyloseq_1.16.2

**Comment by joey711** [comment]
@benjjneb do you have any idea? I think yours was the only change to UniFrac b/w 1.14 and 1.16 ... It's a little difficult to begin review because the correct result is not provided. @kh8046 do you have an external reference result of the ordination coordinates, scree values, or plot so that we have some idea which version is the odd-one-out? 

Btw, the 1.16 update was believed to be a performance modification only, and it passed our wunifrac unit tests the first try without any problems. I'm very surprised to see this.

**Comment by joey711** [comment]
@kh8046 can you provide the minimal reproducible example (data + code) to reproduce this?

**Comment by benjjneb** [comment]
My first guess is that this is from randomly choosing the root of the presumably unrooted phylogenetic tree differently.

**Comment by joey711** [comment]
Thanks, @benjjneb , good point.

Also @kh8046 , I noticed from your variable names that you may have done the following transformations on the same data:

- rarefying (Bad. Don't do this. Ever.)
- relative abundance (fine for wUniFrac for most datasets)
- log2 (was this after the previous two? but still provided to wUniFrac?)

The `log2` is especially strange because `log2(0)` is -infinite, and I'm yet to see a microbiome dataset without a zero in it. 

The full `data + code` would resolve these questions...

**Comment by kh8046** [comment]
Hi Guys,

Thanks for your fast responses. Below is a (hastily) put together example with the R code and the necessary input files to generate the PCoA plot I attached above for v1.16.  I hope my self-taught R skills are decipherable.

Addressing @joey711 's last post:

* You are right about rarefying the dataset, as you will see in the R code.  The decision to rarefy was made after many discussions of "Waste Not, Want Not", as well as the library normalization methods of metagenomeSeq, DESeq2, and edgeR, which did not address my issue of large differences in library size.  This discussion is probably best left for another post, but in the end, I followed the method outlined by Weiss et al. (2015) _Effects of library size variance, sparsity, and compositionality on the analysis of micrbiome data_

* The rarefied counts are transformed into relative abundance and expressed as %

* As you will see in the R code, I use ``log2 + 1`` of the rarefied, RA counts.  This was done after the advice of some colleagues that had used similar methods in the past.

Thanks for the help!

[WUniFrac_PCoA.zip](https://github.com/joey711/phyloseq/files/312703/WUniFrac_PCoA.zip)

**Comment by radikalana** [comment]
Hi kh8046!

I tried to obtain a PCoA based on weighted UniFrac distances, and always the same phyloseq version, and the plot changed each time I ran R. I realized that the phylogenetic tree I was using was unrooted and it was randomly rooting. So I rooted the tree and the problem was solved: now the PCoA is stable and don't change every time I run the script.

**Comment by joey711** [comment]
@radikalana thanks for that. I believe this was already suggested on another post, and unless I'm mistaken, we have code or PR sitting around to resolve this such that there's a clear definition of which root is being chosen, it is consistent, and an appropriate message is reported to user about the new root.

Cheers
