### ISSUE TITLE
DESeq2 dealing with 0 in OTU table

### ISSUE THREAD

**Issue by sfeds** [joey711/phyloseq#642]
Hi,
I was following the advice to work with DESeq2 with my phyloseq data described here:
http://joey711.github.io/phyloseq-extensions/DESeq2.html

For the step "DESeq2 conversion and call" I got an error due to plenty of 0 in my OTU table. 
Searching through the issues I saw a couple of fixes:
- adding 1 to the otu_table (which was later not recommended)
- creating and using the function:
gm_mean = function(x, na.rm=TRUE){
  exp(sum(log(x[x > 0]), na.rm=na.rm) / length(x))
}
geoMeans = apply(counts(diagdds), 1, gm_mean)
diagdds = estimateSizeFactors(diagdds, geoMeans = geoMeans)
diagdds = DESeq(diagdds, fitType="local")

I have used the latter and worked fine, but as I see that it's not included in the original .html site I was wondering whether this is still the recommended approach?

Thanks and great package!!
Susana

**Comment by vyom84** [comment]
Hi Susana,
               Did you able to know whether to use the geometric mean or the one described in the original HTML. I tried both, and they both give me different answers. When I did some literature hunting, I believe the geometric mean method more. Let me know, What your conclusion

Thanks
Harinder

**Comment by joey711** [comment]
@sfeds They're both okay, but perhaps not for your data, at least how its been processed up to this point. The modified geometric mean "works" with less filtering of OTUs/seqs/features, but that doesn't mean it's actually better. Many of these features that are zero in almost every observation (sample) should probably be removed from your data prior to attempting to fit the negative binomial using DESeq2. Adding a value of 1 to such a feature just makes this fact stand out, because now you have something that has a 1 in nearly every observation, which is very unlikely for NB distributed data. In an applied predictive modeling sense, these would be considered "near-zero variance" features that don't convey any useful information for predicting or explaining your sample classes. If you flip around the question, these features have only a trivial chance at being differentially abundant.

There are biologically realistic phenomena that can generate feature patterns like this (e.g. sample-specific sequence variants). However, I've found that for most datasets, many or most of these features are an artifact of the OTU clustering process itself. Rather than attempt the filtering post-hoc (which you should still explore), I recommend a more principled approach to processing your sequences, like [DADA2](http://benjjneb.github.io/dada2/):

http://benjjneb.github.io/dada2/

Even though these are exact sequence variants, I've found I usually end up with fewer features overall, due to the egregious false-positive rate of OTU-clustering methods. More importantly, these sequence variants usually have fewer examples of this "only in one/few sample" phenomena.

For filtering prior to testing, check out posts and doc for the `prune_taxa` method in phyloseq.

Hope that helps.
