### ISSUE TITLE
How to remove OTUs by name

### ISSUE THREAD

**Issue by lfaller** [joey711/phyloseq#652]
Hi all,

I have a list of OTUs that I want to remove from my phyloseq dataset.

I can access my OTU table using `otu_table(physeq_object)` and remove OTUs that way, but is there a better way to do this, so that the entire phyloseq object gets updated?

Thanks for any suggestions!
~Lina

**Comment by colinbrislawn** [comment]
How about this, from the [preprocessing tutorial](https://joey711.github.io/phyloseq/preprocess.html)?

```
myTaxa = names(sort(taxa_sums(GlobalPatterns), decreasing = TRUE)[1:10])
ex1 = prune_taxa(myTaxa, GlobalPatterns)
plot(phy_tree(ex1), show.node.label = TRUE)
```

**Comment by joey711** [comment]
Just to close this out, I think @lfaller is asking about a "pop" operation, like what happens with negative-integer indexing in many R `"["` operations.

```r
# Define the taxa you don't want like this:
badTaxa = c("bad1", "bad2", "bad3")
allTaxa = taxa_names(GlobalPatterns)
allTaxa <- allTaxa[!(allTaxa %in% badTaxa)]
ex1 = prune_taxa(myTaxa, GlobalPatterns)
# new phyloseq object with just the taxa you kept.
ex1
```

**Comment by joey711** [comment]
you can even define a function to do this in one line

```r
pop_taxa = function(physeq, badTaxa){
  allTaxa = taxa_names(physeq)
  allTaxa <- allTaxa[!(allTaxa %in% badTaxa)]
  return(prune_taxa(myTaxa, physeq))
}
```

Which you would then use as

```r
badTaxa = c("bad1", "bad2", "bad3")
GP2 = pop_taxa(GlobalPatterns, badTaxa)
```

**Comment by lfaller** [comment]
Yes, the pop_taxa function looks good for my immediate needs -- thanks!

I think the solution that @colinbrislawn suggested can also come in handy!

**Comment by dylandahan** [comment]
Hi,
I came across this while dealing with a similar issue of trying to remove taxa found in negative controls from samples and expanded the function a bit to suit my need. I initially tried to do this with just ``subset_samples`` and ``prune_taxa`` but could not, so please let me know if there is an easier/already existing way. 

```{r}
prune_negatives = function(physeq, negs, samps) {
  negs.n1 <- prune_taxa(taxa_sums(negs)>=1, negs) 
  samps.n1 = prune_taxa(taxa_sums(samps)>=1, samps) 
  allTaxa = names(sort(taxa_sums(physeq),TRUE))
  negtaxa = names(sort(taxa_sums(negs.n1),TRUE))
  taxa.noneg = allTaxa[!(allTaxa %in% negtaxa)]
  return(prune_taxa(taxa.noneg,samps.n1))
}
``` 

Could be used as

```{r}
#Subset samples to  negative controls
#phytest object has sample data variable sample_type with entries as either negative (for negative control) or sample
neg.cts = subset_samples(phytest, sample_type == "negative")
#Same but non negative control samples
samples = subset_samples(phytest, sample_type == "sample")

samps.noneg <- prune_negatives(phytest,neg.cts,samples)

```

**Comment by Nyangahu** [comment]
Hi guys,
Can we please revisit this script. I'm trying to do the same thing today and running into some problems.
# Define the taxa you don't want like this:
badTaxa = c("bad1", "bad2", "bad3")
allTaxa = taxa_names(GlobalPatterns)
allTaxa <- allTaxa[!(allTaxa %in% badTaxa)]
ex1 = prune_taxa(myTaxa, GlobalPatterns)
# new phyloseq object with just the taxa you kept.
ex1

I want to remove 6 OTUs that are predominant in the negative controls from my phyloseq object. I have defined them like this:

badTaxa = c("OTU_18", "OTU_5286", "OTU_2649", "OTU_1", "OTU_36", "OTU_4063")
allTaxa = taxa_names(phy)
allTaxa <- allTaxa[!(allTaxa %in% badTaxa)]

However, i don't have specific taxa i want to retain. Just need the above gone from "phy"
So the below script does not work since i haven't defined "myTaxa"
myTaxa = names(sort(taxa_sums(phy), decreasing = TRUE)[1:10])

Is there a way i can the "allTaxa" being converted to my new phyloseq since i have now removed the "badTaxa" that i do not need?

**Comment by jeffkimbrel** [comment]
Here is how I do it... a bit differently than the previous suggestions. It uses the base R set operations to get `goodTaxa`, and this is then used in the `prune_taxa()` function.

```
badTaxa = c("OTU_18",  "OTU_5286",  "OTU_2649",  "OTU_1",  "OTU_36",  "OTU_4063")
goodTaxa <- setdiff(taxa_names(phy), badTaxa)
phy2 <- prune_taxa(goodTaxa, phy)
```

BTW, I think the example you posted first actually has an error in it, which is why it didn't work for. `myTaxa` is probably supposed to be `allTaxa`. So, either try my method, or try the code you posted but using `allTaxa` instead.

**Comment by Nyangahu** [comment]
Thank you @jeffkimbrel . Your method works fine and thanks for the correction on the earlier code too. This will get me going for now.

**Comment by colinbrislawn** [comment]
Hello folks,

While we are on the topic of removing `badTaxa`, I wanted to mention that filtering your data sets bluntly can be really harmful. See this discussion:
https://forum.qiime2.org/t/filter-controls-or-not-to-filter-controls/1832 

Colin

**Comment by Nyangahu** [comment]
Thanks @colinbrislawn for the link. Very nice discussion going on. Infact, that is my current dilemma. I just did some 16S sequencing on lung samples and included negative controls in the run. Problem is i have all these contaminating OTUs that don't seem to be unique to negative controls. Taxa from other sources such as soil, freshwater etc that i have been trying to remove. Again, thanks for the link, following!

**Comment by colinbrislawn** [comment]
Yep. We are all having problems like this. I'm glad it's being noticed and hopefully it can be addressed.

In that thread, Ben mentioned [this preprint](https://www.biorxiv.org/content/early/2017/11/17/221499) and matching [R package](https://github.com/benjjneb/decontam) for removing contaminant sequences. Has anyone tried using these? Does the underlying method seem reasonable?

**Comment by jeffkimbrel** [comment]
I don't use it to remove contaminants, per se. We do a lot of host-microbe studies where we need to remove the host mitochondrial/chloroplast sequences. 

But, as you mention, it is good that more researchers are thinking about contamination. I haven't looked at Ben's latest preprint, but I'll check it out.

**Comment by Frederica1** [comment]
Hi, I'm trying to remove 2 OTUs from a phyloseq object. 
1. I don't understand how to assign the data I want to keep as object called myTaxa (I want to keep everything but the two OTUs I want to remove) - I don't undersatnd what that first line of code actually does. I have a total of 1009 OTU of which I try to remove two. 
2. how do I name the badTaxa, by OTU number? 

The code looks like this for now:

myTaxa = names(sort(taxa_sums(bc_metazoa), decreasing = TRUE)[1:1009])
badTaxa = c("c904a6966934ab3d91f6467603eb39460b42fe93", "77999e982c09ce41ca2a88e271088f94a99bb144")
allTaxa = taxa_names(bc_metazoa)
allTaxa <- allTaxa[!(allTaxa %in% badTaxa)]
ex1 = prune_taxa(myTaxa, bc_metazoa)

Thanks for your help!
