### ISSUE TITLE
Problems loading Mothur data

### ISSUE THREAD

**Issue by tdangelo12** [joey711/phyloseq#653]
I am trying to load Mothur data into phyloseq as follows:

taxonomy = system.file("extdata", "mimosa.an.cons.taxonomy", package="phyloseq")

This produces no error message, but nothing is loaded.  So tried this, although through autofilling with tab, R is finding the file

taxonomy = system.file("extdata", "mimosa.an.cons.taxonomy", package="phyloseq", mustWork = TRUE)
Error in system.file("extdata", "mimosa.an.cons.taxonomy", package = "phyloseq",  : 
  no file found

But file.exists can find the file:

> file.exists("mimosa.an.cons.taxonomy")
> [1] TRUE

Am I missing something?

Thanks

**Comment by joey711** [comment]
You are not creating a valid system path. In your code above, `taxonomy` is supposed to be a character string specifying a valid path to your data file, which is almost certainly not present within the installed location of the phyloseq package.

Please familiarize yourself further with R, system paths, etc. Since `file.exists` worked, the file you wanted to import was in fact present in your current working directory, and you probably could have just used something like:

```R
import_mothur("mimosa.an.cons.taxonomy")
```

Side note, I recommend using [DADA2](http://benjjneb.github.io/dada2/index.html) rather than mothur for your sequence processing...
