### ISSUE TITLE
DPCoA species coordinates missing?

### ISSUE THREAD

**Issue by nmshahir** [joey711/phyloseq#657]
Hello,

I'm trying to construct a DPCoa with my dataset and when I run plot_ordination on my data, it runs with the following warning:

> Species coordinates not found directly in ordination object. Attempting weighted average (`vegan::wascores`)
> Warning message:
> non-unique values when setting 'row.names': 

Code that was run

```
> data
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 869 taxa and 152 samples ]
sample_data() Sample Data:       [ 152 samples by 34 sample variables ]
tax_table()   Taxonomy Table:    [ 869 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 869 tips and 868 internal nodes ]

```

> data.dpcoa <- ordinate(data,"DPCoA")
> p <- plot_ordination(data, data.dpcoa, type="split",color="Phylum",shape="DiseaseStatus")
> 
> ```
> ```

Is that normal, or is something wrong with my physeq file or?

**Comment by joey711** [comment]
Can you post a MRE?

**Comment by nmshahir** [comment]
I could if I knew what that was?

**Comment by nmshahir** [comment]
Hopefully this is what you wanted?
`library("vegan")
library("MASS")
library("phyloseq")
library("ggplot2")

#### Import data files ####
GG.tree <- read_tree_greengenes("97_otus.tree")
test1 = biomformat::read_biom(biom_file='otu_table_filtered_json.biom')
mp0 = import_biom(test1, treefilename=GG.tree, parseFunction = parse_taxonomy_greengenes)
#Check ranks
rank_names(mp0)
qiimemap = import_qiime_sample_data("MicrobiomeMap.txt")
mp1 = merge_phyloseq(mp0,qiimemap)
all.1000 = prune_samples(sample_sums(mp1)>1000,mp1)
disease_set = as.vector(sample_data(all.1000)$DiseaseStatus=="disease")
disease = prune_samples(disease_set,all.1000)
disease = prune_taxa(taxa_sums(disease)>0,disease)
ord.dpcoa <- ordinate(disease,"DPCoA")

Dpcoa.pheno <- plot_ordination(disease, ord.dpcoa, type="split",color="Phylum",shape="pheno",title = "DPCoA: Disease Patients by Phenotype")`

> Species coordinates not found directly in ordination object. Attempting weighted average (`vegan::wascores`)
> Warning message:
> non-unique values when setting 'row.names':


Does that work?

**Comment by joey711** [comment]
Almost there. To actually be reproducible, one needs the data as well. Often users will demonstrate their issue with example datasets included in phyloseq, like `GlobalPatterns`.

**Comment by joey711** [comment]
@jfukuyama do you have any comment on this? Have you ever seen this problem?

**Comment by JacobRPrice** [comment]
@joey711 , was this issue ever resolved or it's cause located? 

I am getting the same error when I attempt to carry out DPCoA with my dataset and I've been unable to figure out what I'm doing wrong and/or how to correct it. 

My phyloseq object was created using Callahan et. al.'s pathway (doi: 10.12688/f1000research.8986.2). I understand you need the error to be reproducable; I'm willing to email you an .RDS of the phyloseq object if that's easiest (jrp355@drexel.edu). 

The code I'm attempting to execute is as follows:

```
# read in and prep ps object
ps_orig<-readRDS(file.path(data_path,"ps_orig.RDS"))
psB<-prune_samples(sample_data(ps_orig)$seqrun=="B",ps_orig)
psB<-prune_taxa(taxa_sums(psB)>0,psB)
ps0<-subset_taxa(psB, !is.na(Phylum) & !Phylum %in% c("", "uncharacterized"))
ps_filtered<-filter_taxa(ps0, function(x) sum(x > 10) >= 2, TRUE)
ps<-ps_filtered
pslog<-transform_sample_counts(ps,function(x) log(1+x))

# perform DPCoA ordination
out.dpcoa.log<-ordinate(pslog,method="DPCoA")
evals<-out.dpcoa.log$eig

# plot ordination
plot_ordination(pslog,
	out.dpcoa.log,
	type="split",
	color="Phylum",
	shape="Position",
	label="site",
	title="Split") +
	coord_fixed(sqrt(evals[2]/evals[1])) +
	theme(legend.position="bottom", 
		legend.margin=unit(0,"cm"), legend.text=element_text(size=5))
```
I'm given the following warning (matching what @nmshahir reports above): 

> Species coordinates not found directly in ordination object. Attempting weighted average (`vegan::wascores`)
> Warning message:
> non-unique values when setting 'row.names':  

A ggplot object is still returned and plotted. I'm not worried about the "scrunchy-ness" of the samples because, as you explained in issue #450, that's a result of the log transformation. If I use the non-log transformed sample counts (using "ps" instead of "pslog") the same warning message is returned. 

[plot.DPCoA.pdf](https://github.com/joey711/phyloseq/files/806881/plot.DPCoA.pdf)

Thanks for any insight you'd be able to provide!

Jake
