### ISSUE TITLE
plot_tree w unrooted tree?

### ISSUE THREAD

**Issue by mpnelsen** [joey711/phyloseq#669]
hi,

i have an unrooted tree and would like to plot the abundance of each tip/otu in different environments.  as i dont know where the root is, i'd prefer to plot it as an unrooted star-like phylogeny (rather than rectangular or circular).  is there a simple way to do this using the plot_tree function, or must the tree always be rectangular or circular?  thanks for your help.

-matt.

**Comment by joey711** [comment]
This should be possible with [ggtree](https://bioconductor.org/packages/release/bioc/html/ggtree.html)

phyloseq was the first package to support phylogenetic tree plotting via ggplot2, but ggtree has taken it to "the next level" in features, and I highly recommend using it for cases where `plot_tree` or other functions in phyloseq do not directly support what you want. A star plot happens to be one of these things, and I'm considering writing a "hand-off" function or at least document the procedure somewhere to make the hand-off easier. The object output from `phy_tree` is ready to be used by ggtree methods. However, it might be missing some of the microbiome experiment details that you'd want to add to your plot, requiring a few more commands on your part if you want to overlay these...

I will close for now, as I think the ggtree handoff is already a feature request in this issue tracker. If that turns out not to be the case, please feel free to re-open and ping me.
