### ISSUE TITLE
"tree file could not be read"

### ISSUE THREAD

**Issue by Maya0801** [joey711/phyloseq#681]
Hi,

I am new to phyloseq, and I am having problem in importing the tree file. 

The tree was constructed using qiime: 
make_phylogeny.py -i 6_align/seqs_derep_nochim_repotus_aligned_pfiltered.fasta -o 6_align/rep_set.tre --root_method tree_method_default --tree_method fasttree

and when I run the command: 

>tree <- read_tree("rep_set.tre", errorIfNULL=TRUE) 
 
I get the error:

Error in read_tree("rep_set.tre",  : 
  tree file could not be read.
Please retry with valid tree.

The tree doesn't upload also when I try to load it together with the biom file: 
> data <- import_biom("otu_table_blastn_s123_2s3t_nochl.biom", treefilename = "rep_set.tre")

Warning message:
In import_biom("C:/Users/Maya/OneDrive for Business/PhD/מחקר/Theonella/16S_amplicon/Data/otu_table_blastn_s123_2s3t_nochl.biom",  :
  treefilename failed import. It not included.

PS:
I used silva for taxonomic assingment, should I specify this somewhere in the commands?

Thanks

**Comment by dadahan** [comment]
Hi, running the commands on a fasttree .tre file, I did not receive this error but when providing the incorrect filename/path I did. Are you sure you're providing the correct relative or absolute path and filename?

For example,

```{r}
tree = read_tree("path/to/my/data/rep_set.tre")
```

If this doesn't work, you may want to give the ape package a try:
```{r}
tree = ape::read.tree("path/to/my/data/rep_set.tre")
```

**Comment by Maya0801** [comment]
it worked when I used this command:

tree = read_tree("path/to/my/data/rep_set.tre")
thanks so much!

**Comment by dadahan** [comment]
You only need one to work. Did the first run without errors? If so, see what happens when that is imported with your biom table. 
```{r}
tree = read_tree("C:/Users/Maya/OneDrive for Business/PhD/מחקר/Theonella/16S_amplicon/Data/rep_set.tre")
```

**Comment by Maya0801** [comment]
Hi Dylan,
Thank you for your quick reply.

neither of them worked, 
when I ran:
> tree = ape::read.tree("C:/Users/Maya/OneDrive for Business/PhD/מחקר/Theonella/16S_ampliconData/rep_set.tre")

I got the error:
Error in if (tp[3] != "") obj$node.label <- tp[3] :
missing value where TRUE/FALSE needed

When I ran: 
> tree = read_tree("C:/Users/Maya/OneDrive for Business/PhD/מחקר/Theonella/16S_amplicon/Data/rep_set.tre")

No error but the tree is NULL

**Comment by dadahan** [comment]
Alright, after some digging around it looks like the NULL may be due to semi-colon delimitation in taxa names on the nodes of a GreenGenes formatted tree. 
See here: #224 and here: and 04dc433 and here: [Somewhat flexible tree-import function](Somewhat flexible tree-import function)


Try this:
```{r}
tree = read_tree_greengenes("C:/Users/Maya/OneDrive for Business/PhD/מחקר/Theonella/16S_amplicon/Data/rep_set.tre")
```

Hope this helps. Happy to keep trying fixes.

**Comment by dadahan** [comment]
Just for clarity though, this is a new issue and the initial one was fixed by providing the correct path.

**Comment by Maya0801** [comment]
Hey Dylan,

Thanks for your help. that help the upload of the tree. However, now I have another issue now, because when we remove the semi colon from the tree the taxa names don't match up:

`> taxa_names(tree)[1:10]`
 [1] "'Maya5-196_26247><-><size=3><-><'"   "'Maya18-339_2898><-><size=3><-><'"  
 [3] "'Maya56-N1-RNA_155><-><size=1><-><'" "'Maya19-352_13306><-><size=3><-><'" 
 [5] "'Maya17-322_18014><-><size=1><-><'"  "'Maya18-339_8960><-><size=1><-><'"  
 [7] "'Maya7-211_19062><-><size=1><-><'"   "'Maya12-249_13377><-><size=4><-><'" 
 [9] "'Maya7-211_16386><-><size=1><-><'"   "'Maya11-248_4919><-><size=4><-><'"  
`> taxa_names(biomot)[1:10]`
 [1] "Maya10-232_755;size=18702;"  "Maya10-232_1049;size=12348;" "Maya10-232_708;size=18179;" 
 [4] "Maya10-232_5044;size=22289;" "Maya10-232_228;size=17322;"  "Maya10-232_6708;size=501;"  
 [7] "Maya10-232_266;size=10586;"  "Maya10-232_4822;size=25616;" "Maya10-232_1196;size=8372;" 
[10] "Maya11-248_3276;size=3672;" 

Should I convert the taxa names in the biom file? if yes, do you know a way to do it? 

Thanks you so much for your help!

PS: I used the whole file path in my first post, I just wanted to simply it, so I removed the long path.

**Comment by joey711** [comment]
This problem is because there is extra information being embedded in the field in the tree file that should just be the identity of the leaves, also called the "taxa name" in phyloseq. When you combine one data type with others in phyloseq, it takes the intersection of the IDs among them along the same dimension (samples or taxa). I can't see any reason you need the `;size=3672;` information at all at this stage in the analysis. The counts should already be stored in your biom file, or anything else that represents an sequence/OTU-by-sample table. 

I've probably done this before elsewhere in this forum, but you can write a regular expression that will remove everything from the first semi-colon to the end of the string for each of those tip names in the tree. I assume that is the difference between the tip IDs in this tree and the taxa names in your biom file. You'll have to check.

Some relevant commands

```r
gsub
taxa_names
taxa_names() <-
read_tree
merge_phyloseq
phyloseq
```

Fixing the problem with the tree tip names can be done in R/phyloseq via `taxa_names()`. Once you've done this, the tree can be joined/added to the rest of your phyloseq object using `phyloseq()` or `merge_phyloseq()`.

I'll close for now, but re-open if something else crops up.
