### ISSUE TITLE
plotting alpha diversity in clinical trial

### ISSUE THREAD

**Issue by AndreaQ7** [joey711/phyloseq#687]
Hi everyone,

I have alpha diversity values for 12 sample, that have been sampled 4 times during a clinical trial. I wanted to do a scatter plot with alpha diversity value for each sample at a specific data, and unify with a line the sample to see how does it change during time. 
I was following this tutorial in the section "Custom Alpha Diversity Grafic"
http://evomics.org/wp-content/uploads/2016/01/phyloseq-Lab-01-Answers.html

My data looks like that (i cut a part just to give you an idea)

Status	ID	variable	value
T-10	S1	Shannon	3.378081
T-10	S3	Shannon	3.846562
T-10	S4	Shannon	4.316614
T-10	S5	Shannon	3.903878
T-10	S6	Shannon	4.466978
T-10	S7	Shannon	4.099425
T-10	S8	Shannon	3.613751
T-10	S9	Shannon	4.21184
T0	S1	Shannon	3.41776
T0	S3	Shannon	4.197096
T0	S4	Shannon	4.151618
T0	S5	Shannon	3.749968
T0	S6	Shannon	4.447208
T0	S7	Shannon	4.090328
T0	S8	Shannon	3.438264
T0	S9	Shannon	4.277432
T30	S1	Shannon	3.771578
T30	S4	Shannon	4.303618
T30	S5	Shannon	4.008355
T30	S6	Shannon	4.092389
T30	S7	Shannon	4.41824
T30	S8	Shannon	4.253617
T30	S9	Shannon	4.234923

were Status should be the date and ID are the sample i want to scatter with their respective value.
I wrote this command line (following the tutorial i said before) after have extracted the shannon value

>ggplot(data = alphadt,mapping = aes(Status, value,color = ID)) + geom_point(size = 5) + geom_path()
geom_path: Each group consists of only one observation. Do you need to adjust the group aesthetic?

but i get only the scatter point for every sample without the line to connect each other during time.
Why? does anyone can help me?
thank you all for your help

**Comment by joey711** [comment]
This is a ggplot2 question. Please see the documentation for `geom_path`. There is a huge amount of ggplot2 doc available. Please make use of it.

Based on the error returned and what you specified, it looks like `geom_path` needs to be told how to group variables for drawing the path, and I suspect this is because your x-axis is a categorical variable as-defined (even though I think it is actually a continuous time variable). You could either change `Status` to a numeric variable, or offer an extra aesthetic variable to indicated groups: `geom_path(aes(group = ID))`.

Hope that helps. I'll close because this is really a question for ggplot2 forums.
