### ISSUE TITLE
biom convert not working

### ISSUE THREAD

**Issue by Ambmoose** [joey711/phyloseq#716]
I have been having a problem converting my .biom files to .txt files, and would appreciate any suggestions. I have .biom files that I created in qiime 1.9.1 and ran this command: 

biom convert -i table.biom -o table.from_biom_w_taxonomy.txt --to-tsv --header-key taxonomy

It ran for approximately 1 hour and then stopped, and said "Killed:9".

**Comment by cpauvert** [comment]
hi @Ambmoose,
Depending on `biom` version, it could be memory greedy, hence the process could have been killed.

What `biom` version do you run? 2.1.5 ?

By the way, I am not sure it is a `phyloseq` related issues

Cheers,

**Comment by ariverosw** [comment]
Hello,

I'm having a similar issue and I'm running version 2.1.5. Is there anything I can do to fix this. Fortunately is not crushing for all samples, thought I can't tell specifically if it is a memory issue or not since there is no output addressing why the job was actually killed. I really appreciate the help.

Cheers,

Alejandro

**Comment by cpauvert** [comment]
Hi Alejandro,
Are you running biom on a cluster or on your personal computer? The output message may have sinked into a file that you need to find.
Sorry, I don't understand "is not crushing for all samples", do you mean that with fewer samples it runs ok?

Charlie

**Comment by ariverosw** [comment]
Hi Charlie,

Thanks for the reply!!!. I'm running it in a cluster. I looked everywhere for any message other than the"killed".
Well I'm running a qiime on several fasta files from a number of samples. I reckon that if the input fasta is not too big (<3Gb) then biom convert finished successfully. If fasta files are big it crushed. I went a little ahead and try a run of only biom convert with 250Gb of RAM. Then the program finishes. I did this because what you say before in this thread about biom convert being a bit memory greedy. 
This whole issue is breaking the slurm script for the job and then I have to launch an additional job with more memory to finish the broken pipeline. I don't know if you know a "trick" to control the memory required for biom convert. 
I'm running qiime with 20 processors and 88Gb of RAM. 

Cheers,
Alejandro
