### ISSUE TITLE
Question about what trimming OTUs is doing

### ISSUE THREAD

**Issue by coyk** [joey711/phyloseq#741]
Hi,
 I've been tying myself in knots trying to figure out how to interpret a result.
 Bathy_ps1_exp
#This is original phyloseq object.  103683 OTUs, 10 samples, 3 variables, 6 tax ranks

Bathy_ps1_exp_trim <- prune_taxa(taxa_sums(Bathy_ps1_exp) > 1, Bathy_ps1_exp)
#I THOUGHT this was trimming out singletons, but it's actually omitting OTUs from the data that don't #occur at least TWICE, no?  Even removing an OTU that only occurs in one sample does not take into #account abundance within OTU, right?  If I had an OTU that only occurred in 1 sample, but the OTU #represented 3 million sequences, that OTU would still be trimmed right? Anyway, moving on.....

Bathy_ps1_B689_exp_trim <- subset_samples(Bathy_ps1_exp_trim, dive == "B689")
#just interested in OTUs from one variable "B689"

Bathy_ps1_B689_exp_trimb <- prune_taxa(taxa_sums(Bathy_ps1_B689_exp_trim) > 1, Bathy_ps1_B689_exp_trim)
#again, THOUGHT I was trimming out singletons.  Probably don't need to do this

#I'm interested in what genera are represented in this group that aren't found in the other groups.  I #made files as above from the other variables in order to compare/contrast.  Using get_unique_taxa, I #found two genera that only occur in B689.  One was Campylobacter. I searched a Mothur taxonomy #file for Campylobacter and got back 2 representative sequences.  One sequence represents itself and #one represents 2 sequences.  Both of these OTUs only occur in B689 (of course, because that's what I #was looking for) and have 1 and 2 sequences associated.  So if I trimmed my OTUs above so that my #data wouldn't have OTUs that weren't in at least 2 groups, how did I recover the answer I did?  What is #prune_taxa doing?  In other words, to me, if I'm interested in finding OTUs unique to a sample site, I #would only do the prune_taxa thing with >0. because this gets rid of OTUs that are zero across all #samples, right?  But again,, how was I able to recover a genus that had 2 representative OTUS that only #occurred in a single group?

**Comment by campenr** [comment]
If you look at the documentation for `taxa_sums` it is just a convenience wrapper for `rowSums`, so it is calculating the total abundance of that taxa across all samples. Using `prune_taxa(taxa_sums(physeq) > 1, physeq)` should be removing any taxa whose row sums comes to less than 2 irrespective of whether this taxa is present in one or two samples.

You can visualize this easily by inverting the pruning here with `otu_table(prune_taxa(taxa_sums(physeq) <= 1, physeq))` which creates an otu_table of singletons (and missing i.e. row sums of 0).

So in regards to your statement 

>  If I had an OTU that only occurred in 1 sample, but the OTU #represented 3 million sequences, that OTU would still be trimmed right?

The answer is no. If an OTU has an abundance of 3 million sequences, then it should be represented in the OTU table as having an abundance of 3 million. In this situation the row sum, and therefore the taxa sum for that OTU/taxa is going to be three million (plus more if that OTU is present in more samples). Therefore, `prune_taxa(taxa_sums(physeq) > 1, physeq)` would **NOT** remove this OTU.

If you **DO** want more complicated trimming so that you are removing an OTU that does not appear in at least two samples (irrespective of actuall abundance within those samples) you can use a more complicated pruning procedure using [filterfun](https://www.rdocumentation.org/packages/phyloseq/versions/1.16.2/topics/filterfun_sample).

But to just get the OTUs that are present in only one sample then you could calculate the taxa sums for all samples, and just subset those taxa where the taxa sum is equal to the abundance in your sample (after removing any missing i.e. abundance of zero, OTUs).

**Comment by joey711** [comment]
Thanks @campenr 

I would add that there is a phyloseq-specific wrapper for filterfun, see `?filter_taxa`

As for filtering terminology, I try to be consistent in describing filtering based on a **minimum abundance** criteria as an **abundance filter**. For filtering based on the minimum number of samples in which a taxa appeared, I refer to this as a **minimum prevalence** criteria, or **prevalence filter**.

There are examples of these types of filters applied to real data in a number of places in phyloseq documentation. I'll consider this issue closed for now unless something new pops up.
