### ISSUE TITLE
Pipeline Comparison

### ISSUE THREAD

**Issue by rlh13** [joey711/phyloseq#809]
Hello,
I am trying to compare the results of DADA2 and QIIME on the same set of samples. I have created 2 different phyloseq objects for the DADA2 and QIIME output to do intra-pipeline comparison. My question now is: do I merge these phyloseq objects or is there a way to compare them while separate? If I merge them, I saw [this post](https://github.com/joey711/phyloseq/issues/508) but was wondering if it will work to merge the sample data files since they have the same sample names? I did add a column to each sample data object to include the Pipeline (i.e. DADA2 or QIIME). I also didnt really understand how to use merge_taxa to match the OTU IDs of the two tables (we did use the same reference for classification).

Any help is appreciated! Thank you!

**Comment by joey711** [comment]
Following the instructions on that post, you will need to modify the sample names to get them in the same object, since you cannot have duplicate column names. You can preserve the sample names in a `sample_data` variable for this purpose, and then that is also the variable you would specify in comparisons...

Given what I know about QIIME-based OTUs, I wouldn't advise spending too much time thinking about or considering QIIME unless you have some unavoidable and specific reason (for that matter, use USEARCH if you have to do OTUs at all) ... but if you do, would you mind posting your finding here?

**Comment by joey711** [comment]
I will close for now, but please post what you find :-)

**Comment by rlh13** [comment]
Hi Joey I'm sorry but I would like to keep this open to figure this out. I don't really understand your explanation. I would like to still compare the DADA2 and QIIME results if possible so could you please advise further on how to do so? I am still unclear as to whether I need to merge my phyloseq objects and what you mean by preserving the sample names in a sample_data variable (I already have the mapping info preserved in a sample_data variable for each of the 2 phyloseq objects I would like to compare. 

Thank you

**Comment by werdnus** [comment]
Hey @rlh13, I've done some OTU/DADA2 comparisons, but I've not taken it out as far as it sounds like you're going. 

I think what @joey711's saying is that you _can_ merge the two phyloseq objects, but you'll have to make sure the sample names are unique. You could do that by doing something like this, I think:
```
sample_names(phyloseq_object_with_DADA2) <- paste(sample_names(phyloseq_object_with_DADA2), "dada", sep="_")

sample_names(phyloseq_object_with_QIIME) <- paste(sample_names(phyloseq_object_with_QIIME), "qiime", sep="_")
```
To preserve the original samples names, I think he's suggesting doing something like this before modifying the sample names, so that they end up in the `sample_data`. I think this makes a lot of sense if you opt to do something like use sequential numbering for the new sample names, but probably isn't necessary if you just append an identifier for each batch, as above.
```
sample_data(phyloseq_object_with_DADA2)$old_name <- sample_names(phyloseq_object_with_DADA2)
```
I guess the question of "do you have to merge them?" depends on how you want to compare them... I think if I were in your shoes, I'd probably do it.

**Comment by rlh13** [comment]
Hi @werdnus thank you for your help! I guess my follow-up question from this is how to construct a tree for this merged phyloseq object? I have done this before for the phyloseq objects containing the results from DADA2 using the seqtab.nochim (sequence table with no bimeras) object but how would I do this with the new phyloseq object I have? I would like to be able to do this so I can perform UniFrac analyses. Thank you again!

**Comment by werdnus** [comment]
You're outside my area of expertise with that one, @rlh13: I work with fungal ITS, which is a region that cannot be aligned for dissimilar taxa, so I don't use UniFrac. 

But, I guess you'll use the reference sequence for each taxon in your `tax_table`, build your tree with whatever your favourite tree-building software is, and then add that to the phyloseq object with `phy_tree()`. You'll need to use tools outside of phyloseq, whatever you do.  

Good luck!

**Comment by rlh13** [comment]
Thanks for the help @werdnus! I'll have to experiment and see if I can work this one out.

**Comment by ireceptor** [comment]
Hi @rlh13 , I'm trying to do the same comparison with my data. Just want to follow up if you have figured out a way? Thanks.

**Comment by rlh13** [comment]
Hi @ireceptor, yes I was able to do this by appending the sample names in each of the separate phyloseq objects with _Q (for QIIME) or _D (for DADA2). I also added a column to my mapping files "Pipeline" that specified which pipeline was used for the analysis (QIIME or DADA2). Once I did this, I was able to merge them.

**Comment by ireceptor** [comment]
Hi @rlh13 , thanks for your quick reply. I have another question: since the results from QIIME and DADA2 have different OTU names, when you merge two objects the OTUs are not merged. Would that affect the distances between groups and the final PCoA result? Thanks.

**Comment by rlh13** [comment]
Hi @ireceptor, you're correct. We didn't look at the PCoA distances between the two for this reason. We were primarily focused on the differences in taxonomic classification between the two.

**Comment by ireceptor** [comment]
Hi @rlh13, I think the other way to use the PCoA is that merge all the OTUs at the Genus level so that they would have the same name, which is the name of bacteria. I tried with my data and the data from QIIME and DADA2 can be clustered separately. I don't know if this is a correct way.
