### ISSUE TITLE
Phyloseq Unifrac root tree issue

### ISSUE THREAD

**Issue by RicardoGCCR** [joey711/phyloseq#828]
Hi, 
I am very new in this and maybe someone can help me. I am trying to run UNIFRAC (Phyloseq) but the function is not recognizing the root of my tree. And I get the following message:

Warning message:
In UniFrac(physeq, ...) :
  Randomly assigning root as -- Bartonella_sp_OE_1_1_variant_H -- in the phylogenetic tree in the data you provided.

But I did root my tree! After importing my tree I wrote the following commands:
>tree_Q3 = root(treebartY, "'Brucella_abortus_strain_MC_(CP022879.1", resolve.root = TRUE)
>is.rooted(tree_Q3) 
[1] TRUE
>physeq1 = merge_phyloseq(physeq, sampledata2, tree_Q3)
>physeq1
>UniFrac(physeq1)

Can someone tell me what's my mistake?
Thanks

**Comment by drcarrot** [comment]
Hi! Perhaps this helps

tree=read.tree(file="rep_set.tre")
tree=root(**phy_tree(tree)**, sample(taxa_names(tree), 1), resolve.root = TRUE)

**Comment by RicardoGCCR** [comment]
Thanks for the fast response. 
Indeed the warning message is not appearing after that!
However, with the command: 
tree=root(phy_tree(tree), sample(taxa_names(tree), 1), resolve.root = TRUE)
How do I specify that the root is the specific taxa "Brucella..."?

Thanks again

**Comment by joey711** [comment]
@RicardoGCCR find the specific ID from `taxa_names(tree)` that you want to use as root, and use that as the second argument to `root` instead of that `sample` command (which would select a random root).

In fact, a random root is not necessarily what you want, even if it gets rid of the warning. Ideally you would pick a deterministic root based on a justifiable criterion (like connected to longest branch, known to be different from most other taxa in that environment, etc.).

The "one-liner" to update the tree in your phyloseq object is:

```R
phy_tree(physeq) <- root(phy_tree(physeq), "root_id", resolve.root = TRUE)
```

Where you've replaced `"root_id"` with the specific taxa ID of the thing you've selected or reproducibly-randomly chosen as root; and `physeq` is your phyloseq object.
