### ISSUE TITLE
Relative abundance Bar Plots for select Taxa

### ISSUE THREAD

**Issue by jjscarpa** [joey711/phyloseq#840]
Hi. 

I am following your bar plot tutorial and am using `transform_sample_counts` to get relative abundance data at the bacterial Class level for all of my samples. Facet, box-and-whiskers plots.  

What I would like to do is generate the same abundance plots but for specific groups, Say Orders within the Betas. I can do this fine with `subset_taxa ` but then relative abundance is just based on the Beta totals and not the whole dataset--which is what I am looking for. 

I have tried using `sample_sums ` to get sums for all samples and then using that as a variable in `transform_sample_counts ` to get relative abundance but since I am writing my code does not work :)

`sub_beta <- subset_taxa(ps_gg_filt, Class =="c__Betaproteobacteria")` #1st I pull out Betas
`sub_beta_order <- tax_glom(sub_beta, taxrank = "Order", NArm = FALSE)`#1st I pull out Betas
`sums_total <- sample_sums(ps_gg_filt)` ##Then I get sample totals from the Original phyloseq object
`transform_sample_counts(sub_beta_order, function(x) x/sums_total)`##Here I try to use sample totals from the original phyloseq object to get relative abundance of each Order. 

Any help would be, well, very helpful. 

Thanks!

**Comment by joey711** [comment]
Please post a [MRE](https://stackoverflow.com/a/5963610/935950). Will close for now.

**Comment by cedwardson4** [comment]
Could you just run the subset_taxa on your relative abundance transformed object?

ps_gg_filt_RA<-transform_sample_counts(ps_gg_filt, function(x) x / sum(x) 
sub_beta_RA <- subset_taxa(ps_gg_filt_RA, Class =="c__Betaproteobacteria")
sub_beta_order_RA <- tax_glom(sub_beta_RA, taxrank = "Order", NArm = FALSE)

**Comment by jjscarpa** [comment]
yup, thanks @cedwardson4. Great idea! Transform  before subsetting. That did the trick. 

And thanks @joey711 for passing along the tutorial on MRE. I will be sure to include this in any future questions.

**Comment by gmteunisse** [comment]
@jjscarpa, I'm creating a package that contains a function that creates relative abundance plots for phyloseq objects. It also allows you to do faceting and to color by taxonomic levels of interest. Have a look and please let me know whether it helped you! It's the `fantaxtic_bar` function from the [Fantaxtic package](https://github.com/gmteunisse/Fantaxtic).

**Comment by joey711** [comment]
I don't understand why "fantaxtic" is a package and not a pull request or snippet... code examples or a ggplot2 theme and color palettes are all pretty standard steps in someone creating or customizing a figure. The choice to output "vanilla" ggplot2 objects without special palettes or themes was an intentional feature, not a bug. This makes it much less confusing for the user to customize after the fact using standard ggplot2 documentation. "do faceting and color by taxonomic levels" is already a supported feature of phyloseq, and there are *lots* of examples of this...

**Comment by gmteunisse** [comment]
@joey711 Thanks for the feedback. I did not mean to criticize phyloseq in any way, I love the package. I was not aware that you accepted input for phyloseq, I'd be happy to file a pull request some day. I need some more testing before doing that though, which is why I'd like people to try things out first. I also thought it could be handy for @jjscarpa.

I agree that these are pretty standard steps, but I don't think it to be superfluous. I am well aware that a similar function exists within phyloseq ([examples](https://joey711.github.io/phyloseq/plot_bar-examples.html)), but it does not generate subrank shades for the color of a higher level taxonomy (i.e. all genera for a phylum get the same base color, but different shades). I'd like to invite you or anybody to try it and let me know what you think!

**Comment by joey711** [comment]
@gmteunisse part of that is my fault for not having good doc for dev contributions. I also haven't been great about merging in PRs quickly. That is mostly a time constraint. I have to prioritize maintenance of current features over adding new features that then also need to be maintained.

I do like the idea of a consistent color palette that simultaneously indicates phylum along with a lower taxonomic rank. The limits of our eyeballs means that it won't work for all data, but in the case of small numbers of phyla/genera, it could make for a nice presentation. If you already have an example vignette to point to, I'm happy to take a look.

**Comment by gmteunisse** [comment]
@joey711 Yes, with more than ~7 shades it becomes hard to distinguish. There's an HTML vignette with some examples available in the package, you can find it using `browseVignettes("fantaxtic")` after installing the package.
