### ISSUE TITLE
Results different from qiime2

### ISSUE THREAD

**Issue by Biancabrown** [joey711/phyloseq#856]
Hi, 
I'm currently in the process of analyzing data. I used dada2 get the results transfer that sequence table to qiime2, assign taxonomy in qiime2 and port to phyloseq for analysis. The issue is that although the otu_table and tax_table is the same in qiime2 and phyloseq at the beginning of the analysis(I checked the stats etc.) when I remove Chloroplast and Archea, the number of sequences and OTUs I have remaining are different between the two pipelines. Any thoughts as to why? 

Thanks in advance.

**Comment by colinbrislawn** [comment]
In specific situations, phyloseq will drop samples / OTUs / tree tips if they do not match inside of your object. For example, `tax_glom()` uses `NArm=TRUE` by default, resulting in less OTUs depending on how this merge happens.

```
psobject %>% tax_glom("Rank4") # makes more taxa
psobject %>% tax_glom("Rank5") %>% tax_glom("Rank4") # makes fewer taxa
```
Even though these two commands will both output objects gloms at the Rank4 level, glomming by Rank5 first will drop OTUs without tax due to`NArm=TRUE`, ending up with fewer OTUs at the end.

I'm not sure what's in your pipeline, but I would check on all the settings of your functions, and see when something is getting merged / dropped. My guess is it's happening in the `filter_taxa()` command... 

Colin

P.S. If this answers your question, feel free to close this issue.
