### ISSUE TITLE
Correlating relative abundance to continuous variable

### ISSUE THREAD

**Issue by GeoMicroSoares** [joey711/phyloseq#858]
Hello there,

I'm looking to show the correlation between relative abundance of some of my SVs and a continuous variable. However, can't seem to figure out how to access geom_smooth's data on the R2, for example.

In the reproducible example below, using the enterotype dataset, I subset it to hold only the 5 most abundant OTUs, leave only the samples with proper values for age and gender to then check correlation of OTU relative abundance to Age.

What's missing is just a way to also plot the R2 of the correlation, possibly with values from cor.kendall.SV1_ent_df. 
I've tried annotate() but I'm sure there's a better way to do that!

Any help? @benjjneb @joey711 

Thanks in advance!
```
data(enterotype)
myTaxa = names(sort(taxa_sums(enterotype), decreasing = TRUE)[1:5])
ex1 = prune_taxa(myTaxa, enterotype)
ex1 = subset_samples(ex1, Gender != "NA")
ex1 = subset_samples(ex1, Age != "NA")
ex1.r = transform_sample_counts(ex1, function(x) x/sum(x))
taxa_names(ex1.r) <- paste0("SV_", seq(ntaxa(ex1.r)))

#check correlations
SV1_ent = as(otu_table(ex1.r), "matrix")
if(taxa_are_rows(ex1.r)){SV1_ent <- t(SV1_ent)}
SV1_ent_df = as.data.frame(SV1_ent)
cor.kendall.SV1_ent_df = cor(SV1_ent_df, 
                                     sample_data(ex1.r)$Age, 
                                     method = "kendall")
#doesn't matter if correlations <0.5 in this context
cor.kendall.SV1_ent_df
#quickly check them in a basic plot
plot(sort(cor.kendall.SV1_ent_df, decreasing = TRUE))

#in my study, I subset only the OTUs holding correlation values >0.5. and them psmelt() that phyloseq object.

ex1.r.psdf <- data.table(psmelt(ex1.r))
ex1.r.psdf.plot<-ggplot(ex1.r.psdf[Abundance > 0], 
                      aes(x = Age, y = Abundance, fill=OTU)) + 
  facet_grid(~Gender, scales="free_x") +
  geom_point(aes(color=OTU, fill=OTU,
                 size=Abundance)) +
  geom_smooth(aes(color=OTU, fill=OTU),
              method='lm', se=FALSE) +
  theme(axis.title.x = element_blank())+ 
  guides(fill = guide_legend(keywidth = 1, keyheight = 1)) +
  scale_y_log10() +
  ylab("Relative Abundance\n")

ex1.r.psdf.plot
```
Correlation plot (y=Kendall-Tau's correlation of the top 5 OTUs with Age)
![image](https://user-images.githubusercontent.com/14272488/33901150-c582a590-df68-11e7-9a15-1916d6e21273.png)
Relative abundance plot facetted by Gender, using geom_smooth to draw rel.abund.+age regression lines (x=Age).
![image](https://user-images.githubusercontent.com/14272488/33901158-cc008392-df68-11e7-9256-1347bd5e890c.png)

**Comment by joey711** [comment]
The notion of regression of these count against continuous variable(s) is not a new problem, and I would recommend using one of these methods rather than simple correlation. There are many well-known characteristics of this kind of count data that make the correlation dubious at best, invalid at worst.

I will *close* this issue for now, since it is more a discussion topic for analysis rather than a feature or bug, but this is just a categorization of the issue. It does not prevent further discussion, examples, etc.

**Comment by fabipc** [comment]
Hi GeoMicroSoares  and Joey711, 

I have a quick question for you guys. I am following your tutorial above, but I wanted to see, once I filter my physeq object to Genus and calculate the relative abundance of the new "Genus-table", how can I trim my dataset to include only the top 10 most abundant species in the Genus level and or should I not be doing this, since I am filtering at a given abundance?Please note, my OTU table has already been rarefied, so I am unsure if I should have an abundance value and or not. 

Additionally, after trimming my table to the top10 abundant species, how can I add those names to my new table to check for correlations?

This is my code, thus far. 
Genus-table <- physeq.b %>%
  tax_glom(taxrank = "Genus") %>%                                  # agglomerate at phylum level
  transform_sample_counts(function(x) {x/sum(x)} ) %>%  # Transform to rel. abundance
  psmelt() %>%                                                                     # Melt to long format
  filter(Abundance > 0.02) %>%                                            # Filter out low abundance taxa
  arrange(Genus)                                      # Sort data frame alphabetically by phylum

**Comment by marwa38** [comment]
@joey711 
Any current function for correlation analysis of microbiota?
Thanks 
M
