### ISSUE TITLE
rarefy_even_depth removes samples below subsample depth

### ISSUE THREAD

**Issue by mc68462** [joey711/phyloseq#910]
General issues with rarefying data aside, the phyloseq function rarefy_even_depth removes samples which fall below the subsampling depth. It would be great to have a boolean option to keep samples below subsampling threshold. To do this now, I have to create 2 different phyloseq objects, one to be subsampled and one not, followed by merging. Is there an easier way to do this with the current version of phyloseq or could it be added to future updates?

Thanks,
Meghan

**Comment by joey711** [comment]
The current behavior of the function is the working definition of "rarefying" in common use. 

The only reason I included the function in phyloseq was to make it easier to compare with legitimate analysis methods so that people can objectively evaluate how bad it is. Same reason I included the complete code in [Waste Not, Want Not](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003531)...

Since this is the case, adding more "features" to the function is not something I'm going to include in phyloseq. I apologize in advance if someone is requiring that you rarefy in your work because they do not know better. Your time is probably better spent convincing them not to rarefy in the first place.

I will close for now. Feel free to post back if I have misunderstood your request/post.
