### ISSUE TITLE
Error with Using Fills and Scaling.

### ISSUE THREAD

**Issue by astoriadetuncq** [joey711/phyloseq#947]
Hello,
Disclaimer: I am very new to R and Phyloseq, so I'm sorry in advance if this is really stupid. I am trying to set up a bar plot for a biom file. I can create the bar plot, but I am having issues setting up the fill. Here is the code that I tried:

`plot_bar(biom_otu_tax, fill="family")`

And this is the error message that I received:

`Don't know how to automatically pick scale for object of type function. Defaulting to continuous.
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 0, 419994`

The file has components that are typical of genetic analysis, i.e. OTU, Sample, Rank, Abundance, etc. 

There are 23333 taxa, 7 tax ranks, and 18 samples. 

Attached below is a file with an excerpt of the sample data that I am trying to graph. I would like to have the families of each sample be filled with varying color. What would be the best way to go about this?

[Sample Data.txt](https://github.com/joey711/phyloseq/files/2040623/Sample.Data.txt)

**Comment by ianartmor** [comment]
Hi AstoriaD, welcome!

A couple things:

1) `family()` is a built-in function in R, which is causing that error. 
2) It looks like your rank names are Rank1, Rank2, etc. rather than Kingdom, Phylum, etc. so it it probably would not have worked anyway.

You can figure out / change your rank names using `rank_names()`. Rank5 is probably family assuming you used the GreenGenes reference, which it looks like based on your prefixes.

Ian

**Comment by astoriadetuncq** [comment]
@ianartmor 

Thanks so much for your help! I think the root of the problem was that I did not assign the correct rank names.
